# Generated by Django 5.2.5 on 2025-08-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('sales', 'Sales'), ('manager', 'Manager'), ('finance', 'Finance')], default='sales', max_length=20),
        ),
    ]
