# Generated by Django 5.2.5 on 2026-01-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('AIR', 'Air Freight'), ('SEA', 'Sea Freight'), ('LAND', 'Land Freight')], help_text='Department assignment for visibility restrictions (e.g., Air vs Sea).', max_length=10, null=True),
        ),
    ]
