# Generated by Django 5.2.5 on 2026-05-28 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_organization'),
        ('core', '0011_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_departments',
            field=models.JSONField(blank=True, default=list, help_text="List of additional authorized department codes (e.g. ['AIR', 'CUSTOMS'])."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='authorised_locations',
            field=models.ManyToManyField(blank=True, help_text='All authorized branch locations this user can access.', related_name='authorised_users', to='core.location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='primary_location',
            field=models.ForeignKey(blank=True, help_text='Primary home branch location for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='core.location'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('AIR', 'Air Freight'), ('SEA', 'Sea Freight'), ('LAND', 'Land Freight / Inland Transport'), ('CUSTOMS', 'Customs')], help_text='Primary department assignment for visibility restrictions.', max_length=10, null=True),
        ),
    ]
