# Generated by Django 5.2.5 on 2026-06-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_buy_charges_override',
            field=models.BooleanField(default=False, help_text='Explicitly allow viewing buy cost data regardless of role.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_margins_override',
            field=models.BooleanField(default=False, help_text='Explicitly allow viewing margins regardless of role.'),
        ),
    ]
