# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_permission_role_rolepermission_role_permissions_and_more"),
        ("parties", "0011_branch_operating_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermembership",
            name="operating_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_memberships",
                to="parties.operatingentity",
            ),
        ),
    ]
