[pytest]
DJANGO_SETTINGS_MODULE = rate_engine.settings
addopts =
    --ignore=test_dg_charge.py
    --ignore=test_general_cargo.py
    --ignore=test_import_engine.py
    --ignore=test_pom_syd_100kg.py
    --ignore=test_export_quote.py
    --ignore=test_output.txt
