from decimal import Decimal
from io import BytesIO
import logging

from django.conf import settings
from django.utils import timezone

from fpdf import FPDF

from .models import Shipment
from .services import get_or_create_shipment_settings

logger = logging.getLogger(__name__)


def _clean_text(value) -> str:
    if value is None:
        return ""
    text = str(value)
    replacements = {
        "\u2013": "-",
        "\u2014": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2022": "-",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text.encode("latin-1", "replace").decode("latin-1")


def _format_weight(value) -> str:
    return f"{float(value or 0):,.2f}"


def _format_choice(value) -> str:
    return str(value or "").replace("_", " ").title()


def _build_shipment_record_url(shipment: Shipment) -> str:
    return f"{settings.FRONTEND_BASE_URL.rstrip('/')}/shipments/{shipment.id}"


def _build_qr_image(url: str) -> BytesIO | None:
    try:
        import qrcode
    except ModuleNotFoundError:
        logger.warning("qrcode package is not installed; shipment PDF will omit the QR image.")
        return None

    qr = qrcode.QRCode(box_size=4, border=1)
    qr.add_data(url)
    qr.make(fit=True)
    image = qr.make_image(fill_color="black", back_color="white")
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)
    return buffer


class ConnotePDF(FPDF):
    def __init__(self, shipment: Shipment, footer_lines: list[str]):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.shipment = shipment
        self.footer_lines = footer_lines
        self.set_auto_page_break(auto=True, margin=26)
        self.alias_nb_pages()

    def footer(self):
        self.set_y(-20)
        self.set_draw_color(203, 213, 225)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_y(self.get_y() + 2)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(71, 85, 105)
        self.cell(140, 3.5, _clean_text(self.footer_lines[0]), new_x="RIGHT", new_y="TOP")
        self.cell(50, 3.5, _clean_text(f"Page {self.page_no()}/{{nb}}"), align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_x(10)
        self.cell(190, 3.5, _clean_text(self.footer_lines[1]), new_x="LMARGIN", new_y="NEXT")


def _party_lines(prefix: str, shipment: Shipment) -> list[str]:
    values = [
        getattr(shipment, f"{prefix}_company_name"),
        getattr(shipment, f"{prefix}_contact_name"),
        getattr(shipment, f"{prefix}_address_line_1"),
        " ".join(
            part
            for part in [
                getattr(shipment, f"{prefix}_address_line_2"),
                getattr(shipment, f"{prefix}_city"),
                getattr(shipment, f"{prefix}_state"),
                getattr(shipment, f"{prefix}_postal_code"),
            ]
            if part
        ).strip(),
        getattr(shipment, f"{prefix}_country_code"),
    ]
    return [line for line in values if line]


def _metadata_value(shipment: Shipment, key: str) -> str:
    return str((shipment.metadata or {}).get(key, "") or "").strip()


def _piece_actual_weight(piece) -> Decimal:
    return Decimal(piece.piece_count or 0) * Decimal(piece.gross_weight_kg or 0)


def generate_shipment_pdf(shipment: Shipment) -> bytes:
    settings_obj = get_or_create_shipment_settings(shipment.organization)
    branding = getattr(shipment.organization, "branding", None)
    record_url = _build_shipment_record_url(shipment)
    qr_image = _build_qr_image(record_url)
    generated_by = (
        getattr(shipment.updated_by, "username", None)
        or getattr(shipment.finalized_by, "username", None)
        or getattr(shipment.created_by, "username", None)
        or "system"
    )
    footer_lines = [
        f"Generated by {generated_by} on {timezone.now():%d %b %Y %H:%M}",
        settings_obj.default_disclaimer,
    ]

    pdf = ConnotePDF(shipment, footer_lines)
    pdf.add_page()
    pdf.set_fill_color(15, 42, 86)
    pdf.set_text_color(255, 255, 255)
    pdf.rect(10, 10, 190, 30, style="F")

    if branding and getattr(branding, "logo_primary", None):
        try:
            pdf.image(branding.logo_primary.path, x=14, y=14, w=36)
        except Exception:
            pass

    pdf.set_xy(54, 14)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(92, 7, _clean_text((branding.display_name if branding else "") or "EFM Air Freight"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(54)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(92, 5, "AIR FREIGHT CONNOTE", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(54)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(92, 5, _clean_text(shipment.connote_number or "Draft"), new_x="LMARGIN", new_y="NEXT")

    if qr_image is not None:
        pdf.image(qr_image, x=170, y=13, w=24, h=24, link=record_url)

    pdf.set_text_color(71, 85, 105)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_xy(118, 42)
    pdf.cell(80, 4, _clean_text(f"Shipment Date: {shipment.shipment_date:%d %b %Y}"), align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(118)
    pdf.cell(80, 4, _clean_text(f"Branch: {shipment.branch or '-'}"), align="R", new_x="LMARGIN", new_y="NEXT")

    def party_block(x, title, lines):
        pdf.set_xy(x, 54)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(92, 6, title)
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(203, 213, 225)
        pdf.rect(x, 61, 92, 36, style="DF")
        pdf.set_xy(x + 3, 64)
        pdf.set_font("Helvetica", "", 8)
        for line in lines:
            pdf.multi_cell(86, 4.2, _clean_text(line))
            pdf.set_x(x + 3)

    party_block(10, "Shipper Details", _party_lines("shipper", shipment))
    party_block(108, "Consignee Details", _party_lines("consignee", shipment))

    pdf.set_xy(10, 103)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 6, "Shipment Details", new_x="LMARGIN", new_y="NEXT")
    pdf.set_fill_color(248, 250, 252)
    pdf.rect(10, 109, 190, 30, style="DF")
    pdf.set_xy(13, 113)
    pdf.set_font("Helvetica", "", 8)
    detail_rows = [
        f"Shipment Type: {_format_choice(shipment.shipment_type)}",
        f"Origin: {shipment.origin_code} {shipment.origin_name}".strip(),
        f"Destination: {shipment.destination_code} {shipment.destination_name}".strip(),
        f"Service Type: {_format_choice(shipment.service_product)}",
        f"Scope: {_format_choice(shipment.service_scope)}",
        f"Payment Type: {_format_choice(shipment.payment_term)}",
        f"Booking Ref: {_metadata_value(shipment, 'booking_reference') or shipment.reference_number or '-'}",
        f"Flight Ref: {_metadata_value(shipment, 'flight_reference') or '-'}",
    ]
    for index, line in enumerate(detail_rows):
        column_x = 13 if index % 2 == 0 else 103
        row_y = 113 + ((index // 2) * 6)
        pdf.set_xy(column_x, row_y)
        pdf.cell(90, 4, _clean_text(line))

    pdf.set_xy(10, 145)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(190, 6, "Cargo Details", new_x="LMARGIN", new_y="NEXT")
    pdf.set_fill_color(15, 42, 86)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    headers = [
        ("Piece", 16),
        ("Qty", 16),
        ("Package", 28),
        ("Dimensions (cm)", 46),
        ("Actual", 24),
        ("Vol", 24),
        ("Chargeable", 32),
    ]
    pdf.set_x(10)
    for label, width in headers:
        pdf.cell(width, 7, label, align="C", fill=True)
    pdf.ln(7)

    pdf.set_text_color(15, 23, 42)
    pdf.set_font("Helvetica", "", 8)
    for piece in shipment.pieces.all():
        pdf.set_x(10)
        pdf.cell(16, 7, str(piece.line_number), border=1, align="C")
        pdf.cell(16, 7, str(piece.piece_count), border=1, align="C")
        pdf.cell(28, 7, _clean_text(piece.package_type or "PCS"), border=1)
        pdf.cell(46, 7, _clean_text(f"{piece.length_cm} x {piece.width_cm} x {piece.height_cm}"), border=1)
        pdf.cell(24, 7, _clean_text(_format_weight(_piece_actual_weight(piece))), border=1, align="R")
        pdf.cell(24, 7, _clean_text(_format_weight(piece.volumetric_weight_kg)), border=1, align="R")
        pdf.cell(32, 7, _clean_text(_format_weight(piece.chargeable_weight_kg)), border=1, align="R")
        pdf.ln(7)

    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(190, 6, "Handling / Declaration Notes", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8)
    note_lines = []
    if shipment.handling_notes:
        note_lines.append(f"Special Handling: {shipment.handling_notes}")
    if shipment.is_dangerous_goods or shipment.dangerous_goods_details:
        note_lines.append(f"DG Notes: {shipment.dangerous_goods_details or 'Declared as dangerous goods.'}")
    if shipment.is_perishable or shipment.perishable_details:
        note_lines.append(f"Perishable Notes: {shipment.perishable_details or 'Perishable cargo handling required.'}")
    if shipment.declaration_notes:
        note_lines.append(f"Declaration Notes: {shipment.declaration_notes}")
    if shipment.shipment_type == Shipment.ShipmentType.EXPORT:
        export_details = [
            _metadata_value(shipment, "export_reference"),
            _metadata_value(shipment, "invoice_reference"),
            _metadata_value(shipment, "permit_reference"),
            _metadata_value(shipment, "customs_notes"),
        ]
        labeled_export_lines = [
            f"Export Ref: {export_details[0]}" if export_details[0] else "",
            f"Invoice Ref: {export_details[1]}" if export_details[1] else "",
            f"Permit Ref: {export_details[2]}" if export_details[2] else "",
            f"Export Notes: {export_details[3]}" if export_details[3] else "",
        ]
        note_lines.extend([line for line in labeled_export_lines if line])
    if not note_lines:
        note_lines.append("No additional handling or declaration notes recorded.")
    pdf.multi_cell(190, 4.5, _clean_text("\n".join(note_lines)))

    output = pdf.output(dest="S")
    if isinstance(output, (bytes, bytearray)):
        return bytes(output)
    return output.encode("latin-1")
