# Generated by Django 5.2.5 on 2025-09-17 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('country_code', models.CharField(default='PG', max_length=2)),
                ('audience', models.TextField()),
                ('default_sell_currency', models.TextField()),
                ('gst_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disbursement_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursement_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.organizations')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.organizations')),
            ],
            options={
                'db_table': 'sites',
            },
        ),
    ]
