"""
Django settings for rate_engine project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from the backend directory (explicit path)
load_dotenv(BASE_DIR / '.env')


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name: str) -> list[str]:
    raw = os.environ.get(name, '')
    return [item.strip() for item in raw.split(',') if item.strip()]



# (BASE_DIR defined above)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY: DEBUG defaults to False for safety
DEBUG = _env_bool('DJANGO_DEBUG', False)

# SECURITY: SECRET_KEY must be set in environment (no fallback in production)
_dev_secret_key = 'django-insecure-dev-only-key-do-not-use-in-production'
_secret_key = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not _secret_key:
    # Only allow insecure default in explicit development mode
    if DEBUG:
        _secret_key = _dev_secret_key
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY environment variable is required. "
            "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(50))\""
        )

if not DEBUG:
    if _secret_key == _dev_secret_key or _secret_key.lower().startswith('django-insecure'):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is using an insecure development value. "
            "Set a strong production secret key."
        )
    if len(_secret_key) < 50:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is too short for production. "
            "Use at least 50 characters of entropy."
        )

SECRET_KEY = _secret_key

# SECURITY: ALLOWED_HOSTS must be explicitly configured
ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS')
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
elif not ALLOWED_HOSTS and not DEBUG:
    raise ImproperlyConfigured("ALLOWED_HOSTS must be set in production")

# ============================================================================
# PRODUCTION SECURITY HARDENING
# ============================================================================
# These defaults are strict in production and can still be overridden with envs.
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = _env_bool('SESSION_COOKIE_HTTPONLY', True)
CSRF_COOKIE_HTTPONLY = _env_bool('CSRF_COOKIE_HTTPONLY', True)
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')

SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool('SECURE_CONTENT_TYPE_NOSNIFF', True)
SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'DENY')

_hsts_default = '31536000' if not DEBUG else '0'
_hsts_seconds_raw = os.environ.get('SECURE_HSTS_SECONDS', _hsts_default)
try:
    SECURE_HSTS_SECONDS = int(_hsts_seconds_raw)
except ValueError as exc:
    raise ImproperlyConfigured("SECURE_HSTS_SECONDS must be an integer") from exc

SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', not DEBUG)

# Enable this when Django is behind a trusted reverse proxy forwarding HTTPS.
if _env_bool('USE_X_FORWARDED_PROTO', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'core',
    'parties',
    'quotes',
    'ratecards',
    'services',
    'pricing_v4',  # Greenfield pricing engine
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rate_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Project-level templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rate_engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Development may fall back to SQLite, but production must provide DATABASE_URL.
_database_url = os.environ.get('DATABASE_URL', '').strip()
if not DEBUG and not _database_url:
    raise ImproperlyConfigured("DATABASE_URL must be set in production")

if _database_url:
    _default_db = dj_database_url.parse(
        _database_url,
        conn_max_age=600,
        conn_health_checks=True,
    )
else:
    _default_db = dj_database_url.parse(
        f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )

DATABASES = {
    'default': _default_db
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/topics/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Project-level static files
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Collected static files for production
MEDIA_URL = '/media/'
# Uploaded branding assets are currently stored under BASE_DIR/branding/... via upload_to.
# Keeping MEDIA_ROOT at BASE_DIR preserves existing uploaded logo paths during beta.
MEDIA_ROOT = BASE_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

# SECURITY: CORS configured from environment (no allow-all in production)
_cors_origins = _env_list('CORS_ALLOWED_ORIGINS')
if _cors_origins:
    CORS_ALLOWED_ORIGINS = _cors_origins
    CORS_ALLOW_ALL_ORIGINS = False
elif DEBUG:
    # Allow localhost origins in development
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:3001',
        'http://127.0.0.1:3001',
    ]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOWED_ORIGINS = []
    CORS_ALLOW_ALL_ORIGINS = False

_csrf_trusted_origins = _env_list('CSRF_TRUSTED_ORIGINS')
if _csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS = _csrf_trusted_origins
elif DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:3001',
        'http://127.0.0.1:3001',
    ]
else:
    CSRF_TRUSTED_ORIGINS = []

REST_FRAMEWORK = {
    # Secure-by-default: endpoints must explicitly opt out (e.g. public quote links).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Rate limiting to prevent brute force and DoS attacks
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',      # Anonymous users: 20 requests per minute
        'user': '100/minute',     # Authenticated users: 100 requests per minute
        'login': '5/minute',      # Login attempts: 5 per minute (brute force protection)
    },
}

# Public quote share links (customer-facing).
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'http://localhost:3000')
_public_quote_ttl = os.environ.get('PUBLIC_QUOTE_LINK_TTL_SECONDS', str(60 * 60 * 24 * 7))
try:
    PUBLIC_QUOTE_LINK_TTL_SECONDS = int(_public_quote_ttl)
except ValueError:
    PUBLIC_QUOTE_LINK_TTL_SECONDS = 60 * 60 * 24 * 7

# AI intake model configuration (Gemini)
GEMINI_MODEL_NAME = (
    os.environ.get('GEMINI_MODEL_NAME', 'gemini-2.5-flash-lite').strip()
    or 'gemini-2.5-flash-lite'
)

# Explicit SPOT coverage overrides for known lanes.
SPOT_ROUTE_COVERAGE = {
    # Export D2A lanes we already have origin coverage for.
    'export_d2a_lanes': [
        'POM-SIN',
        'POM-HKG',
        'POM-BNE',
        'POM-SYD',
        'POM-VLI',
        'POM-HIR',
        'POM-NAN',
        'POM-CNS',
    ],
    # Import: we always have destination A2D coverage in PNG.
    'import_a2d_destination_global': True,
    # Import D2A lanes with known airfreight coverage.
    'import_d2a_lanes': [
        'BNE-POM',
        'SYD-POM',
    ],
}

# Fallback airport-country resolver for SPOT intake when country is missing in payload.
SPOT_AIRPORT_COUNTRY_MAP = {
    'POM': 'PG',
    'LAE': 'PG',
    'MTV': 'PG',
    'SIN': 'SG',
    'HKG': 'HK',
    'BNE': 'AU',
    'SYD': 'AU',
    'CNS': 'AU',
    'NAN': 'FJ',
    'HIR': 'SB',
    'VLI': 'VU',
}

# Optional non-PNG cross-trade allowlist, e.g. ["SYD-SIN"].
# Empty by default to preserve PNG-only policy.
_spot_non_png = os.environ.get('SPOT_ALLOWED_NON_PNG_LANES', '')
SPOT_ALLOWED_NON_PNG_LANES = [
    lane.strip().upper() for lane in _spot_non_png.split(',') if lane.strip()
]

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
# Structured logging for production environments (outputs to console for containers)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'console_debug': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Django's default logger
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        # Django request logging (4xx and 5xx errors)
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Dev server access logs (avoid duplicate emission via parent/root loggers)
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Security-related logs (bad host headers, CSRF failures, etc.)
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Application-specific loggers
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'quotes': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'pricing_v4': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
