# Generated by Django 5.2.5 on 2025-10-23 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(blank=True, help_text='Auto-generated human-readable ID.', max_length=50, unique=True)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], default='AIR', max_length=10)),
                ('shipment_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], default='IMPORT', max_length=10)),
                ('incoterm', models.CharField(blank=True, help_text='Incoterm code (e.g., EXW, FOB, DAP, DDP). Null for Domestic.', max_length=3, null=True)),
                ('payment_term', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], default='PREPAID', max_length=10)),
                ('valid_until', models.DateField(blank=True, help_text='Date the quote expires.', null=True)),
                ('origin_code', models.CharField(blank=True, help_text='Origin location code (e.g., Airport IATA, Port UN/LOCODE).', max_length=10, null=True)),
                ('destination_code', models.CharField(blank=True, help_text='Destination location code.', max_length=10, null=True)),
                ('is_dangerous_goods', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('INCOMPLETE', 'Incomplete (Missing Data)')], default='DRAFT', max_length=20)),
                ('request_details_json', models.JSONField(blank=True, help_text='Store the original V3 API request payload for reference/replay.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Specific contact person at the customer company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='parties.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='The primary customer requesting the quote.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_customer', to='parties.company')),
                ('fx_snapshot', models.ForeignKey(blank=True, help_text='The exact FX snapshot used for this quote calculation.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fxsnapshot')),
                ('output_currency', models.ForeignKey(default='PGK', help_text='The currency the final quote totals are presented in.', on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('policy', models.ForeignKey(blank=True, help_text='Policy version used (may be overridden by customer profile).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.policy')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteTotal',
            fields=[
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='totals', serialize=False, to='quotes.quote')),
                ('subtotal_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_total_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('grand_total_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('output_currency', models.CharField(default='PGK', max_length=3)),
                ('grand_total_output_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('ORIGIN', 'Origin'), ('FREIGHT', 'Freight'), ('DESTINATION', 'Destination'), ('INFO_ONLY', 'Informational Only')], max_length=20)),
                ('charge_code', models.CharField(help_text="e.g., 'FREIGHT', 'CARTAGE', 'AW'", max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('basis', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('buy_amount_native', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_amount_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_amount_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('caf_applied_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('margin_applied_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('rounding_applied', models.BooleanField(default=False)),
                ('source_references', models.JSONField(blank=True, help_text="Links to sources, e.g., {'surcharge_id': '.', 'service_component_id': '.'}", null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField(help_text='Sequential version number (e.g., 1, 2, 3).')),
                ('payload_json', models.JSONField(help_text='The V3 API request payload used for this calculation.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('INCOMPLETE', 'Incomplete (Missing Data)')], default='DRAFT', help_text='Status of the quote at the time this version was created.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="Reason for creating this new version (e.g., 'Customer requested change', 'Initial Draft').", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fx_snapshot', models.ForeignKey(help_text='FX snapshot used for this version.', on_delete=django.db.models.deletion.PROTECT, to='core.fxsnapshot')),
                ('policy', models.ForeignKey(blank=True, help_text='Policy snapshot used for this version (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.policy')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotes.quote')),
            ],
            options={
                'ordering': ['quote', '-version_no'],
                'unique_together': {('quote', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='OverrideNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(help_text="Identifier of what was overridden (e.g., 'scope', 'manual_rate:FRT_AIR', 'margin_pct').", max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('reason', models.TextField(help_text='Mandatory reason for the override.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='quotes.quoteversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
