# Generated by Django 5.2.5 on 2025-09-25 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('validity_days', models.PositiveIntegerField(default=7)),
                ('service_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], max_length=20)),
                ('terms', models.CharField(choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CIP', 'CIP'), ('CPT', 'CPT'), ('DAP', 'DAP'), ('DDP', 'DDP')], max_length=20)),
                ('scope', models.CharField(choices=[('D2D', 'Door–Door'), ('D2A', 'Door–Airport'), ('A2D', 'Airport–Door'), ('A2A', 'Airport–Airport')], max_length=20)),
                ('payment_term', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], max_length=20)),
                ('sell_currency', models.CharField(default='PGK', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('volumetric_divisor', models.PositiveIntegerField(default=6000)),
                ('volumetric_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('chargeable_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('carrier_code', models.CharField(blank=True, max_length=3, null=True)),
                ('service_level', models.CharField(blank=True, max_length=50, null=True)),
                ('transit_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('routing_details', models.TextField(blank=True, null=True)),
                ('fx_snapshot', models.JSONField()),
                ('policy_snapshot', models.JSONField()),
                ('rate_provenance', models.JSONField(default=dict)),
                ('sell_currency', models.CharField(max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('calc_version', models.CharField(default='qe-0.1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.station')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.station')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotes.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ORIGIN', 'Origin'), ('AIR', 'Air'), ('DESTINATION', 'Destination')], max_length=12)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=255)),
                ('basis', models.CharField(choices=[('PER_KG', 'Per Kg'), ('FLAT', 'Flat'), ('PERCENT', 'Percent')], default='FLAT', max_length=10)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('extended_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='SELL', max_length=5)),
                ('is_taxable', models.BooleanField(default=True)),
                ('min_charge_applied', models.BooleanField(default=False)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('currency', models.CharField(default='PGK', max_length=3)),
                ('source_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='quotes.quoteversion')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_cm', models.PositiveIntegerField()),
                ('width_cm', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='quotes.quoteversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer', '-created_at'], name='quotes_quot_custome_9caf7c_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteversion',
            index=models.Index(fields=['quotation', '-version_no'], name='quotes_quot_quotati_3cedad_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteversion',
            index=models.Index(fields=['origin', 'destination', '-created_at'], name='quotes_quot_origin__d23a86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quoteversion',
            unique_together={('quotation', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['version', 'side', 'stage'], name='quotes_char_version_bdb4a8_idx'),
        ),
    ]
