# Generated by Django 5.2.5 on 2025-11-06 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('parties', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number (e.g., 1, 2, 3).')),
                ('payload_json', models.JSONField(blank=True, help_text='The V3 API request payload used for this calculation.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('INCOMPLETE', 'Incomplete (Missing Data)')], default='DRAFT', help_text='Status of the quote at the time this version was created.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="Reason for creating this new version (e.g., 'Customer requested change', 'Initial Draft').", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fx_snapshot', models.ForeignKey(blank=True, help_text='FX snapshot used for this version.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fxsnapshot')),
                ('policy', models.ForeignKey(blank=True, help_text='Policy snapshot used for this version (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.policy')),
            ],
            options={
                'ordering': ['quote', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(blank=True, help_text='Auto-generated human-readable ID.', max_length=50, unique=True)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], default='AIR', max_length=10)),
                ('shipment_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], default='IMPORT', max_length=10)),
                ('incoterm', models.CharField(blank=True, help_text='Incoterm code (e.g., EXW, FOB, DAP). Null for Domestic.', max_length=3, null=True)),
                ('payment_term', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], default='PREPAID', max_length=10)),
                ('output_currency', models.CharField(default='PGK', help_text='The 3-letter ISO currency code the quote is presented in.', max_length=3)),
                ('valid_until', models.DateField(blank=True, help_text='Date the quote expires.', null=True)),
                ('origin_code', models.CharField(blank=True, help_text='Origin location code (e.g., Airport IATA, Port UN/LOCODE).', max_length=10, null=True)),
                ('destination_code', models.CharField(blank=True, help_text='Destination location code.', max_length=10, null=True)),
                ('is_dangerous_goods', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('INCOMPLETE', 'Incomplete (Missing Data)')], default='DRAFT', max_length=20)),
                ('request_details_json', models.JSONField(blank=True, help_text='Store the original V3 API request payload for reference/replay.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Specific contact person at the customer company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='parties.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='The primary customer requesting the quote.', on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_customer', to='parties.company')),
                ('fx_snapshot', models.ForeignKey(blank=True, help_text='The exact FX snapshot used for this quote calculation.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fxsnapshot')),
                ('policy', models.ForeignKey(blank=True, help_text='Policy version used (may be overridden by customer profile).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.policy')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteTotal',
            fields=[
                ('quote_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='totals', serialize=False, to='quotes.quoteversion')),
                ('total_cost_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_pgk_incl_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_fcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_fcy_incl_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_fcy_currency', models.CharField(default='PGK', max_length=3)),
                ('has_missing_rates', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='quoteversion',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotes.quote'),
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_fcy', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_fcy_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('sell_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_pgk_incl_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_fcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_fcy_incl_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_fcy_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('cost_source', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_source_description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_rate_missing', models.BooleanField(default=False)),
                ('service_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.servicecomponent')),
                ('quote_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quoteversion')),
            ],
        ),
        migrations.CreateModel(
            name='OverrideNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(help_text="Identifier of what was overridden (e.g., 'manual_rate:FRT_AIR').", max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('reason', models.TextField(help_text='Mandatory reason for the override.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='quotes.quoteversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='quoteversion',
            unique_together={('quote', 'version_number')},
        ),
    ]
