# Generated by Django 5.2.5 on 2025-10-23 20:04

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicecomponent_description'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='output_currency',
        ),
        migrations.AddField(
            model_name='quote',
            name='output_currency',
            field=models.CharField(default='PGK', help_text='The 3-letter ISO currency code the quote is presented in.', max_length=3),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(help_text='The primary customer requesting the quote.', on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_customer', to='parties.company'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='incoterm',
            field=models.CharField(blank=True, help_text='Incoterm code (e.g., EXW, FOB, DAP). Null for Domestic.', max_length=3, null=True),
        ),
        migrations.RenameField(
            model_name='quoteversion',
            old_name='version_no',
            new_name='version_number',
        ),
        migrations.AlterModelOptions(
            name='quoteversion',
            options={'ordering': ['quote', '-version_number']},
        ),
        migrations.AlterUniqueTogether(
            name='quoteversion',
            unique_together={('quote', 'version_number')},
        ),
        migrations.AlterField(
            model_name='quoteversion',
            name='fx_snapshot',
            field=models.ForeignKey(blank=True, help_text='FX snapshot used for this version.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fxsnapshot'),
        ),
        migrations.AlterField(
            model_name='quoteversion',
            name='payload_json',
            field=models.JSONField(blank=True, help_text='The V3 API request payload used for this calculation.', null=True),
        ),
        migrations.DeleteModel(
            name='QuoteLine',
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_fcy', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_fcy_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('sell_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_pgk_incl_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_fcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_fcy_incl_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_fcy_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('cost_source', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_source_description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_rate_missing', models.BooleanField(default=False)),
                ('quote_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quoteversion')),
                ('service_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.servicecomponent')),
            ],
        ),
        migrations.DeleteModel(
            name='QuoteTotal',
        ),
        migrations.CreateModel(
            name='QuoteTotal',
            fields=[
                ('quote_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='totals', serialize=False, to='quotes.quoteversion')),
                ('total_cost_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_pgk', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_pgk_incl_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_fcy', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_fcy_incl_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sell_fcy_currency', models.CharField(default='PGK', max_length=3)),
                ('has_missing_rates', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='overridenote',
            name='field',
            field=models.CharField(help_text="Identifier of what was overridden (e.g., 'manual_rate:FRT_AIR').", max_length=100),
        ),
    ]
