# Generated by Django 5.2.5 on 2025-08-25 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('length_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('width_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='quotes.quote')),
            ],
        ),
    ]
