# Generated by Django 5.2.5 on 2025-10-22 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fxsnapshot_caf_percent_fxsnapshot_fx_buffer_percent'),
        ('parties', '0002_customercommercialprofile'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='bill_to',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='request_details',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipper',
        ),
        migrations.AddField(
            model_name='quote',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Specific contact person at the customer company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='parties.contact'),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The primary customer requesting the quote.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_customer', to='parties.company'),
        ),
        migrations.AddField(
            model_name='quote',
            name='incoterm',
            field=models.CharField(blank=True, help_text='Incoterm code (e.g., EXW, FOB, DAP, DDP). Null for Domestic.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_dangerous_goods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='mode',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], default='AIR', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='output_currency',
            field=models.ForeignKey(default='PGK', help_text='The currency the final quote totals are presented in.', on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_term',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], default='PREPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='request_details_json',
            field=models.JSONField(blank=True, help_text='Store the original V3 API request payload for reference/replay.', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='shipment_type',
            field=models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], default='IMPORT', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='fx_snapshot',
            field=models.ForeignKey(blank=True, help_text='The exact FX snapshot used for this quote calculation.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fxsnapshot'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='Policy version used (may be overridden by customer profile).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.policy'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('INCOMPLETE', 'Incomplete (Missing Data)')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='buy_amount_native',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='sell_amount_pgk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='source_references',
            field=models.JSONField(blank=True, help_text="Links to sources, e.g., {'surcharge_id': '.', 'service_component_id': '.'}", null=True),
        ),
        migrations.AlterField(
            model_name='quotetotal',
            name='grand_total_pgk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotetotal',
            name='gst_total_pgk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotetotal',
            name='subtotal_pgk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
