# Generated by Django 5.2.5 on 2025-10-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE VIEW quotes_quoteversion_totals AS
            SELECT
              qv.id AS quote_version_id,
              SUM(CASE WHEN c.side = 'SELL' AND c.stage = 'ORIGIN' THEN c.extended_price ELSE 0 END) AS sell_origin,
              SUM(CASE WHEN c.side = 'SELL' AND c.stage = 'AIR' THEN c.extended_price ELSE 0 END) AS sell_air,
              SUM(CASE WHEN c.side = 'SELL' AND c.stage = 'DESTINATION' THEN c.extended_price ELSE 0 END) AS sell_destination,
              SUM(CASE WHEN c.side = 'SELL' THEN c.extended_price ELSE 0 END) AS sell_total,
              SUM(CASE WHEN c.side = 'BUY' THEN c.extended_price ELSE 0 END) AS buy_total,
              SUM(CASE WHEN c.side = 'SELL' AND c.is_taxable THEN c.extended_price * (c.gst_percentage / 100.0) ELSE 0 END) AS tax_total,
              SUM(CASE WHEN c.side = 'SELL' THEN c.extended_price ELSE 0 END) + SUM(CASE WHEN c.side = 'SELL' AND c.is_taxable THEN c.extended_price * (c.gst_percentage / 100.0) ELSE 0 END) AS grand_total,
              SUM(CASE WHEN c.side = 'SELL' THEN c.extended_price ELSE 0 END) - SUM(CASE WHEN c.side = 'BUY' THEN c.extended_price ELSE 0 END) AS margin_abs,
              (SUM(CASE WHEN c.side = 'SELL' THEN c.extended_price ELSE 0 END) - SUM(CASE WHEN c.side = 'BUY' THEN c.extended_price ELSE 0 END)) * 100.0 / NULLIF(SUM(CASE WHEN c.side = 'SELL' THEN c.extended_price ELSE 0 END), 0) AS margin_pct
            FROM quotes_quoteversion qv
            LEFT JOIN quotes_charge c ON qv.id = c.version_id
            GROUP BY qv.id;
            """,
            reverse_sql="DROP VIEW IF EXISTS quotes_quoteversion_totals;"
        )
    ]
