# Generated by Django 5.2.5 on 2025-11-08 23:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_quote_locations(apps, schema_editor):
    """
    Copies the old origin_code/destination_code strings into the
    new origin_airport/destination_airport/port ForeignKeys.
    """
    Quote = apps.get_model('quotes', 'Quote')
    Airport = apps.get_model('core', 'Airport')
    Port = apps.get_model('core', 'Port')

    airports = {a.iata_code: a for a in Airport.objects.all()}
    ports = {p.unlocode: p for p in Port.objects.all()}

    quotes_to_update = []

    for quote in Quote.objects.all():
        updated = False

        if quote.origin_code:
            if quote.origin_code in airports:
                quote.origin_airport = airports[quote.origin_code]
                updated = True
            elif quote.origin_code in ports:
                quote.origin_port = ports[quote.origin_code]
                updated = True

        if quote.destination_code:
            if quote.destination_code in airports:
                quote.destination_airport = airports[quote.destination_code]
                updated = True
            elif quote.destination_code in ports:
                quote.destination_port = ports[quote.destination_code]
                updated = True

        if updated:
            quotes_to_update.append(quote)

    if quotes_to_update:
        Quote.objects.bulk_update(
            quotes_to_update,
            ['origin_airport', 'destination_airport', 'origin_port', 'destination_port'],
        )
        print(f"Successfully backfilled locations for {len(quotes_to_update)} quotes.")


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='destination_airport',
            field=models.ForeignKey(blank=True, help_text='Destination airport (for AIR mode).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_destination', to='core.airport'),
        ),
        migrations.AddField(
            model_name='quote',
            name='destination_port',
            field=models.ForeignKey(blank=True, help_text='Destination port (for SEA mode).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_destination_port', to='core.port'),
        ),
        migrations.AddField(
            model_name='quote',
            name='origin_airport',
            field=models.ForeignKey(blank=True, help_text='Origin airport (for AIR mode).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_origin', to='core.airport'),
        ),
        migrations.AddField(
            model_name='quote',
            name='origin_port',
            field=models.ForeignKey(blank=True, help_text='Origin port (for SEA mode).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_origin_port', to='core.port'),
        ),
        migrations.RunPython(backfill_quote_locations, reverse_code=do_nothing),
        migrations.RemoveField(
            model_name='quote',
            name='destination_code',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='origin_code',
        ),
    ]
