# Generated by Django 5.2.5 on 2025-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_constraints_and_totals_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteversion',
            options={'ordering': ['-version_no']},
        ),
        migrations.AddField(
            model_name='quoteversion',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quoteversion',
            name='fx_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quoteversion',
            name='policy_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
