# Generated by Django 5.2.5 on 2025-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_quote_destination_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='service_scope',
            field=models.CharField(blank=True, choices=[('D2D', 'Door to Door'), ('D2A', 'Door to Airport'), ('A2D', 'Airport to Door'), ('A2A', 'Airport to Airport')], help_text='User-selected scope (e.g., D2D, D2A) used by the v1.1 engine.', max_length=3, null=True),
        ),
    ]
