# Generated by Django 5.2.5 on 2025-10-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_quote_bill_to_remove_quote_consignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='destination_code',
            field=models.CharField(blank=True, help_text='Destination location code.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='origin_code',
            field=models.CharField(blank=True, help_text='Origin location code (e.g., Airport IATA, Port UN/LOCODE).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Date the quote expires.', null=True),
        ),
    ]
