# Generated by Django 5.2.5 on 2025-09-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_add_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelines',
            name='tax_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
