# Generated by Django 5.2.5 on 2025-10-23 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fxsnapshot_caf_percent_fxsnapshot_fx_buffer_percent'),
        ('quotes', '0003_quote_destination_code_quote_origin_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField(help_text='Sequential version number (e.g., 1, 2, 3).')),
                ('payload_json', models.JSONField(help_text='The V3 API request payload used for this calculation.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('INCOMPLETE', 'Incomplete (Missing Data)')], default='DRAFT', help_text='Status of the quote at the time this version was created.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="Reason for creating this new version (e.g., 'Customer requested change', 'Initial Draft').", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fx_snapshot', models.ForeignKey(help_text='FX snapshot used for this version.', on_delete=django.db.models.deletion.PROTECT, to='core.fxsnapshot')),
                ('policy', models.ForeignKey(blank=True, help_text='Policy snapshot used for this version (if applicable).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.policy')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotes.quote')),
            ],
            options={
                'ordering': ['quote', '-version_no'],
                'unique_together': {('quote', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='OverrideNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(help_text="Identifier of what was overridden (e.g., 'scope', 'manual_rate:FRT_AIR', 'margin_pct').", max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('reason', models.TextField(help_text='Mandatory reason for the override.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='quotes.quoteversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
