# Generated by Django 5.2.5 on 2025-11-16 00:03

import django.db.models.deletion
from django.db import migrations, models


def assign_locations(apps, schema_editor):
    Quote = apps.get_model('quotes', 'Quote')
    Location = apps.get_model('core', 'Location')
    Airport = apps.get_model('core', 'Airport')
    Port = apps.get_model('core', 'Port')

    def ensure_airport_location(airport):
        if not airport:
            return None
        country = airport.city.country if airport.city else None
        return Location.objects.get_or_create(
            airport=airport,
            defaults={
                "kind": "AIRPORT",
                "name": airport.name or airport.iata_code,
                "code": airport.iata_code,
                "country": country,
                "city": airport.city,
            },
        )[0]

    def ensure_port_location(port):
        if not port:
            return None
        country = port.city.country if port.city else None
        return Location.objects.get_or_create(
            port=port,
            defaults={
                "kind": "PORT",
                "name": port.name or port.unlocode,
                "code": port.unlocode,
                "country": country,
                "city": port.city,
            },
        )[0]

    for quote in Quote.objects.select_related(
        "origin_airport__city__country__currency",
        "destination_airport__city__country__currency",
        "origin_port__city__country__currency",
        "destination_port__city__country__currency",
    ):
        updates = []
        if quote.origin_location_id is None:
            location = None
            if quote.origin_airport_id:
                location = ensure_airport_location(quote.origin_airport)
            elif quote.origin_port_id:
                location = ensure_port_location(quote.origin_port)
            if location:
                quote.origin_location_id = location.id
                updates.append("origin_location")

        if quote.destination_location_id is None:
            location = None
            if quote.destination_airport_id:
                location = ensure_airport_location(quote.destination_airport)
            elif quote.destination_port_id:
                location = ensure_port_location(quote.destination_port)
            if location:
                quote.destination_location_id = location.id
                updates.append("destination_location")

        if updates:
            quote.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_locations'),
        ('quotes', '0003_quote_service_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Generic destination location (airport, port, city, address).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_destination', to='core.location'),
        ),
        migrations.AddField(
            model_name='quote',
            name='origin_location',
            field=models.ForeignKey(blank=True, help_text='Generic origin location (airport, port, city, address).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_origin', to='core.location'),
        ),
        migrations.RunPython(assign_locations, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='quote',
            name='destination_airport',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='destination_port',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='origin_airport',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='origin_port',
        ),
    ]
