# Generated by Django 5.2.5 on 2025-12-08 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_quote_destination_airport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotChargeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.CharField(choices=[('ORIGIN', 'Origin Charges'), ('FREIGHT', 'Freight'), ('DESTINATION', 'Destination Charges')], help_text='Which cost bucket this charge belongs to.', max_length=20)),
                ('description', models.CharField(help_text='Freeform description exactly as received from agent.', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Charge amount. Null when unit_basis is PERCENTAGE.', max_digits=12, null=True)),
                ('currency', models.CharField(help_text='3-letter ISO currency code (e.g., USD, AUD, PGK).', max_length=3)),
                ('unit_basis', models.CharField(choices=[('PER_KG', 'Per KG'), ('PER_SHIPMENT', 'Per Shipment'), ('PER_AWB', 'Per AWB'), ('MINIMUM', 'Minimum Charge'), ('PER_HOUR', 'Per Hour'), ('PER_MAN', 'Per Man'), ('PERCENTAGE', 'Percentage'), ('OTHER', 'Other')], help_text='How this charge is calculated.', max_length=50)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage value (e.g., 20.00 for 20%). Required when unit_basis is PERCENTAGE.', max_digits=6, null=True)),
                ('percent_applies_to', models.CharField(blank=True, choices=[('SPECIFIC_LINE', 'Specific Charge Line'), ('BUCKET_ORIGIN', 'Origin Bucket'), ('BUCKET_FREIGHT', 'Freight Bucket'), ('BUCKET_DESTINATION', 'Destination Bucket'), ('BUCKET_TOTAL', 'Total of All Buckets')], help_text='What the percentage applies to. Required when unit_basis is PERCENTAGE.', max_length=30, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this charge.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(help_text='The quote this spot charge belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='spot_charges', to='quotes.quote')),
                ('target_line', models.ForeignKey(blank=True, help_text='Target line for SPECIFIC_LINE percentage calculation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_charges', to='quotes.spotchargeline')),
            ],
            options={
                'verbose_name': 'Spot Charge Line',
                'verbose_name_plural': 'Spot Charge Lines',
                'ordering': ['bucket', 'created_at'],
            },
        ),
    ]
