# Generated by Django 5.2.5 on 2025-09-23 10:15

from django.db import migrations, models, connection
import django.db.models.deletion


def add_currency_fk_constraints(apps, schema_editor):
    """Add foreign key constraints for currency references."""
    # Add FK constraints as NOT VALID initially to avoid blocking writes
    schema_editor.execute("""
        ALTER TABLE quotes 
        ADD CONSTRAINT fk_quotes_currency 
        FOREIGN KEY (currency) REFERENCES currencies(code) NOT VALID;
    """)
    
    schema_editor.execute("""
        ALTER TABLE quote_lines 
        ADD CONSTRAINT fk_quote_lines_currency 
        FOREIGN KEY (currency) REFERENCES currencies(code) NOT VALID;
    """)
    
    schema_editor.execute("""
        ALTER TABLE ratecard_fees 
        ADD CONSTRAINT fk_ratecard_fees_currency 
        FOREIGN KEY (currency) REFERENCES currencies(code) NOT VALID;
    """)
    
    schema_editor.execute("""
        ALTER TABLE service_items 
        ADD CONSTRAINT fk_service_items_currency 
        FOREIGN KEY (currency) REFERENCES currencies(code) NOT VALID;
    """)


def add_unit_fk_constraints(apps, schema_editor):
    """Add foreign key constraints for unit references."""
    schema_editor.execute("""
        ALTER TABLE quote_lines 
        ADD CONSTRAINT fk_quote_lines_unit 
        FOREIGN KEY (unit) REFERENCES units(code) NOT VALID;
    """)


def validate_fk_constraints(apps, schema_editor):
    """Validate foreign key constraints after ensuring data consistency."""
    # In practice, this would be run after verifying that all existing data
    # conforms to the new constraints
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_rateengine_v2_db_fixes'),
    ]

    operations = [
        # Add FK constraints as NOT VALID
        migrations.RunPython(add_currency_fk_constraints, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_unit_fk_constraints, reverse_code=migrations.RunPython.noop),
        
        # Note: VALIDATE CONSTRAINT would be done in a separate migration
        # after verifying data consistency
    ]