# Generated by Django 5.2.5 on 2025-12-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_add_spot_charge_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotchargeline',
            name='unit_basis',
            field=models.CharField(choices=[('PER_KG', 'Per KG'), ('PER_SHIPMENT', 'Per Shipment'), ('PER_AWB', 'Per AWB'), ('MINIMUM', 'Minimum Charge'), ('PER_HOUR', 'Per Hour'), ('PERCENTAGE', 'Percentage'), ('OTHER', 'Other')], help_text='How this charge is calculated.', max_length=50),
        ),
    ]
