# Generated by Django 5.2.5 on 2025-09-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_ratecard_created_at_indexes'),
        ('quotes', '0005_split_mode_into_shipment_type_scope'),
    ]

    operations = [
    ]
