# Generated by Django 5.2.5 on 2025-09-23 10:20

from django.db import migrations, models, connection
import django.db.models.deletion


def add_audience_fk_constraints(apps, schema_editor):
    """Add foreign key constraints for audience references."""
    schema_editor.execute("""
        ALTER TABLE organizations 
        ADD CONSTRAINT fk_orgs_audience 
        FOREIGN KEY (audience_id) REFERENCES audiences(id) NOT VALID;
    """)
    
    schema_editor.execute("""
        ALTER TABLE pricing_policy 
        ADD CONSTRAINT fk_policy_audience 
        FOREIGN KEY (audience_id) REFERENCES audiences(id) NOT VALID;
    """)


def validate_audience_fk_constraints(apps, schema_editor):
    """Validate audience foreign key constraints after ensuring data consistency."""
    # In practice, this would be run after verifying that all existing data
    # conforms to the new constraints
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_add_currency_unit_fks'),
    ]

    operations = [
        # Add audience FK constraints as NOT VALID
        migrations.RunPython(add_audience_fk_constraints, reverse_code=migrations.RunPython.noop),
        
        # Note: VALIDATE CONSTRAINT would be done in a separate migration
        # after verifying data consistency
    ]