# Generated by Django 5.2.5 on 2025-09-23 10:25

from django.db import migrations, models, connection
import django.db.models.deletion


def add_quotes_safety_flags_fields(apps, schema_editor):
    """Add safety flags to quotes table."""
    schema_editor.execute("""
        ALTER TABLE quotes 
        ADD COLUMN IF NOT EXISTS is_incomplete BOOLEAN NOT NULL DEFAULT FALSE;
    """)
    
    schema_editor.execute("""
        ALTER TABLE quotes 
        ADD COLUMN IF NOT EXISTS incomplete_reason TEXT;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_add_audience_fks'),
    ]

    operations = [
        # Add safety flags to quotes table
        migrations.RunPython(add_quotes_safety_flags_fields, reverse_code=migrations.RunPython.noop),
    ]