# Generated by Django 5.2.5 on 2025-12-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_remove_per_man_unit_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotchargeline',
            name='min_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum charge amount for PER_KG rates. If rate × weight is less than this, the minimum applies.', max_digits=12, null=True),
        ),
    ]
