# Generated by Django 5.2.5 on 2025-12-14 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_add_min_charge_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when quote was finalized.', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='User who finalized the quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when quote was sent to customer.', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent the quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('INCOMPLETE', 'Incomplete (Missing Data)')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('INCOMPLETE', 'Incomplete (Missing Data)')], default='DRAFT', help_text='Status of the quote at the time this version was created.', max_length=20),
        ),
    ]
