# Generated by Django 5.2.5 on 2025-09-23 10:30

from django.db import migrations, models, connection
import django.db.models.deletion


def add_jsonb_indexes(apps, schema_editor):
    """Add GIN indexes for JSONB columns."""
    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS quotes_req_snapshot_gin 
        ON quotes USING GIN (request_snapshot jsonb_path_ops);
    """)
    
    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS ratecard_fees_applies_if_gin 
        ON ratecard_fees USING GIN (applies_if jsonb_path_ops);
    """)
    
    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS service_items_conditions_gin 
        ON service_items USING GIN (conditions_json jsonb_path_ops);
    """)


def add_jsonb_checks(apps, schema_editor):
    """Add checks for required keys in JSONB columns."""
    schema_editor.execute("""
        ALTER TABLE ratecard_fees 
        ADD CONSTRAINT chk_applies_if_has_kind 
        CHECK (applies_if ? 'kind') NOT VALID;
    """)
    
    schema_editor.execute("""
        ALTER TABLE service_items 
        ADD CONSTRAINT chk_conditions_has_kind 
        CHECK (conditions_json ? 'kind') NOT VALID;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_add_quotes_safety_flags'),
    ]

    operations = [
        # Add JSONB indexes
        migrations.RunPython(add_jsonb_indexes, reverse_code=migrations.RunPython.noop),
        
        # Add JSONB checks
        migrations.RunPython(add_jsonb_checks, reverse_code=migrations.RunPython.noop),
    ]