# Generated by Django 5.2.5 on 2025-12-19 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quote_lifecycle_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPricingEnvelopeDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('shipment_context_json', models.JSONField(help_text='Immutable shipment context. Verified by hash on read.')),
                ('shipment_context_hash', models.CharField(help_text='SHA256 hash of shipment_context_json for integrity verification.', max_length=64)),
                ('conditions_json', models.JSONField(default=dict, help_text='SPE conditions (uncertainty tracking).')),
                ('spot_trigger_reason_code', models.CharField(help_text='Machine-readable SPOT trigger reason code.', max_length=50)),
                ('spot_trigger_reason_text', models.TextField(help_text='Human-readable SPOT trigger reason for UI display.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='SPE expires after this timestamp. Non-reusable after expiry.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spot_envelopes', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, help_text='Quote this SPE is associated with (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_envelopes', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Spot Pricing Envelope',
                'verbose_name_plural': 'Spot Pricing Envelopes',
                'db_table': 'spot_pricing_envelopes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SPEManagerApprovalDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField()),
                ('decision_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True, help_text='Optional comment from manager.', null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('envelope', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_approval', to='quotes.spotpricingenvelopedb')),
            ],
            options={
                'verbose_name': 'SPE Manager Approval',
                'verbose_name_plural': 'SPE Manager Approvals',
                'db_table': 'spe_manager_approvals',
            },
        ),
        migrations.CreateModel(
            name='SPEChargeLineDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Canonical internal charge code (e.g., AIRFREIGHT_SPOT)', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('unit', models.CharField(choices=[('per_kg', 'Per KG'), ('flat', 'Flat'), ('per_awb', 'Per AWB'), ('per_shipment', 'Per Shipment'), ('percentage', 'Percentage')], max_length=20)),
                ('bucket', models.CharField(choices=[('airfreight', 'Airfreight'), ('origin_charges', 'Origin Charges'), ('destination_charges', 'Destination Charges')], max_length=30)),
                ('is_primary_cost', models.BooleanField(default=False, help_text='True if this is the primary airfreight cost line.')),
                ('conditional', models.BooleanField(default=False)),
                ('source_reference', models.CharField(help_text='Email ID, filename, or manual note - REQUIRED', max_length=500)),
                ('entered_at', models.DateTimeField()),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_lines', to='quotes.spotpricingenvelopedb')),
            ],
            options={
                'verbose_name': 'SPE Charge Line',
                'verbose_name_plural': 'SPE Charge Lines',
                'db_table': 'spe_charge_lines',
                'ordering': ['bucket', 'entered_at'],
            },
        ),
        migrations.CreateModel(
            name='SPEAcknowledgementDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField()),
                ('statement', models.TextField(default='I acknowledge this is a conditional SPOT quote and not guaranteed', help_text='The acknowledgement statement agreed to.')),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('envelope', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='quotes.spotpricingenvelopedb')),
            ],
            options={
                'verbose_name': 'SPE Acknowledgement',
                'verbose_name_plural': 'SPE Acknowledgements',
                'db_table': 'spe_acknowledgements',
            },
        ),
    ]
