# Generated by Django 5.2.5 on 2025-09-23 10:35

from django.db import migrations, models, connection
import django.db.models.deletion


def add_exclusion_constraints(apps, schema_editor):
    """Add exclusion constraints for overlapping ranges."""
    # Ratecards: no overlapping date ranges per (provider_id, audience_id, name)
    schema_editor.execute("""
        ALTER TABLE ratecards 
        ADD CONSTRAINT excl_ratecards_overlap 
        EXCLUDE USING gist (
            provider_id WITH =, 
            audience_id WITH =, 
            name WITH =, 
            daterange(effective_date, COALESCE(expiry_date, '9999-12-31')) WITH &&
        );
    """)
    
    # Cartage ladders: no overlapping numrange(min_weight_kg, max_weight_kg) per ratecard_id
    schema_editor.execute("""
        ALTER TABLE cartage_ladders 
        ADD CONSTRAINT excl_cartage_ladders_overlap 
        EXCLUDE USING gist (
            ratecard_id WITH =, 
            numrange(min_weight_kg, max_weight_kg, '[]') WITH &&
        );
    """)
    
    # Storage tiers: no overlapping int4range(week_from, week_to) per (ratecard_id, group_code)
    schema_editor.execute("""
        ALTER TABLE storage_tiers 
        ADD CONSTRAINT excl_storage_tiers_overlap 
        EXCLUDE USING gist (
            ratecard_id WITH =, 
            group_code WITH =, 
            int4range(week_from, week_to, '[]') WITH &&
        );
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_add_jsonb_indexes_checks'),
    ]

    operations = [
        # Add exclusion constraints
        migrations.RunPython(add_exclusion_constraints, reverse_code=migrations.RunPython.noop),
    ]