# Generated by Django 5.2.5 on 2025-09-23 10:40

from django.db import migrations, models, connection
import django.db.models.deletion


def add_uniqueness_constraints(apps, schema_editor):
    """Add missing uniqueness constraints."""
    schema_editor.execute("""
        ALTER TABLE route_legs 
        ADD CONSTRAINT route_legs_route_id_sequence_uniq 
        UNIQUE (route_id, sequence);
    """)


def add_data_integrity_checks(apps, schema_editor):
    """Add data integrity checks."""
    schema_editor.execute("""
        ALTER TABLE stations 
        ADD CONSTRAINT chk_stations_iata_len 
        CHECK (length(iata) = 3 AND iata = upper(iata));
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_add_exclusion_constraints'),
    ]

    operations = [
        # Add uniqueness constraints
        migrations.RunPython(add_uniqueness_constraints, reverse_code=migrations.RunPython.noop),
        
        # Add data integrity checks
        migrations.RunPython(add_data_integrity_checks, reverse_code=migrations.RunPython.noop),
    ]