# Generated by Django 5.2.5 on 2025-12-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_spot_pricing_envelope"),
    ]

    operations = [
        migrations.AddField(
            model_name="spechargelinedb",
            name="exclude_from_totals",
            field=models.BooleanField(
                default=False,
                help_text="True for invoice-value taxes that cannot be computed",
            ),
        ),
        migrations.AddField(
            model_name="spechargelinedb",
            name="min_charge",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum charge for 'min OR per kg' logic",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="spechargelinedb",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Narrative conditions from agent (e.g., 'if applicable')",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="spechargelinedb",
            name="percentage_basis",
            field=models.CharField(
                blank=True,
                help_text="What the percentage applies to (e.g., 'commercial_invoice')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spechargelinedb",
            name="unit",
            field=models.CharField(
                choices=[
                    ("per_kg", "Per KG"),
                    ("flat", "Flat"),
                    ("per_awb", "Per AWB"),
                    ("per_shipment", "Per Shipment"),
                    ("percentage", "Percentage"),
                    ("per_trip", "Per Trip"),
                    ("per_set", "Per Set"),
                    ("per_man", "Per Man"),
                ],
                max_length=20,
            ),
        ),
    ]
