# Generated by Django 5.2.5 on 2025-12-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_add_spe_charge_extended_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotChargeLine',
        ),
    ]
