# Generated by Django 5.2.5 on 2025-09-23 10:45

from django.db import migrations, models, connection
import django.db.models.deletion


def add_quote_lines_side_field(apps, schema_editor):
    """Add side field to quote_lines table."""
    schema_editor.execute("""
        ALTER TABLE quote_lines 
        ADD COLUMN IF NOT EXISTS side TEXT CHECK (side IN ('BUY', 'SELL')) DEFAULT 'SELL';
    """)


def backfill_quote_lines_side(apps, schema_editor):
    """Backfill side field from is_buy/is_sell fields."""
    schema_editor.execute("""
        UPDATE quote_lines 
        SET side = CASE 
            WHEN is_buy = TRUE THEN 'BUY'
            WHEN is_sell = TRUE THEN 'SELL'
            ELSE 'SELL'
        END;
    """)


def update_quote_lines_precision(apps, schema_editor):
    """Update precision for quote_lines money fields."""
    # Note: In practice, changing precision might require more careful handling
    # depending on the existing data and database system
    # This is a simplified approach that might need adjustment based on the actual DB system
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_add_uniqueness_integrity'),
    ]

    operations = [
        # Add side field to quote_lines
        migrations.RunPython(add_quote_lines_side_field, reverse_code=migrations.RunPython.noop),
        
        # Backfill side field
        migrations.RunPython(backfill_quote_lines_side, reverse_code=migrations.RunPython.noop),
        
        # Update precision for quote_lines money fields
        migrations.RunPython(update_quote_lines_precision, reverse_code=migrations.RunPython.noop),
    ]