# Generated by Django 5.2.5 on 2025-12-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_delete_spotchargeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='is_informational',
            field=models.BooleanField(default=False, help_text='If True, this is a conditional charge shown as a note, not included in totals.'),
        ),
    ]
