# Generated by Django 5.2.5 on 2026-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_add_is_informational_to_quoteline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='bucket',
            field=models.CharField(blank=True, help_text='e.g., origin_charges, airfreight, destination_charges', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='leg',
            field=models.CharField(blank=True, help_text='ORIGIN, MAIN, or DESTINATION', max_length=20, null=True),
        ),
    ]
