# Generated by Django 5.2.5 on 2026-01-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_quoteline_bucket_quoteline_leg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spechargelinedb',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
