# Generated by Django 5.2.5 on 2026-01-10 00:00
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0014_add_amount_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if soft-deleted/archived (e.g. > 3 months old).",
            ),
        ),
    ]
