# Generated by Django 5.2.5 on 2026-01-19 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_add_quote_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('FINALIZED', 'Finalized'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('REVISED', 'Revised')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional additional context for the event.', null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quotes.quote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['quote', 'event_type'], name='quotes_quot_quote_i_a030ea_idx'), models.Index(fields=['timestamp', 'event_type'], name='quotes_quot_timesta_b1c5f6_idx')],
            },
        ),
    ]
