# Generated by Django 5.2.5 on 2026-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_add_quote_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotetotal',
            name='engine_version',
            field=models.CharField(default='V4', help_text='Pricing engine version (denormalized for reporting queries).', max_length=10),
        ),
        migrations.AddField(
            model_name='quoteversion',
            name='engine_version',
            field=models.CharField(choices=[('V3', 'V3 Legacy'), ('V4', 'V4 ProductCode')], default='V4', help_text='Pricing engine version used for this calculation.', max_length=10),
        ),
    ]
