# Generated by Django 5.2.5 on 2026-01-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_add_engine_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated GST amount for this line', max_digits=12),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='gst_category',
            field=models.CharField(blank=True, choices=[('service_in_PNG', 'Service in PNG (10% GST)'), ('export_service', 'Export Service (0% Zero-Rated)'), ('offshore_service', 'Offshore Service (0% Exempt)'), ('imported_goods', 'Imported Goods (0% - Customs)')], help_text='PNG GST classification for this line item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='gst_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='GST rate applied (0.10 = 10%)', max_digits=5),
        ),
    ]
