# Generated by Django 5.2.5 on 2026-02-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_spe_charge_rule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='conditional',
            field=models.BooleanField(default=False),
        ),
    ]
