# Generated by Django 5.2.5 on 2026-03-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_quoteline_conditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='commodity_code',
            field=models.CharField(choices=[('GCR', 'General Cargo'), ('SCR', 'Special Cargo'), ('DG', 'Dangerous Goods'), ('AVI', 'Live Animals'), ('PER', 'Perishables'), ('HVC', 'High Value Cargo'), ('HUM', 'Human Remains'), ('OOG', 'Oversized/Heavy Cargo'), ('VUL', 'Vulnerable Cargo'), ('TTS', 'Time/Temperature Sensitive'), ('OTHER', 'Other Special Cargo')], db_index=True, default='GCR', help_text='Commodity classification used for conditional pricing and approvals.', max_length=10),
        ),
    ]
