# Generated by Django 5.2.5 on 2026-03-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_quote_commodity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approval_reason',
            field=models.TextField(blank=True, help_text='Human-readable reason explaining why approval is required.'),
        ),
        migrations.AddField(
            model_name='quote',
            name='approval_required',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the quote needs manager approval before commercial release.'),
        ),
    ]
