# Generated by Django 5.2.5 on 2026-03-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_quote_approval_reason_quote_approval_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='approval_reason',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='approval_required',
        ),
        migrations.AlterField(
            model_name='quote',
            name='commodity_code',
            field=models.CharField(choices=[('GCR', 'General Cargo'), ('SCR', 'Special Cargo'), ('DG', 'Dangerous Goods'), ('AVI', 'Live Animals'), ('PER', 'Perishables'), ('HVC', 'High Value Cargo'), ('HUM', 'Human Remains'), ('OOG', 'Oversized/Heavy Cargo'), ('VUL', 'Vulnerable Cargo'), ('TTS', 'Time/Temperature Sensitive'), ('OTHER', 'Other Special Cargo')], db_index=True, default='GCR', help_text='Commodity classification used for conditional pricing decisions.', max_length=10),
        ),
    ]
