# Generated by Django 5.2.5 on 2026-03-19 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_remove_quote_approval_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPESourceBatchDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('AIRLINE', 'Airline'), ('AGENT', 'Agent'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='AGENT', max_length=20)),
                ('source_type', models.CharField(choices=[('TEXT', 'Text'), ('PDF', 'PDF'), ('EMAIL', 'Email'), ('MANUAL', 'Manual')], default='TEXT', max_length=20)),
                ('target_bucket', models.CharField(choices=[('airfreight', 'Airfreight'), ('origin_charges', 'Origin Charges'), ('destination_charges', 'Destination Charges'), ('mixed', 'Mixed')], default='mixed', max_length=30)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('source_reference', models.CharField(blank=True, default='', max_length=500)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('analysis_summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_batches', to='quotes.spotpricingenvelopedb')),
            ],
            options={
                'verbose_name': 'SPE Source Batch',
                'verbose_name_plural': 'SPE Source Batches',
                'db_table': 'spe_source_batches',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_lines', to='quotes.spesourcebatchdb'),
        ),
    ]
