# Generated by Django 5.2.5 on 2026-04-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0026_add_canonical_audit_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spemanagerapprovaldb',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional historical comment from manager.', null=True),
        ),
    ]
