# Generated by Django 5.2.5 on 2026-04-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0027_alter_spemanagerapprovaldb_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotpricingenvelopedb',
            name='resolved_missing_components',
            field=models.JSONField(
                help_text="The missing components that were resolved when this SPE was created.",
                null=True,
                blank=True,
            ),
        ),
    ]
