# Generated by Django 5.2.5 on 2026-04-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0028_add_resolved_missing_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotpricingenvelopedb',
            name='resolved_missing_components',
        ),
    ]
