# Generated by Django 5.2.5 on 2026-04-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0029_remove_spotpricingenvelopedb_resolved_missing_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='description',
            field=models.CharField(blank=True, help_text='Custom display name for this line (e.g. from AI extraction). Falls back to component description if null.', max_length=500, null=True),
        ),
    ]
