# Generated by Django 5.2.5 on 2026-04-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0023_chargealias'),
        ('quotes', '0030_quoteline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='spechargelinedb',
            name='matched_alias',
            field=models.ForeignKey(blank=True, help_text='Matched ChargeAlias when deterministic normalization resolves to a specific alias.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spe_charge_lines', to='pricing_v4.chargealias'),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='normalization_method',
            field=models.CharField(blank=True, choices=[('EXACT_ALIAS', 'Exact Alias'), ('PATTERN_ALIAS', 'Pattern Alias'), ('NONE', 'None')], db_index=True, help_text='Resolution method used for deterministic charge normalization.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='normalization_status',
            field=models.CharField(blank=True, choices=[('MATCHED', 'Matched'), ('AMBIGUOUS', 'Ambiguous'), ('UNMAPPED', 'Unmapped')], db_index=True, help_text='Deterministic charge-normalization outcome for this line.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='normalized_label',
            field=models.CharField(blank=True, default='', help_text='Deterministically normalized label derived from source_label.', max_length=255),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='resolved_product_code',
            field=models.ForeignKey(blank=True, help_text='Resolved canonical ProductCode from deterministic normalization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spe_resolved_charge_lines', to='pricing_v4.productcode'),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='source_label',
            field=models.CharField(blank=True, default='', help_text='Original raw charge label from the source content, if captured.', max_length=255),
        ),
    ]
