# Generated by Django 5.2.5 on 2026-04-30 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('quotes', '0035_spechargelinedb_source_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='CRM opportunity this quote supports, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='crm.opportunity'),
        ),
    ]
