# Generated by Django 5.2.5 on 2026-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0036_quote_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='spechargelinedb',
            name='agent_name_snapshot',
            field=models.CharField(blank=True, help_text='Snapshot of the agent/supplier/airline name.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='calculation_basis',
            field=models.CharField(blank=True, help_text='Inferred calculation basis for the charge (e.g. per_kg, flat, percentage).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='destination_code_snapshot',
            field=models.CharField(blank=True, help_text='Snapshot of the destination airport/port code.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='normalization_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Numeric confidence score from resolver if available.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='normalization_review_reason',
            field=models.TextField(blank=True, help_text='Detailed reason for manual review triggers (e.g. unmapped or ambiguous alias).', null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='origin_code_snapshot',
            field=models.CharField(blank=True, help_text='Snapshot of the origin airport/port code.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='route_context',
            field=models.CharField(blank=True, help_text='Snapshot of the route string (e.g. SIN-POM).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='service_scope_snapshot',
            field=models.CharField(blank=True, help_text='Snapshot of the shipment service scope (e.g. D2D, P2P).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='source_section_label',
            field=models.CharField(blank=True, help_text='Verbatim section heading from the raw source document.', max_length=255, null=True),
        ),
    ]
