# Generated by Django 5.2.5 on 2026-06-09 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0030_normalize_import_cogs_origin_phase_3b'),
        ('quotes', '0036_quote_opportunity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotChargeMappingMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_label', models.CharField(db_index=True, help_text='Deterministically normalized charge label.', max_length=255)),
                ('bucket', models.CharField(blank=True, default='', help_text='Charge bucket scope (empty = any bucket).', max_length=30)),
                ('shipment_type', models.CharField(blank=True, db_index=True, default='', help_text='Shipment type scope (empty = any type).', max_length=10)),
                ('status', models.CharField(choices=[('LEARNED', 'Learned'), ('LOCKED', 'Locked'), ('RETIRED', 'Retired')], db_index=True, default='LEARNED', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Latest computed confidence score for this mapping.')),
                ('event_count', models.PositiveIntegerField(default=0, help_text='Number of learning events supporting this mapping.')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent learning event for this mapping.', null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_note', models.TextField(blank=True, default='', help_text='Reason for locking this mapping.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, help_text='Manager/Admin who locked this mapping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_code', models.ForeignKey(help_text='Canonical ProductCode this label resolves to.', on_delete=django.db.models.deletion.PROTECT, related_name='spot_mapping_memories', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Spot Charge Mapping Memory',
                'verbose_name_plural': 'Spot Charge Mapping Memories',
                'db_table': 'spot_charge_mapping_memory',
                'ordering': ['-confidence_score', '-event_count'],
                'indexes': [models.Index(fields=['normalized_label', 'bucket', 'shipment_type', 'status'], name='scmm_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_label', 'bucket', 'shipment_type', 'product_code'), name='scmm_unique_mapping')],
            },
        ),
        migrations.CreateModel(
            name='SpotResolutionLearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_label', models.CharField(help_text='Original raw charge label from the source content.', max_length=255)),
                ('normalized_label', models.CharField(db_index=True, help_text='Deterministically normalized label for matching.', max_length=255)),
                ('bucket', models.CharField(help_text='Charge bucket: airfreight, origin_charges, destination_charges.', max_length=30)),
                ('normalization_status_before', models.CharField(help_text='Normalization status before user intervention (MATCHED, AMBIGUOUS, UNMAPPED).', max_length=20)),
                ('normalization_method_before', models.CharField(blank=True, default='', help_text='Normalization method before user intervention (EXACT_ALIAS, PATTERN_ALIAS, NONE).', max_length=20)),
                ('resolution_type', models.CharField(choices=[('MANUAL_PRODUCT_CODE', 'Manual ProductCode Selection'), ('CONFIRM_PATTERN_MATCH', 'Confirm Pattern Match'), ('OVERRIDE_SUGGESTION', 'Override System Suggestion'), ('CONDITIONAL_KEEP', 'Conditional Charge Kept'), ('CONDITIONAL_REMOVE', 'Conditional Charge Removed'), ('AUTO_RESOLVED', 'System Auto-Resolved')], db_index=True, max_length=30)),
                ('user_agreed_with_suggestion', models.BooleanField(default=False, help_text='True when user confirmed the system suggestion without changing it.')),
                ('origin_code', models.CharField(blank=True, db_index=True, default='', max_length=5)),
                ('destination_code', models.CharField(blank=True, db_index=True, default='', max_length=5)),
                ('mode', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('shipment_type', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('service_scope', models.CharField(blank=True, default='', max_length=10)),
                ('source_kind', models.CharField(blank=True, db_index=True, default='', help_text='Source batch kind: AIRLINE, AGENT, MANUAL, OTHER.', max_length=20)),
                ('source_label_supplier', models.CharField(blank=True, default='', help_text='Source batch label (agent/airline name).', max_length=255)),
                ('resolved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confidence_at_resolution', models.FloatField(blank=True, help_text='Confidence score at the time of resolution (null for pre-learning / cold-start).', null=True)),
                ('charge_line', models.ForeignKey(help_text='The charge line that was resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='quotes.spechargelinedb')),
                ('envelope', models.ForeignKey(help_text='The SPE this resolution belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='quotes.spotpricingenvelopedb')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_product_code', models.ForeignKey(blank=True, help_text='ProductCode the user selected (null for conditional REMOVE).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing_v4.productcode')),
                ('system_suggested_product_code', models.ForeignKey(blank=True, help_text='ProductCode the system suggested (from deterministic normalization), if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Spot Resolution Learning Event',
                'verbose_name_plural': 'Spot Resolution Learning Events',
                'db_table': 'spot_resolution_learning_events',
                'ordering': ['-resolved_at'],
                'indexes': [models.Index(fields=['normalized_label', 'bucket', 'shipment_type'], name='srl_label_bucket_type_idx'), models.Index(fields=['normalized_label', 'resolved_product_code'], name='srl_label_product_idx')],
            },
        ),
    ]
