# Generated by Django 5.2.5 on 2026-05-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0036_quote_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='base_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='caf_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='provider_name',
            field=models.CharField(blank=True, help_text='Actual name of the agent or carrier providing the rate.', max_length=255, null=True),
        ),
    ]
