# Generated by Django 5.2.5 on 2026-05-28 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_location_code'),
        ('quotes', '0037_seed_parent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='owning_location',
            field=models.ForeignKey(blank=True, help_text='The location/branch that owns/manages this quote (e.g. POM, LAE).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_owned', to='core.location'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='mode',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land'), ('CUSTOMS', 'Customs')], default='AIR', max_length=10),
        ),
    ]
