# Generated by Django 5.2.5 on 2026-06-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0031_canonicalchargetype_and_more'),
        ('quotes', '0038_spot_resolution_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='spechargelinedb',
            name='canonical_charge_type',
            field=models.ForeignKey(blank=True, help_text='CanonicalChargeType classification associated with this charge line.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spe_charge_lines', to='pricing_v4.canonicalchargetype'),
        ),
    ]
