# Generated by Django 5.2.5 on 2026-06-11 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0032_seed_canonical_charge_types'),
        ('quotes', '0039_spechargelinedb_canonical_charge_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedChargeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Airfreight Export D2D Template', max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System-seeded templates protected from deletion')),
                ('mode', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], db_index=True, max_length=20)),
                ('transport_mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road'), ('ANY', 'Any')], db_index=True, default='ANY', max_length=20)),
                ('service_scope', models.CharField(choices=[('A2A', 'Airport-to-Airport'), ('D2D', 'Door-to-Door'), ('D2A', 'Door-to-Airport'), ('A2D', 'Airport-to-Door'), ('P2P', 'Port-to-Port'), ('ANY', 'Any')], db_index=True, default='ANY', max_length=20)),
                ('origin_country', models.CharField(blank=True, help_text='ISO 2-letter code', max_length=2, null=True)),
                ('origin_code', models.CharField(blank=True, help_text='Port/Airport Code (e.g., SIN)', max_length=10, null=True)),
                ('destination_country', models.CharField(blank=True, help_text='ISO 2-letter code', max_length=2, null=True)),
                ('destination_code', models.CharField(blank=True, help_text='Port/Airport Code (e.g., POM)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expected Charge Template',
                'verbose_name_plural': 'Expected Charge Templates',
                'db_table': 'expected_charge_templates',
            },
        ),
        migrations.CreateModel(
            name='ExpectedTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_level', models.CharField(choices=[('REQUIRED', 'Expected / Must be accounted for'), ('OPTIONAL', 'Optional (Can be billed, ignore if absent)'), ('CONDITIONAL', 'Conditional (Storage, Demurrage, etc.)'), ('EXCLUDED', 'Excluded (Must not be billed under this scope)')], default='REQUIRED', max_length=20)),
                ('expected_basis', models.CharField(choices=[('per_kg', 'Per Kilogram'), ('flat', 'Flat Charge'), ('percentage', 'Percentage Basis'), ('any', 'Any')], default='any', help_text='Expected calculation unit basis if deterministic', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Explanation/Context rules', null=True)),
                ('sort_order', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('canonical_charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing_v4.canonicalchargetype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.expectedchargetemplate')),
            ],
            options={
                'db_table': 'expected_template_lines',
                'ordering': ['sort_order'],
                'unique_together': {('template', 'canonical_charge_type')},
            },
        ),
    ]
