# Generated by Django 5.2.5 on 2026-06-11 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0040_expectedchargetemplate_expectedtemplateline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotTemplateValidationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_code', models.CharField(max_length=50)),
                ('canonical_type', models.CharField(blank=True, max_length=50, null=True)),
                ('template_line_id', models.IntegerField(blank=True, null=True)),
                ('charge_line_id', models.UUIDField(blank=True, null=True)),
                ('finding_fingerprint', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_validation_reviews', to='quotes.spotpricingenvelopedb')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spot_template_validation_reviews',
                'unique_together': {('envelope', 'finding_fingerprint')},
            },
        ),
    ]
