# Generated by Django 5.2.5 on 2026-06-12 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0041_spottemplatevalidationreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotTemplateValidationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='finding_reviewed', max_length=50)),
                ('finding_code', models.CharField(max_length=100)),
                ('canonical_type', models.CharField(blank=True, max_length=100, null=True)),
                ('template_line_id', models.IntegerField(blank=True, null=True)),
                ('charge_line_id', models.UUIDField(blank=True, null=True)),
                ('finding_fingerprint', models.CharField(max_length=255)),
                ('validation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_validation_events', to='quotes.spotpricingenvelopedb')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spot_template_validation_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
