# Generated by Django 5.2.5 on 2026-06-12 05:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0042_spottemplatevalidationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotTemplateValidationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=50)),
                ('validation_status', models.CharField(max_length=50)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('template_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('findings_hash', models.CharField(db_index=True, max_length=64)),
                ('findings_json', models.JSONField(default=list)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('finding_codes', models.JSONField(default=list)),
                ('canonical_types', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_snapshots', to='quotes.spotpricingenvelopedb')),
            ],
            options={
                'db_table': 'spot_template_validation_snapshots',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('envelope', 'validation_status', 'template_hash', 'findings_hash'), name='unique_spot_envelope_validation_snapshot')],
            },
        ),
    ]
