# Generated by Django 5.2.5 on 2026-06-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0043_spottemplatevalidationsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottemplatevalidationevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='spottemplatevalidationevent',
            name='event_type',
            field=models.CharField(db_index=True, default='finding_reviewed', max_length=50),
        ),
        migrations.AlterField(
            model_name='spottemplatevalidationsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='spottemplatevalidationsnapshot',
            name='trigger',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='spottemplatevalidationsnapshot',
            name='validation_status',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
