# Generated by Django 5.2.5 on 2026-06-17 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_branch_department_and_more'),
        ('quotes', '0044_alter_spottemplatevalidationevent_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Future RBAC branch scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='parties.branch'),
        ),
        migrations.AddField(
            model_name='quote',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Future RBAC department scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='parties.department'),
        ),
        migrations.AddField(
            model_name='quote',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Future RBAC record owner. Nullable until ownership rules are enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spotpricingenvelopedb',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Future RBAC branch scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_envelopes', to='parties.branch'),
        ),
        migrations.AddField(
            model_name='spotpricingenvelopedb',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Future RBAC department scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_envelopes', to='parties.department'),
        ),
        migrations.AddField(
            model_name='spotpricingenvelopedb',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Future RBAC organization scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_envelopes', to='parties.organization'),
        ),
        migrations.AddField(
            model_name='spotpricingenvelopedb',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Future RBAC record owner. Nullable until ownership rules are enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_spot_envelopes', to=settings.AUTH_USER_MODEL),
        ),
    ]
