# Generated by Django 5.2.14 on 2026-07-03 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0045_add_rbac_scope_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftQuoteDecisionDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(db_index=True)),
                ('decision_id', models.CharField(max_length=255)),
                ('decision_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(db_index=True, max_length=255)),
                ('details_json', models.JSONField(default=dict)),
                ('client_audit_metadata_json', models.JSONField(default=dict)),
                ('server_created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_quote_decisions', to='quotes.spotpricingenvelopedb')),
                ('server_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'draft_quote_decisions',
                'ordering': ['server_created_at'],
                'indexes': [models.Index(fields=['envelope', 'target_id'], name='idx_spe_dec_envelope_target')],
                'constraints': [models.UniqueConstraint(fields=('envelope', 'idempotency_key', 'decision_id'), name='unique_envelope_idempotency_decision')],
            },
        ),
    ]
