# Generated by Django 5.2.14 on 2026-07-23 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


ROUTE_POLICIES = {
    'IMP_POM': 'Phase 16E-A dark-mode foundation: automation disabled until explicit route-rate gate approval.',
    'IMP_LAE': 'Phase 16E-A dark-mode foundation: automation disabled until POM to LAE on-forwarding rate gate is approved.',
    'IMP_HGU': 'Phase 16E-A dark-mode foundation: automation disabled until POM to HGU on-forwarding rate gate is approved.',
    'EXP_POM': 'Phase 16E-A dark-mode foundation: automation disabled until explicit export route-rate gate approval.',
    'EXP_LAE': 'Phase 16E-A dark-mode foundation: automation disabled until LAE to POM pre-carriage rate gate is approved.',
    'EXP_HGU': 'Phase 16E-A dark-mode foundation: automation disabled because HGU to POM readiness is not approved.',
}


def seed_disabled_route_policies(apps, schema_editor):
    RouteAutomationPolicyDB = apps.get_model('quotes', 'RouteAutomationPolicyDB')
    for pattern, reason in ROUTE_POLICIES.items():
        RouteAutomationPolicyDB.objects.update_or_create(
            route_pattern=pattern,
            defaults={
                'enabled': False,
                'disabled_reason': reason,
                'required_rate_gate_json': {'phase': '16E-A', 'approved': False},
            },
        )


def unseed_disabled_route_policies(apps, schema_editor):
    RouteAutomationPolicyDB = apps.get_model('quotes', 'RouteAutomationPolicyDB')
    RouteAutomationPolicyDB.objects.filter(route_pattern__in=list(ROUTE_POLICIES)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0046_draftquotedecisiondb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='charge_context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='product_code_resolution_audit_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='charge_context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='product_code_resolution_audit_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RouteAutomationPolicyDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_pattern', models.CharField(choices=[('IMP_POM', 'IMP_POM'), ('IMP_LAE', 'IMP_LAE'), ('IMP_HGU', 'IMP_HGU'), ('EXP_POM', 'EXP_POM'), ('EXP_LAE', 'EXP_LAE'), ('EXP_HGU', 'EXP_HGU')], db_index=True, max_length=20, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('disabled_reason', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('required_rate_gate_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route Automation Policy',
                'verbose_name_plural': 'Route Automation Policies',
                'db_table': 'route_automation_policies',
                'ordering': ['route_pattern'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentJourneyDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('direction', models.CharField(blank=True, choices=[('IMPORT', 'IMPORT'), ('EXPORT', 'EXPORT')], default='', max_length=10)),
                ('pattern', models.CharField(blank=True, choices=[('IMP_POM', 'IMP_POM'), ('IMP_LAE', 'IMP_LAE'), ('IMP_HGU', 'IMP_HGU'), ('EXP_POM', 'EXP_POM'), ('EXP_LAE', 'EXP_LAE'), ('EXP_HGU', 'EXP_HGU')], default='', max_length=20)),
                ('gateway_code', models.CharField(blank=True, default='POM', max_length=10)),
                ('customer_origin_code', models.CharField(blank=True, default='', max_length=20)),
                ('customer_destination_code', models.CharField(blank=True, default='', max_length=20)),
                ('route_policy_key', models.CharField(blank=True, default='', max_length=50)),
                ('rule_version', models.CharField(max_length=80)),
                ('input_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('NEEDS_REVIEW', 'Needs review'), ('PRICED', 'Priced'), ('FINALIZED', 'Finalized'), ('SUPERSEDED', 'Superseded')], db_index=True, default='PLANNED', max_length=20)),
                ('blockers_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_journeys', to='quotes.quote')),
                ('spot_envelope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_journeys', to='quotes.spotpricingenvelopedb')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='quotes.shipmentjourneydb')),
            ],
            options={
                'db_table': 'shipment_journeys',
                'ordering': ['-created_at', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLegDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leg_key', models.CharField(max_length=120)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('INTERNATIONAL_IMPORT', 'INTERNATIONAL_IMPORT'), ('INTERNATIONAL_EXPORT', 'INTERNATIONAL_EXPORT'), ('DOMESTIC_ON_FORWARDING', 'DOMESTIC_ON_FORWARDING'), ('DOMESTIC_PRE_CARRIAGE', 'DOMESTIC_PRE_CARRIAGE'), ('FINAL_PICKUP', 'FINAL_PICKUP'), ('FINAL_DELIVERY', 'FINAL_DELIVERY')], max_length=32)),
                ('transport_mode', models.CharField(choices=[('INTERNATIONAL_AIR', 'INTERNATIONAL_AIR'), ('DOMESTIC_AIR', 'DOMESTIC_AIR'), ('LOCAL_ROAD', 'LOCAL_ROAD')], max_length=32)),
                ('origin_code', models.CharField(max_length=20)),
                ('destination_code', models.CharField(max_length=20)),
                ('product_code_domain', models.CharField(choices=[('IMPORT', 'IMPORT'), ('EXPORT', 'EXPORT'), ('DOMESTIC', 'DOMESTIC')], max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('service_scope', models.CharField(blank=True, default='', max_length=20)),
                ('chargeable_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('NEEDS_REVIEW', 'Needs review'), ('PRICED', 'Priced'), ('FINALIZED', 'Finalized'), ('SUPERSEDED', 'Superseded')], db_index=True, default='PLANNED', max_length=20)),
                ('rate_coverage_status', models.CharField(choices=[('NOT_CHECKED', 'Not checked'), ('MISSING', 'Missing'), ('AVAILABLE', 'Available')], db_index=True, default='NOT_CHECKED', max_length=20)),
                ('blockers_json', models.JSONField(blank=True, default=list)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='quotes.shipmentjourneydb')),
            ],
            options={
                'db_table': 'shipment_legs',
                'ordering': ['journey', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='quoteline',
            name='journey_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='quotes.shipmentlegdb'),
        ),
        migrations.AddField(
            model_name='spechargelinedb',
            name='journey_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_charge_lines', to='quotes.shipmentlegdb'),
        ),
        migrations.AddConstraint(
            model_name='shipmentjourneydb',
            constraint=models.CheckConstraint(condition=models.Q(('quote__isnull', False), ('spot_envelope__isnull', False), _connector='OR'), name='shipment_journey_parent_required'),
        ),
        migrations.AddConstraint(
            model_name='shipmentjourneydb',
            constraint=models.UniqueConstraint(condition=models.Q(('quote__isnull', False)), fields=('quote', 'revision'), name='uniq_shipment_journey_quote_revision'),
        ),
        migrations.AddConstraint(
            model_name='shipmentjourneydb',
            constraint=models.UniqueConstraint(condition=models.Q(('spot_envelope__isnull', False)), fields=('spot_envelope', 'revision'), name='uniq_shipment_journey_spot_revision'),
        ),
        migrations.AddConstraint(
            model_name='shipmentlegdb',
            constraint=models.UniqueConstraint(fields=('journey', 'sequence'), name='uniq_shipment_leg_journey_sequence'),
        ),
        migrations.AddConstraint(
            model_name='shipmentlegdb',
            constraint=models.UniqueConstraint(fields=('journey', 'leg_key'), name='uniq_shipment_leg_journey_leg_key'),
        ),
        migrations.RunPython(seed_disabled_route_policies, unseed_disabled_route_policies),
    ]
