# Generated by Django 5.2.14 on 2026-09-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0048_restore_quoteline_preservation_columns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverrideNote',
        ),
    ]
