# Generated by Django 5.2.14 on 2026-09-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0049_delete_overridenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='opportunity',
        ),
    ]
