# Generated by Django 5.2.5 on 2025-09-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rate_engine", "0003_quotes_incoterm"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE ratecards ALTER COLUMN created_at SET DEFAULT NOW();",
            "ALTER TABLE ratecards ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            "ALTER TABLE ratecards ALTER COLUMN updated_at SET DEFAULT NOW();",
            "ALTER TABLE ratecards ALTER COLUMN updated_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            "ALTER TABLE ratecard_config ALTER COLUMN created_at SET DEFAULT NOW();",
            "ALTER TABLE ratecard_config ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            "ALTER TABLE ratecard_fees ALTER COLUMN created_at SET DEFAULT NOW();",
            "ALTER TABLE ratecard_fees ALTER COLUMN created_at DROP DEFAULT;",
        ),
    ]
