# Generated by Django 5.2.5 on 2025-09-17 20:47

import django.db.models.deletion
from django.db import migrations, models

def set_default_audience(apps, schema_editor):
    Audience = apps.get_model('pricing', 'Audience')
    Ratecard = apps.get_model('pricing', 'Ratecards')
    default_audience, _ = Audience.objects.get_or_create(
        party_type='AGENT',
        region='OVERSEAS',
        settlement='PREPAID',
        defaults={'code': 'OVERSEAS_AGENT_PREPAID', 'is_active': True},
    )
    Ratecard.objects.filter(audience__isnull=True).update(audience=default_audience)


def unset_default_audience(apps, schema_editor):
    Ratecard = apps.get_model('pricing', 'Ratecards')
    Ratecard.objects.filter(audience__code='OVERSEAS_AGENT_PREPAID').update(audience=None)



class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_populate_audience_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratecards',
            name='audience_old',
        ),
        migrations.RunPython(set_default_audience, unset_default_audience),
        migrations.AlterField(
            model_name='ratecards',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.audience'),
        ),
    ]
