# Generated by Django 5.2.5 on 2025-09-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_remove_ratecards_audience_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingpolicy',
            name='caf_on_fx',
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='caf_buy_pct',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='CAF % for converting foreign currency to PGK (e.g., 0.05 for 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='caf_sell_pct',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='CAF % for converting PGK to foreign currency (e.g., 0.10 for 10%)', max_digits=5),
        ),
    ]
