# Generated by Django 5.2.5 on 2025-11-25 04:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_backfill_city_locations'),
        ('parties', '0001_initial'),
        ('quotes', '0004_remove_quote_destination_airport_and_more'),
        ('services', '0003_delete_incotermrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], max_length=10, null=True)),
                ('method', models.CharField(choices=[('WEIGHT_BREAK', 'Weight Break'), ('FLAT', 'Flat Fee'), ('PER_UNIT', 'Per Unit'), ('PERCENT', 'Percentage')], max_length=20)),
                ('unit', models.CharField(blank=True, choices=[('KG', 'Per Kg'), ('CBM', 'Per CBM'), ('PIECE', 'Per Piece'), ('SHIPMENT', 'Per Shipment')], max_length=20, null=True)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(default='PGK', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicecomponent')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_fees_as_destination', to='core.location')),
                ('origin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_fees_as_origin', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteSpotRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spot_rates_as_destination', to='core.location')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spot_rates_as_origin', to='core.location')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_rates', to='quotes.quote')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parties.company')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteSpotCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('WEIGHT_BREAK', 'Weight Break'), ('FLAT', 'Flat Fee'), ('PER_UNIT', 'Per Unit'), ('PERCENT', 'Percentage')], max_length=20)),
                ('unit', models.CharField(blank=True, choices=[('KG', 'Per Kg'), ('CBM', 'Per CBM'), ('PIECE', 'Per Piece'), ('SHIPMENT', 'Per Shipment')], max_length=20, null=True)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Flat amount or rate per unit', max_digits=12)),
                ('min_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('percent_value', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicecomponent')),
                ('percent_of_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spot_percent_charges', to='services.servicecomponent')),
                ('spot_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='pricing_v3.quotespotrate')),
            ],
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], max_length=10)),
                ('currency', models.CharField(help_text='ISO 3-letter currency code', max_length=3)),
                ('scope', models.CharField(choices=[('CONTRACT', 'Contract Rate'), ('SPOT', 'Spot Rate')], default='CONTRACT', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3_rate_cards', to='parties.company')),
            ],
        ),
        migrations.CreateModel(
            name='RateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('WEIGHT_BREAK', 'Weight Break'), ('FLAT', 'Flat Fee'), ('PER_UNIT', 'Per Unit'), ('PERCENT', 'Percentage')], max_length=20)),
                ('unit', models.CharField(blank=True, choices=[('KG', 'Per Kg'), ('CBM', 'Per CBM'), ('PIECE', 'Per Piece'), ('SHIPMENT', 'Per Shipment')], max_length=20, null=True)),
                ('min_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('percent_value', models.DecimalField(blank=True, decimal_places=4, help_text='e.g. 0.05 for 5%', max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing_v3.ratecard')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicecomponent')),
                ('percent_of_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='percent_lines', to='services.servicecomponent')),
            ],
        ),
        migrations.CreateModel(
            name='RateBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('to_value', models.DecimalField(blank=True, decimal_places=2, help_text='Null means infinity/open-ended', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate per unit in card currency', max_digits=12)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='pricing_v3.rateline')),
            ],
            options={
                'ordering': ['from_value'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(blank=True, choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], max_length=10, null=True)),
                ('partner', models.ForeignKey(blank=True, help_text="If set, this zone is specific to a partner's definition.", null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.company')),
            ],
        ),
        migrations.AddField(
            model_name='ratecard',
            name='destination_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_cards_as_destination', to='pricing_v3.zone'),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='origin_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_cards_as_origin', to='pricing_v3.zone'),
        ),
        migrations.CreateModel(
            name='ZoneMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_memberships', to='core.location')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pricing_v3.zone')),
            ],
        ),
        migrations.AddIndex(
            model_name='ratecard',
            index=models.Index(fields=['mode', 'scope', 'priority', 'valid_from'], name='pricing_v3__mode_b85f55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zonemember',
            unique_together={('zone', 'location')},
        ),
    ]
