# Generated by Django 5.2.5 on 2025-11-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v3', '0001_initial'),
        ('services', '0003_delete_incotermrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfeerule',
            name='percent_of_component',
            field=models.ForeignKey(blank=True, help_text='Component to calculate percentage of', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_fee_percentage_dependencies', to='services.servicecomponent'),
        ),
        migrations.AddField(
            model_name='localfeerule',
            name='percent_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Percentage as decimal (e.g., 0.10 for 10%)', max_digits=5, null=True),
        ),
    ]
