# Generated by Django 5.2.5 on 2025-11-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v3', '0002_localfeerule_percent_of_component_and_more'),
        ('services', '0003_delete_incotermrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_percent', models.DecimalField(decimal_places=4, help_text='Margin as decimal (e.g., 0.20 for 20%)', max_digits=5)),
                ('customer_segment', models.CharField(blank=True, help_text='Optional: segment-specific margin (VIP, STANDARD, BULK, etc.)', max_length=50)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='margin_rules', to='services.servicecomponent')),
            ],
            options={
                'indexes': [models.Index(fields=['component', 'is_active'], name='pricing_v3__compone_5b536c_idx')],
                'unique_together': {('component', 'customer_segment')},
            },
        ),
    ]
