# Generated by Django 5.2.5 on 2025-10-22 20:51

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Short, unique, stable code (e.g., 'PKUP_ORG', 'CLEAR_IMP', 'FRT_AIR').", max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], db_index=True, max_length=10)),
                ('leg', models.CharField(choices=[('ORIGIN', 'Origin'), ('MAIN', 'Main Freight'), ('DESTINATION', 'Destination')], db_index=True, max_length=20)),
                ('base_pgk_cost', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Standard internal cost for this service in PGK.', max_digits=12)),
                ('unit', models.CharField(choices=[('SHIPMENT', 'Per Shipment'), ('KG', 'Per KG'), ('WM', 'Per W/M'), ('CBM', 'Per CBM'), ('TEU', 'Per TEU'), ('FEU', 'Per FEU'), ('PALLET', 'Per Pallet'), ('KM', 'Per KM')], default='SHIPMENT', help_text='The unit basis for the base_pgk_cost (e.g., Per KG, Per Shipment).', max_length=20)),
                ('min_charge_pgk', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cost applied for this component in PGK.', max_digits=10, null=True)),
                ('tiering_json', models.JSONField(blank=True, help_text='JSON defining tiered pricing rules (e.g., weight breaks, CBM breaks).', null=True)),
                ('audience', models.CharField(choices=[('BUY', 'Buy Side'), ('SELL', 'Sell Side'), ('BOTH', 'Both')], default='BOTH', help_text='Is this primarily a Buy cost, Sell charge, or both?', max_length=10)),
                ('tax_code', models.CharField(blank=True, help_text="Tax code reference (e.g., 'GST_10', 'ZERO_RATED').", max_length=20, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['mode', 'leg', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IncotermRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], db_index=True, max_length=10)),
                ('shipment_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], db_index=True, max_length=10)),
                ('incoterm', models.CharField(db_index=True, max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('service_components', models.ManyToManyField(help_text='Select the services included in the scope for this Incoterm rule.', related_name='incoterm_rules', to='services.servicecomponent')),
            ],
            options={
                'verbose_name': 'Incoterm Rule',
                'verbose_name_plural': 'Incoterm Rules',
                'ordering': ['mode', 'shipment_type', 'incoterm'],
                'unique_together': {('mode', 'shipment_type', 'incoterm')},
            },
        ),
    ]
