# Generated by Django 5.2.5 on 2025-11-06 22:47

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Short, unique, stable code (e.g., 'PKUP_ORG', 'CLEAR_IMP', 'FRT_AIR').", max_length=20, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], db_index=True, max_length=10)),
                ('leg', models.CharField(choices=[('ORIGIN', 'Origin'), ('MAIN', 'Main Freight'), ('DESTINATION', 'Destination')], db_index=True, max_length=20)),
                ('category', models.CharField(blank=True, choices=[('TRANSPORT', 'Transportation / Freight'), ('HANDLING', 'Handling / Terminal'), ('CUSTOMS', 'Customs / Regulatory'), ('DOCUMENTATION', 'Documentation'), ('LOCAL', 'Local / Cartage'), ('ACCESSORIAL', 'Accessorial / Other'), ('STATUTORY', 'Statutory / Pass-Through')], db_index=True, help_text='Category for grouping charges on quotes/invoices.', max_length=20, null=True)),
                ('cost_type', models.CharField(choices=[('COGS', 'COGS (Cost - Requires Lookup or Base)'), ('RATE_OFFER', 'Rate Offer (Sell Price - Requires Lookup or Base)')], default='COGS', help_text='Is this a direct cost (COGS) or a standard sell rate (Rate Offer)?', max_length=10)),
                ('cost_source', models.CharField(choices=[('BASE_COST', 'Base PGK Cost (Directly from this ServiceComponent)'), ('EXPORT_RATECARD', 'Export Rate Card (e.g., ratecards.RateCard)'), ('PARTNER_RATECARD', 'Partner Rate Card (e.g., Import AUD Rates - Requires New Model)'), ('LOCAL_TARIFF', 'Local Tariff (e.g., core.LocalTariff - PNG Sell Rates)'), ('SURCHARGE', 'Surcharge Table (e.g., core.Surcharge - PX Fees)')], default='BASE_COST', help_text='Where does the system find the cost/rate for this service?', max_length=20)),
                ('base_pgk_cost', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Standard internal cost or sell rate in PGK (used if cost_source is BASE_COST).', max_digits=12)),
                ('cost_currency_type', models.CharField(choices=[('PGK', 'PGK'), ('FCY', 'FCY')], default='PGK', help_text='Currency type if cost_source requires lookup (e.g., PARTNER_RATECARD often FCY).', max_length=3)),
                ('unit', models.CharField(choices=[('SHIPMENT', 'Per Shipment'), ('KG', 'Per KG'), ('WM', 'Per W/M'), ('CBM', 'Per CBM'), ('TEU', 'Per TEU'), ('FEU', 'Per FEU'), ('PALLET', 'Per Pallet'), ('KM', 'Per KM')], default='SHIPMENT', help_text='The unit basis for the cost/rate.', max_length=20)),
                ('min_charge_pgk', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum charge applied in PGK.', max_digits=10, null=True)),
                ('tiering_json', models.JSONField(blank=True, help_text='JSON defining tiered pricing rules.', null=True)),
                ('audience', models.CharField(choices=[('BUY', 'Buy Side'), ('SELL', 'Sell Side'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['mode', 'leg', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IncotermRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], db_index=True, max_length=10)),
                ('shipment_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], db_index=True, max_length=10)),
                ('incoterm', models.CharField(db_index=True, max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('service_components', models.ManyToManyField(help_text='Select the services included in the scope for this Incoterm rule.', related_name='incoterm_rules', to='services.servicecomponent')),
            ],
            options={
                'verbose_name': 'Incoterm Rule',
                'verbose_name_plural': 'Incoterm Rules',
                'ordering': ['mode', 'shipment_type', 'incoterm'],
                'unique_together': {('mode', 'shipment_type', 'incoterm')},
            },
        ),
    ]
