# Generated by Django 5.2.5 on 2025-11-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incotermrule",
            options={
                "ordering": [
                    "mode",
                    "shipment_type",
                    "incoterm",
                    "service_level",
                    "payment_term",
                ],
                "verbose_name": "Incoterm Rule",
                "verbose_name_plural": "Incoterm Rules",
            },
        ),
        migrations.AlterUniqueTogether(
            name="incotermrule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="incotermrule",
            name="payment_term",
            field=models.CharField(
                choices=[("PREPAID", "Prepaid"), ("COLLECT", "Collect")],
                db_index=True,
                default="PREPAID",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="incotermrule",
            name="service_level",
            field=models.CharField(
                choices=[
                    ("D2D", "Door-to-Door"),
                    ("A2D", "Airport-to-Door"),
                    ("D2A", "Door-to-Airport"),
                    ("A2A", "Airport-to-Airport"),
                ],
                db_index=True,
                default="D2D",
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="incotermrule",
            unique_together={
                ("mode", "shipment_type", "incoterm", "service_level", "payment_term")
            },
        ),
    ]
