# Generated by Django 5.2.5 on 2025-10-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomponent',
            name='category',
            field=models.CharField(blank=True, choices=[('TRANSPORT', 'Transportation / Freight'), ('HANDLING', 'Handling / Terminal'), ('CUSTOMS', 'Customs / Regulatory'), ('DOCUMENTATION', 'Documentation'), ('LOCAL', 'Local / Cartage'), ('ACCESSORIAL', 'Accessorial / Other'), ('STATUTORY', 'Statutory / Pass-Through')], db_index=True, help_text='Category for grouping charges on quotes/invoices.', max_length=20, null=True),
        ),
    ]
