# Generated by Django 5.2.5 on 2025-11-15 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], db_index=True, max_length=10)),
                ('direction', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], db_index=True, max_length=10)),
                ('incoterm', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('payment_term', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], db_index=True, max_length=10)),
                ('service_scope', models.CharField(choices=[('D2D', 'Door to Door'), ('D2A', 'Door to Airport'), ('A2D', 'Airport to Door'), ('A2A', 'Airport to Airport')], db_index=True, max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('output_currency_type', models.CharField(choices=[('DESTINATION', 'Match Destination Currency'), ('ORIGIN', 'Match Origin Currency'), ('PGK', 'Force PGK'), ('USD', 'Force USD')], default='DESTINATION', help_text='Determines how the sell/output currency should be derived.', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Rule',
                'verbose_name_plural': 'Service Rules',
                'ordering': ['mode', 'direction', 'incoterm', 'payment_term', 'service_scope'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRuleComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Ordering of the component within the rule.')),
                ('leg_owner', models.CharField(choices=[('COMPANY', 'Company Managed'), ('CUSTOMER', 'Customer Managed'), ('THIRD_PARTY', '3rd Party / Partner')], default='COMPANY', help_text='Who owns/manages this component within the scope.', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Marks whether the component is required for the scope.')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_rules', to='services.servicecomponent')),
                ('service_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_components', to='services.servicerule')),
            ],
            options={
                'verbose_name': 'Service Rule Component',
                'verbose_name_plural': 'Service Rule Components',
                'ordering': ['service_rule', 'sequence', 'service_component__code'],
                'unique_together': {('service_rule', 'service_component')},
            },
        ),
        migrations.AddField(
            model_name='servicerule',
            name='service_components',
            field=models.ManyToManyField(related_name='service_rules', through='services.ServiceRuleComponent', to='services.servicecomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerule',
            unique_together={('mode', 'direction', 'incoterm', 'payment_term', 'service_scope')},
        ),
    ]
