# Generated by Django 5.2.5 on 2025-10-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_seed_efm_partner_ratecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecomponent',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
