# Generated by Django 5.2.5 on 2025-12-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_incotermrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomponent',
            name='percent_of_component',
            field=models.ForeignKey(blank=True, help_text='If this is a percentage surcharge, reference the base component (e.g., Fuel Surcharge = 10%% of Cartage)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surcharges', to='services.servicecomponent'),
        ),
        migrations.AddField(
            model_name='servicecomponent',
            name='percent_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage value (e.g., 10.00 for 10%%). Only used if percent_of_component is set.', max_digits=5, null=True),
        ),
    ]
