# Generated by Django 5.2.5 on 2025-12-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_percentage_surcharge_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCode',
            fields=[
                ('code', models.CharField(help_text="Service code in format [LOCATION]-[TYPE]-[SUBTYPE], e.g., 'ORG-PICKUP-STD'", max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(help_text='Human-readable description of this service', max_length=200)),
                ('location_type', models.CharField(choices=[('ORIGIN', 'Origin'), ('MAIN', 'Main Freight'), ('DESTINATION', 'Destination')], db_index=True, help_text='Where this service is performed: ORIGIN, MAIN, or DESTINATION', max_length=20)),
                ('service_category', models.CharField(choices=[('PICKUP', 'Pickup & Collection'), ('DELIVERY', 'Delivery & Cartage'), ('CLEARANCE', 'Customs Clearance'), ('FREIGHT', 'Main Freight'), ('HANDLING', 'Handling & Terminal'), ('DOCUMENTATION', 'Documentation Fees'), ('AGENCY', 'Agency Fees'), ('SCREENING', 'Security & Screening'), ('FUEL_SURCHARGE', 'Fuel Surcharge'), ('OTHER', 'Other Charges')], db_index=True, help_text='Category of service for grouping and reporting', max_length=50)),
                ('pricing_method', models.CharField(choices=[('FX_CAF_MARGIN', 'FX + CAF + Margin (Origin Charges)'), ('PASSTHROUGH', 'Pass-through (Destination Charges)'), ('RATE_OF_BASE', 'Percentage of Base (Fuel Surcharges)'), ('STANDARD_RATE', 'Standard Rate (Freight)')], help_text='How this service should be priced by the engine', max_length=20)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether GST/VAT applies to this service')),
                ('gl_code', models.CharField(blank=True, help_text='General Ledger code for accounting integration', max_length=20, null=True)),
                ('revenue_account', models.CharField(blank=True, help_text='Revenue account code', max_length=50, null=True)),
                ('cost_account', models.CharField(blank=True, help_text='Cost account code', max_length=50, null=True)),
                ('requires_weight', models.BooleanField(default=False, help_text='Whether this service requires weight information')),
                ('requires_dimensions', models.BooleanField(default=False, help_text='Whether this service requires dimension information')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether this service must be included in quotes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service code is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this service code', null=True)),
            ],
            options={
                'verbose_name': 'Service Code',
                'verbose_name_plural': 'Service Codes',
                'db_table': 'service_codes',
                'ordering': ['code'],
            },
        ),
    ]
