# Generated by Django 5.2.5 on 2025-12-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_service_code_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomponent',
            name='service_code',
            field=models.ForeignKey(blank=True, help_text='Service code for deterministic classification (Phase 2). Nullable for backward compatibility.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='services.servicecode'),
        ),
    ]
