# Generated by Django 5.2.5 on 2025-12-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_add_service_code_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecomponent',
            name='unit',
            field=models.CharField(choices=[('SHIPMENT', 'Per Shipment'), ('KG', 'Per KG'), ('WM', 'Per W/M'), ('CBM', 'Per CBM'), ('TEU', 'Per TEU'), ('FEU', 'Per FEU'), ('PALLET', 'Per Pallet'), ('KM', 'Per KM'), ('PAGE', 'Per Page')], default='SHIPMENT', help_text='The unit basis for the cost/rate.', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerule',
            name='output_currency_type',
            field=models.CharField(choices=[('DESTINATION', 'Match Destination Currency'), ('ORIGIN', 'Match Origin Currency'), ('ORIGIN_AU_USD', 'AU Origin→AUD, Else→USD'), ('PGK', 'Force PGK'), ('USD', 'Force USD')], default='DESTINATION', help_text='Determines how the sell/output currency should be derived.', max_length=20),
        ),
    ]
