# Generated by Django 5.2.5 on 2026-03-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_add_fuel_surcharge_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecomponent',
            name='cost_source',
            field=models.CharField(choices=[('BASE_COST', 'Base PGK Cost (Directly from this ServiceComponent)'), ('EXPORT_RATECARD', 'Export Rate Card (e.g., ratecards.RateCard)'), ('PARTNER_RATECARD', 'Partner Rate Card (e.g., Import AUD Rates - Requires New Model)'), ('SURCHARGE', 'Surcharge Table (e.g., core.Surcharge - PX Fees)')], default='BASE_COST', help_text='Where does the system find the cost/rate for this service?', max_length=20),
        ),
    ]
