# Generated by Django 5.2.5 on 2026-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicecomponent_cost_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecomponent',
            name='mode',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land'), ('CUSTOMS', 'Customs')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerule',
            name='mode',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land'), ('CUSTOMS', 'Customs')], db_index=True, max_length=10),
        ),
    ]
