# Generated by Django 5.2.14 on 2026-09-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicecomponent_cost_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRuleComponent',
        ),
        migrations.DeleteModel(
            name='ServiceRule',
        ),
    ]
