# Generated by Django 5.2.5 on 2026-04-30 03:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0007_company_account_owner_company_industry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('CUSTOMS', 'Customs'), ('DOMESTIC', 'Domestic'), ('MULTIMODAL', 'Multimodal')], db_index=True, max_length=20)),
                ('direction', models.CharField(blank=True, choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], db_index=True, default='', max_length=16)),
                ('scope', models.CharField(blank=True, choices=[('D2D', 'Door to Door'), ('D2A', 'Door to Airport'), ('A2D', 'Airport to Door'), ('A2A', 'Airport to Airport')], default='', max_length=3)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estimated_fcl_count', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_frequency', models.CharField(blank=True, default='', max_length=120)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_currency', models.CharField(blank=True, default='PGK', max_length=3)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('QUOTED', 'Quoted'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10)),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('won_reason', models.TextField(blank=True, default='')),
                ('lost_reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='parties.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL)),
                ('won_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Call'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('SITE_VISIT', 'Site Visit'), ('SYSTEM', 'System')], max_length=20)),
                ('summary', models.TextField()),
                ('outcomes', models.TextField(blank=True, default='')),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('is_system_generated', models.BooleanField(db_index=True, default=False)),
                ('system_event_type', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_interactions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='parties.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='parties.contact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_tasks', to='parties.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.opportunity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'status'], name='crm_opportu_company_40bb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner', 'status'], name='crm_opportu_owner_i_0d8158_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['service_type', 'priority'], name='crm_opportu_service_c46b15_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['company', '-created_at'], name='crm_interac_company_f1dc78_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['opportunity', '-created_at'], name='crm_interac_opportu_401aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['interaction_type', '-created_at'], name='crm_interac_interac_7913d3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'status', 'due_date'], name='crm_task_owner_i_caad09_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'status'], name='crm_task_company_f552b0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['opportunity', 'status'], name='crm_task_opportu_719968_idx'),
        ),
    ]
