# Generated by Django 5.2.5 on 2026-05-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_opportunity_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
