# Generated by Django 5.2.14 on 2026-06-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_opportunity_service_type'),
        ('parties', '0009_company_branch_company_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Future RBAC branch scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_interactions', to='parties.branch'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Future RBAC department scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_interactions', to='parties.department'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Future RBAC organization scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_interactions', to='parties.organization'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Future RBAC branch scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunities', to='parties.branch'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Future RBAC department scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunities', to='parties.department'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Future RBAC organization scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunities', to='parties.organization'),
        ),
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Future RBAC branch scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to='parties.branch'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Future RBAC department scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to='parties.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Future RBAC organization scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to='parties.organization'),
        ),
    ]
