# Generated by Django on 2026-09-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_interaction_branch_interaction_department_and_more'),
        ('quotes', '0050_remove_quote_opportunity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
