# Generated by Django 5.2.5 on 2025-10-10 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='State / Province')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'constraints': [models.UniqueConstraint(fields=('address_line_1', 'address_line_2', 'city', 'state_province', 'postcode', 'country'), name='unique_address')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('audience_type', models.CharField(choices=[('LOCAL_PNG_CUSTOMER', 'Local PNG Customer'), ('OVERSEAS_PARTNER_AU', 'Overseas Partner (AU)'), ('OVERSEAS_PARTNER_NON_AU', 'Overseas Partner (Non-AU)')], default='LOCAL_PNG_CUSTOMER', max_length=50)),
                ('address_description', models.TextField(blank=True, help_text="For PNG addresses without formal structure, e.g., 'Warehouse next to the main market, Gordons'", null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('primary_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.address')),
            ],
        ),
    ]
