# Generated by Django 5.2.5 on 2025-10-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='audience_type',
            field=models.CharField(blank=True, choices=[('PNG_SHIPPER', 'PNG_SHIPPER'), ('OVERSEAS_AGENT_AU', 'OVERSEAS_AGENT_AU'), ('OVERSEAS_AGENT_NON_AU', 'OVERSEAS_AGENT_NON_AU')], max_length=50, null=True),
        ),
    ]
