# Generated by Django 5.2.5 on 2025-10-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_audience_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='audience_type',
            field=models.CharField(choices=[('PNG_SHIPPER', 'PNG_SHIPPER'), ('OVERSEAS_AGENT_AU', 'OVERSEAS_AGENT_AU'), ('OVERSEAS_AGENT_NON_AU', 'OVERSEAS_AGENT_NON_AU')], default='PNG_SHIPPER', help_text='Defines the business relationship for quoting purposes.', max_length=50),
        ),
    ]
