# Generated by Django 5.2.5 on 2025-10-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_contact_customer_customer_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='company_name',
        ),
    ]
