# Generated by Django 5.2.5 on 2025-10-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_address_line_1_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='audience_type',
            field=models.CharField(choices=[('LOCAL_PNG_CUSTOMER', 'Local PNG Customer'), ('OVERSEAS_PARTNER_AU', 'Overseas Partner (AU)'), ('OVERSEAS_PARTNER_NON_AU', 'Overseas Partner (Non-AU)')], default='LOCAL_PNG_CUSTOMER', help_text='Defines the business relationship for quoting purposes.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
