# Generated by Django 5.2.5 on 2025-10-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_address_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State / Province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_description',
            field=models.TextField(blank=True, help_text="For PNG addresses without formal structure, e.g., 'Warehouse next to the main market, Gordons'", null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='audience_type',
            field=models.CharField(choices=[('LOCAL_PNG_CUSTOMER', 'Local PNG Customer'), ('OVERSEAS_PARTNER_AU', 'Overseas Partner (AU)'), ('OVERSEAS_PARTNER_NON_AU', 'Overseas Partner (Non-AU)')], default='LOCAL_PNG_CUSTOMER', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
