# Generated by Django 5.2.5 on 2026-01-12 23:49

from django.db import migrations, models

def migrate_roles(apps, schema_editor):
    Company = apps.get_model('parties', 'Company')
    for company in Company.objects.all():
        if company.company_type == 'CUSTOMER':
            company.is_customer = True
        elif company.company_type == 'SUPPLIER':
            company.is_agent = True
            # Auto-detect Carrier if name implies it
            if "Carrier" in company.name or "Air Niugini" in company.name:
                company.is_carrier = True
        company.save()

class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], default='CUSTOMER', max_length=20, null=True),
        ),
        migrations.RunPython(migrate_roles),
    ]
