# Generated by Django 5.2.5 on 2025-10-22 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fxsnapshot_caf_percent_fxsnapshot_fx_buffer_percent'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCommercialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_margin_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Override standard margin for this customer (e.g., 0.12 for 12%).', max_digits=5, null=True)),
                ('min_margin_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum allowable margin for quotes to this customer.', max_digits=5, null=True)),
                ('payment_term_default', models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], help_text='Default payment term if known.', max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='parties.company')),
                ('preferred_quote_currency', models.ForeignKey(blank=True, help_text='Default currency for quoting this customer (e.g., AUD, USD).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Commercial Profile',
                'verbose_name_plural': 'Customer Commercial Profiles',
            },
        ),
    ]
