# Generated by Django 5.2.5 on 2025-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_company_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercommercialprofile',
            name='default_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override standard margin for this customer (e.g., 12.00 for 12%).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customercommercialprofile',
            name='min_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowable margin for quotes to this customer.', max_digits=5, null=True),
        ),
    ]
