# Generated by Django 5.2.5 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0003_contact_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
