# Generated by Django 5.2.5 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0004_company_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address_description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="audience_type",
            field=models.CharField(
                choices=[
                    ("LOCAL_PNG_CUSTOMER", "Local PNG Customer"),
                    ("OVERSEAS_PARTNER_AU", "Overseas Partner (AU)"),
                    ("OVERSEAS_PARTNER_NON_AU", "Overseas Partner (Non-AU)"),
                ],
                default="LOCAL_PNG_CUSTOMER",
                max_length=32,
            ),
        ),
    ]
