# Generated by Django 5.2.5 on 2026-03-19 20:42

import django.db.models.deletion
import parties.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_localtariff'),
        ('parties', '0005_company_audience_and_address_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('time_zone', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(blank=True, help_text='Default quote/output currency for this organization.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('logo_primary', models.ImageField(blank=True, null=True, upload_to=parties.models.branding_upload_to)),
                ('logo_small', models.ImageField(blank=True, null=True, upload_to=parties.models.branding_upload_to)),
                ('primary_color', models.CharField(blank=True, default='', max_length=7)),
                ('accent_color', models.CharField(blank=True, default='', max_length=7)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=64)),
                ('website_url', models.URLField(blank=True, default='')),
                ('address_lines', models.TextField(blank=True, default='')),
                ('quote_footer_text', models.TextField(blank=True, default='')),
                ('public_quote_tagline', models.CharField(blank=True, default='', max_length=255)),
                ('email_signature_text', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='parties.organization')),
            ],
            options={
                'verbose_name': 'Organization Branding',
                'verbose_name_plural': 'Organization Branding',
            },
        ),
    ]
