# Generated by Django 5.2.14 on 2026-06-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_branch_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Future RBAC branch scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='parties.branch'),
        ),
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Future RBAC department scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='parties.department'),
        ),
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Future RBAC organization scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='parties.organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Future RBAC branch scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='parties.branch'),
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Future RBAC department scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='parties.department'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Future RBAC organization scope. Nullable until backfilled and enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='parties.organization'),
        ),
    ]
