# Generated by Django 5.2.5 on 2026-06-28 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_company_branch_company_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64)),
                ('country_code', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_entities', to='parties.organization')),
            ],
            options={
                'ordering': ['organization__name', 'code'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='op_entity_org_active_idx'), models.Index(fields=['organization', 'country_code'], name='op_entity_org_country_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='unique_operating_entity_code_per_organization'), models.UniqueConstraint(fields=('organization', 'slug'), name='unique_operating_entity_slug_per_organization'), models.UniqueConstraint(fields=('organization', 'name'), name='unique_operating_entity_name_per_organization')],
            },
        ),
    ]
