# Generated by Django 5.2.14 on 2026-07-09 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0011_branch_operating_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='operating_entity',
            field=models.ForeignKey(blank=True, help_text='RBAC operating-entity scope for customer master visibility. Nullable until backfilled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='parties.operatingentity'),
        ),
    ]
