# Generated by Django 5.2.14 on 2026-09-21 05:42

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (
        ("core", "0012_clean_db_foundation"),
        ("parties", "0012_company_operating_entity"),
    )

    operations = (
        migrations.CreateModel(
            name="OrgCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=24, unique=True)),
                ("country_code", models.CharField(max_length=2)),
                ("currency_code", models.CharField(max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "org_company",
            },
        ),
        migrations.CreateModel(
            name="OrgOperatingEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=24)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                ("functional_currency", models.CharField(max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_entities",
                        to="parties.orgcompany",
                    ),
                ),
            ],
            options={
                "db_table": "org_operating_entity",
            },
        ),
        migrations.CreateModel(
            name="OrgBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=24)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="core.geolocation",
                    ),
                ),
                (
                    "operating_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="parties.orgoperatingentity",
                    ),
                ),
            ],
            options={
                "db_table": "org_branch",
            },
        ),
        migrations.CreateModel(
            name="PartyMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                ("entity_type", models.CharField(max_length=50)),
                ("country_code", models.CharField(max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "party_master",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_name", "country_code"),
                        name="party_name_country_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="parties.partymaster",
                    ),
                ),
            ],
            options={
                "db_table": "party_contact",
            },
        ),
        migrations.CreateModel(
            name="PartyAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("BILLING", "Billing"),
                            ("PHYSICAL", "Physical"),
                            ("DEPOT", "Depot"),
                        ],
                        max_length=16,
                    ),
                ),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="core.geolocation",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="parties.partymaster",
                    ),
                ),
            ],
            options={
                "db_table": "party_address",
            },
        ),
        migrations.CreateModel(
            name="PartyRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("CARRIER", "Carrier"),
                            ("AGENT", "Agent"),
                            ("SUPPLIER", "Supplier"),
                            ("VENDOR", "Vendor"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="parties.partymaster",
                    ),
                ),
            ],
            options={
                "db_table": "party_role",
            },
        ),
        migrations.CreateModel(
            name="PartyRoleIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("IATA_CARRIER", "IATA carrier"),
                            ("ICAO", "ICAO"),
                            ("SCAC", "SCAC"),
                            ("CUSTOMS_BROKER", "Customs broker"),
                            ("TAX_ID", "Tax ID"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identifiers",
                        to="parties.partyrole",
                    ),
                ),
            ],
            options={
                "db_table": "party_role_identifier",
            },
        ),
        migrations.CreateModel(
            name="OrgDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=24)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="parties.orgbranch",
                    ),
                ),
            ],
            options={
                "db_table": "org_department",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "code"),
                        name="org_department_branch_code_uniq",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="orgoperatingentity",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="org_entity_company_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="orgbranch",
            constraint=models.UniqueConstraint(
                fields=("operating_entity", "code"), name="org_branch_entity_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="partycontact",
            constraint=models.UniqueConstraint(
                fields=("party", "email"), name="party_contact_email_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="partyaddress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("address_type__in", ["BILLING", "PHYSICAL", "DEPOT"])
                ),
                name="party_address_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="partyrole",
            constraint=models.UniqueConstraint(
                fields=("party", "role_type"), name="party_role_type_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="partyrole",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role_type__in",
                        ["CUSTOMER", "CARRIER", "AGENT", "SUPPLIER", "VENDOR"],
                    )
                ),
                name="party_role_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="partyroleidentifier",
            constraint=models.UniqueConstraint(
                fields=("scheme", "value"), name="party_identifier_scheme_val_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="partyroleidentifier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "scheme__in",
                        ["IATA_CARRIER", "ICAO", "SCAC", "CUSTOMS_BROKER", "TAX_ID"],
                    )
                ),
                name="party_identifier_scheme_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="partyroleidentifier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("value", ""), _negated=True),
                    ("value", django.db.models.functions.text.Trim("value")),
                ),
                name="party_identifier_value_trimmed",
            ),
        ),
    )
