import json
import os
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone
from django.contrib.auth import get_user_model

from pricing_v4.models import ChargeAlias, ProductCode
from quotes.spot_models import SPEChargeLineDB
from quotes.management.commands.spot_productcode_masterdata_audit import normalize_label
from quotes.management.commands.spot_productcode_close_loop_report import build_report as build_close_loop_report

APPLY_APPROVED_REQUEST = "APPLY_APPROVED_REQUEST"
APPLY_EXISTING_PRODUCT_CODE = "APPLY_EXISTING_PRODUCT_CODE"
CREATE_ALIAS_MAPPING = "CREATE_ALIAS_MAPPING"
CREATE_NEW_PRODUCT_CODE = "CREATE_NEW_PRODUCT_CODE"
MANUAL_REVIEW = "MANUAL_REVIEW"

VALID_ACTION_GROUPS = {
    APPLY_APPROVED_REQUEST,
    APPLY_EXISTING_PRODUCT_CODE,
    CREATE_ALIAS_MAPPING,
}


class Command(BaseCommand):
    help = "Controlled apply command to execute approved SPOT ProductCode remediation plans."

    def add_arguments(self, parser):
        parser.add_argument(
            "--plan",
            required=True,
            help="Path to the JSON plan file generated by spot_productcode_remediation_plan.",
        )
        parser.add_argument(
            "--apply",
            action="store_true",
            help="Actually perform the writes. Default is dry-run.",
        )
        parser.add_argument(
            "--action-group",
            action="append",
            dest="action_groups",
            choices=list(VALID_ACTION_GROUPS),
            help="Action groups to apply (can specify multiple times).",
        )

    def handle(self, *args, **options):
        plan_path = options["plan"]
        dry_run = not options["apply"]
        action_groups = options.get("action_groups") or []

        if not action_groups:
            raise CommandError("At least one explicit --action-group must be provided.")

        if not os.path.exists(plan_path):
            raise CommandError(f"Plan file does not exist: {plan_path}")

        try:
            with open(plan_path, "r", encoding="utf-8-sig") as f:
                plan_data = json.load(f)
        except Exception as e:
            raise CommandError(f"Failed to parse plan JSON file: {e}")

        # Get system user
        User = get_user_model()
        system_user = (
            User.objects.filter(username="system").first()
            or User.objects.filter(is_superuser=True).first()
            or User.objects.first()
        )

        readiness_before = build_close_loop_report()["readiness_status"]

        summary = {
            "writes_performed": not dry_run,
            "dry_run": dry_run,
            "selected_action_groups": action_groups,
            "planned_count": 0,
            "applied_count": 0,
            "skipped_count": 0,
            "error_count": 0,
            "per_action_results": [],
            "readiness_before": readiness_before,
            "readiness_after": readiness_before,
        }

        try:
            with transaction.atomic():
                for group in action_groups:
                    group_items = plan_data.get("plan", {}).get(group, [])
                    for item in group_items:
                        normalized_label = item.get("normalized_label")
                        pc_id = item.get("recommended_product_code_id")
                        confidence = item.get("confidence")
                        affected_ids = item.get("affected_charge_line_ids") or []

                        summary["planned_count"] += len(affected_ids)

                        # Validate ProductCode
                        if not pc_id:
                            self._log_skip(
                                summary,
                                group,
                                normalized_label,
                                "MISSING_PRODUCT_CODE",
                                affected_ids,
                            )
                            continue

                        product_code = ProductCode.objects.filter(id=pc_id).first()
                        if not product_code:
                            self._log_skip(
                                summary,
                                group,
                                normalized_label,
                                "PRODUCT_CODE_NOT_FOUND",
                                affected_ids,
                            )
                            continue

                        # Confidence validations
                        if group == APPLY_EXISTING_PRODUCT_CODE and confidence != "HIGH":
                            self._log_skip(
                                summary,
                                group,
                                normalized_label,
                                "LOW_CONFIDENCE",
                                affected_ids,
                            )
                            continue

                        if group == CREATE_ALIAS_MAPPING:
                            if confidence != "HIGH":
                                self._log_skip(
                                    summary,
                                    group,
                                    normalized_label,
                                    "LOW_CONFIDENCE",
                                    affected_ids,
                                )
                                continue

                            # CREATE_ALIAS_MAPPING: Create ChargeAlias if not dry-run
                            if not dry_run:
                                # Ensure we don't duplicate existing ChargeAlias
                                existing_alias = ChargeAlias.objects.filter(
                                    normalized_alias_text=normalize_label(normalized_label),
                                    product_code=product_code,
                                ).first()
                                if not existing_alias:
                                    ChargeAlias.objects.create(
                                        alias_text=normalized_label,
                                        product_code=product_code,
                                        is_active=True,
                                        review_status=ChargeAlias.ReviewStatus.APPROVED,
                                        alias_source=ChargeAlias.AliasSource.ADMIN,
                                    )

                        applied_lines = []
                        for cl_id in affected_ids:
                            line = SPEChargeLineDB.objects.filter(id=cl_id).first()
                            if not line:
                                summary["skipped_count"] += 1
                                summary["per_action_results"].append({
                                    "action_group": group,
                                    "normalized_label": normalized_label,
                                    "charge_line_id": cl_id,
                                    "status": "SKIPPED",
                                    "reason": "CHARGE_LINE_NOT_FOUND",
                                })
                                continue

                            # Validate is unresolved
                            is_resolved = (
                                line.manual_resolution_status == SPEChargeLineDB.ManualResolutionStatus.RESOLVED
                                and line.manual_resolved_product_code_id is not None
                            )
                            if is_resolved:
                                summary["skipped_count"] += 1
                                summary["per_action_results"].append({
                                    "action_group": group,
                                    "normalized_label": normalized_label,
                                    "charge_line_id": cl_id,
                                    "status": "SKIPPED",
                                    "reason": "ALREADY_RESOLVED",
                                })
                                continue

                            # Validate label match
                            line_norm = normalize_label(line.normalized_label or line.source_label or line.description)
                            if line_norm != normalized_label:
                                summary["skipped_count"] += 1
                                summary["per_action_results"].append({
                                    "action_group": group,
                                    "normalized_label": normalized_label,
                                    "charge_line_id": cl_id,
                                    "status": "SKIPPED",
                                    "reason": "STALE_LABEL_MISMATCH",
                                })
                                continue

                            # Apply resolution
                            if not dry_run:
                                line.manual_resolution_status = SPEChargeLineDB.ManualResolutionStatus.RESOLVED
                                line.manual_resolved_product_code = product_code
                                line.manual_resolution_by = system_user
                                line.manual_resolution_at = timezone.now()
                                line.save()

                            applied_lines.append(cl_id)
                            summary["applied_count"] += 1
                            summary["per_action_results"].append({
                                "action_group": group,
                                "normalized_label": normalized_label,
                                "charge_line_id": cl_id,
                                "status": "APPLIED" if not dry_run else "WOULD_APPLY",
                                "reason": f"Resolved to ProductCode {product_code.code}",
                            })

                if dry_run:
                    raise DryRunRollback()

        except DryRunRollback:
            # Expected dry-run rollback
            pass
        except Exception as e:
            summary["error_count"] += 1
            summary["per_action_results"].append({
                "status": "ERROR",
                "reason": str(e),
            })
            self.stdout.write(json.dumps(summary, indent=2, sort_keys=True))
            raise e

        # Calculate readiness after
        try:
            readiness_after = build_close_loop_report()["readiness_status"]
            summary["readiness_after"] = readiness_after
        except Exception:
            pass

        self.stdout.write(json.dumps(summary, indent=2, sort_keys=True))

    def _log_skip(self, summary, group, normalized_label, reason, affected_ids):
        for cl_id in affected_ids:
            summary["skipped_count"] += 1
            summary["per_action_results"].append({
                "action_group": group,
                "normalized_label": normalized_label,
                "charge_line_id": cl_id,
                "status": "SKIPPED",
                "reason": reason,
            })


class DryRunRollback(Exception):
    pass
