# Generated by Django 5.2.5 on 2026-03-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0006_organization_organizationbranding"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentaddressbookentry",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment_address_book_entries",
                to="parties.company",
            ),
        ),
        migrations.AddField(
            model_name="shipmentaddressbookentry",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment_address_book_entries",
                to="parties.contact",
            ),
        ),
    ]
