# Generated by Django 5.2.5 on 2026-03-23 15:05

from django.db import migrations, models


def _merge_descriptions(*values):
    cleaned = []
    for value in values:
        text = (value or "").strip()
        if text and text not in cleaned:
            cleaned.append(text)
    return " / ".join(cleaned)


def forwards(apps, schema_editor):
    Shipment = apps.get_model("shipments", "Shipment")
    ShipmentTemplate = apps.get_model("shipments", "ShipmentTemplate")

    for shipment in Shipment.objects.all().iterator():
        shipment.cargo_description = _merge_descriptions(
            getattr(shipment, "commodity_description", ""),
            getattr(shipment, "goods_description", ""),
        )
        shipment.save(update_fields=["cargo_description"])

    for template in ShipmentTemplate.objects.all().iterator():
        defaults = dict(template.shipment_defaults or {})
        defaults["cargo_description"] = _merge_descriptions(
            defaults.get("cargo_description", ""),
            defaults.get("commodity_description", ""),
            defaults.get("goods_description", ""),
        )
        defaults.pop("commodity_description", None)
        defaults.pop("goods_description", None)
        template.shipment_defaults = defaults
        template.save(update_fields=["shipment_defaults"])


def backwards(apps, schema_editor):
    Shipment = apps.get_model("shipments", "Shipment")
    ShipmentTemplate = apps.get_model("shipments", "ShipmentTemplate")

    for shipment in Shipment.objects.all().iterator():
        cargo = (getattr(shipment, "cargo_description", "") or "").strip()
        shipment.commodity_description = cargo
        shipment.goods_description = ""
        shipment.save(update_fields=["commodity_description", "goods_description"])

    for template in ShipmentTemplate.objects.all().iterator():
        defaults = dict(template.shipment_defaults or {})
        cargo = (defaults.get("cargo_description", "") or "").strip()
        defaults["commodity_description"] = cargo
        defaults["goods_description"] = ""
        defaults.pop("cargo_description", None)
        template.shipment_defaults = defaults
        template.save(update_fields=["shipment_defaults"])


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_shipmentaddressbookentry_company_and_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="cargo_description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="shipment",
            name="commodity_description",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="goods_description",
        ),
    ]
