# Generated by Django 5.2.5 on 2026-03-23 16:05

from django.db import migrations, models


SERVICE_LEVEL_TO_PRODUCT = {
    "EXPRESS": "EXPRESS",
    "PRIORITY": "STANDARD",
    "ECONOMY": "STANDARD",
    "CHARTER": "CHARTER",
}


def forwards(apps, schema_editor):
    Shipment = apps.get_model("shipments", "Shipment")
    ShipmentTemplate = apps.get_model("shipments", "ShipmentTemplate")

    for shipment in Shipment.objects.all().iterator():
        shipment.cargo_type = (
            "DANGEROUS_GOODS"
            if shipment.is_dangerous_goods
            else "PERISHABLE"
            if shipment.is_perishable
            else "GENERAL_CARGO"
        )
        shipment.service_product = SERVICE_LEVEL_TO_PRODUCT.get(shipment.service_level, "STANDARD")
        shipment.service_scope = "A2A"
        shipment.save(update_fields=["cargo_type", "service_product", "service_scope"])

    for template in ShipmentTemplate.objects.all().iterator():
        defaults = dict(template.shipment_defaults or {})
        defaults["cargo_type"] = (
            "DANGEROUS_GOODS"
            if defaults.get("is_dangerous_goods")
            else "PERISHABLE"
            if defaults.get("is_perishable")
            else defaults.get("cargo_type", "GENERAL_CARGO")
        )
        defaults["service_product"] = SERVICE_LEVEL_TO_PRODUCT.get(
            defaults.get("service_level", ""),
            defaults.get("service_product", "STANDARD"),
        )
        defaults["service_scope"] = defaults.get("service_scope", "A2A")
        defaults.pop("service_level", None)
        template.shipment_defaults = defaults
        template.save(update_fields=["shipment_defaults"])


def backwards(apps, schema_editor):
    Shipment = apps.get_model("shipments", "Shipment")
    ShipmentTemplate = apps.get_model("shipments", "ShipmentTemplate")

    for shipment in Shipment.objects.all().iterator():
        if shipment.service_product == "CHARTER":
            shipment.service_level = "CHARTER"
        elif shipment.service_product == "EXPRESS":
            shipment.service_level = "EXPRESS"
        else:
            shipment.service_level = "ECONOMY"
        shipment.save(update_fields=["service_level"])

    for template in ShipmentTemplate.objects.all().iterator():
        defaults = dict(template.shipment_defaults or {})
        product = defaults.get("service_product", "STANDARD")
        defaults["service_level"] = (
            "CHARTER" if product == "CHARTER" else "EXPRESS" if product == "EXPRESS" else "ECONOMY"
        )
        defaults.pop("cargo_type", None)
        defaults.pop("service_product", None)
        defaults.pop("service_scope", None)
        template.shipment_defaults = defaults
        template.save(update_fields=["shipment_defaults"])


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_replace_commodity_and_goods_with_cargo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="cargo_type",
            field=models.CharField(
                choices=[
                    ("GENERAL_CARGO", "General Cargo"),
                    ("VALUABLE_CARGO", "Valuable Cargo"),
                    ("PERISHABLE", "Perishable"),
                    ("LIVE_ANIMALS", "Live Animals"),
                    ("DANGEROUS_GOODS", "Dangerous Goods"),
                ],
                default="GENERAL_CARGO",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="service_product",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("EXPRESS", "Express"),
                    ("DOCUMENTS", "Documents"),
                    ("SMALL_PARCELS", "Small Parcels"),
                    ("CHARTER", "Charter"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="service_scope",
            field=models.CharField(
                choices=[
                    ("D2D", "Door-to-Door"),
                    ("D2A", "Door-to-Airport"),
                    ("A2D", "Airport-to-Door"),
                    ("A2A", "Airport-to-Airport"),
                ],
                default="A2A",
                max_length=3,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="shipment",
            name="service_level",
        ),
    ]
