# Generated by Codex on 2026-03-24

from django.db import migrations, models


DOMESTIC_COUNTRY_CODE = "PG"


def classify_shipment_type(shipment):
    origin_country = (shipment.origin_country_code or "").upper()
    destination_country = (shipment.destination_country_code or "").upper()

    if origin_country == DOMESTIC_COUNTRY_CODE and destination_country == DOMESTIC_COUNTRY_CODE:
        return "DOMESTIC"
    if origin_country == DOMESTIC_COUNTRY_CODE and destination_country and destination_country != DOMESTIC_COUNTRY_CODE:
        return "EXPORT"
    if destination_country == DOMESTIC_COUNTRY_CODE and origin_country and origin_country != DOMESTIC_COUNTRY_CODE:
        return "IMPORT"
    return "EXPORT"


def forwards(apps, schema_editor):
    Shipment = apps.get_model("shipments", "Shipment")
    for shipment in Shipment.objects.all().iterator():
        shipment.shipment_type = classify_shipment_type(shipment)
        shipment.branch = shipment.origin_code or ""
        shipment.save(update_fields=["shipment_type", "branch"])


def backwards(apps, schema_editor):
    Shipment = apps.get_model("shipments", "Shipment")
    for shipment in Shipment.objects.all().iterator():
        shipment.branch = ""
        shipment.save(update_fields=["branch"])


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0004_split_cargo_type_and_service_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="branch",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_type",
            field=models.CharField(
                choices=[
                    ("DOMESTIC", "Domestic"),
                    ("EXPORT", "Export"),
                    ("IMPORT", "Import (Legacy)"),
                ],
                db_index=True,
                default="DOMESTIC",
                max_length=16,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
