# Generated by Django 5.2.5 on 2026-03-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_scope_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('FINALIZED', 'Finalized'), ('PDF_GENERATED', 'PDF Generated'), ('REPRINTED', 'Reprinted'), ('DUPLICATED', 'Duplicated'), ('CANCELLED', 'Cancelled'), ('REISSUED', 'Reissued')], max_length=20),
        ),
    ]
