# Generated by Django 5.2.5 on 2025-10-23 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('parties', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name, e.g., 'EFM AUD Import Airfreight 2025'", max_length=255)),
                ('currency_code', models.CharField(help_text='The 3-letter ISO currency code of the rates (e.g., AUD, USD).', max_length=3)),
                ('valid_from', models.DateField(blank=True, help_text='The date this rate card becomes active.', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='The date this rate card expires.', null=True)),
                ('mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land')], default='AIR', help_text='The freight mode this card applies to (e.g., AIR, SEA).', max_length=10)),
                ('shipment_type', models.CharField(choices=[('GENERAL', 'General Cargo'), ('FCL', 'Full Container Load'), ('LCL', 'Less than Container Load')], default='GENERAL', help_text='The shipment type this card applies to (e.g., GENERAL, FCL, LCL).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(help_text='The partner/supplier these rates are from.', on_delete=django.db.models.deletion.CASCADE, related_name='partner_rate_cards', to='parties.company')),
            ],
            options={
                'verbose_name': 'Partner Rate Card',
                'verbose_name_plural': 'Partner Rate Cards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRateLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_airport', models.ForeignKey(blank=True, help_text='Destination airport for this lane.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_destination_lanes', to='core.airport')),
                ('origin_airport', models.ForeignKey(blank=True, help_text='Origin airport for this lane.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_origin_lanes', to='core.airport')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='ratecards.partnerratecard')),
            ],
            options={
                'verbose_name': 'Partner Rate Lane',
                'verbose_name_plural': 'Partner Rate Lanes',
                'ordering': ['origin_airport', 'destination_airport'],
                'unique_together': {('rate_card', 'origin_airport', 'destination_airport')},
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier', models.CharField(default='PX', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PGK', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratecards_destination', to='core.airport')),
                ('origin_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratecards_origin', to='core.airport')),
            ],
            options={
                'unique_together': {('origin_airport', 'destination_airport', 'carrier', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='PartnerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('PER_KG', 'Per KG'), ('PER_SHIPMENT', 'Per Shipment'), ('PER_CBM', 'Per CBM'), ('PER_PIECE', 'Per Piece'), ('PER_CONTAINER', 'Per Container')], default='PER_KG', help_text='The unit of measure for this rate.', max_length=20)),
                ('min_charge_fcy', models.DecimalField(decimal_places=2, default=0.0, help_text="Minimum charge in the card's foreign currency (FCY).", max_digits=10)),
                ('flat_fee_fcy', models.DecimalField(blank=True, decimal_places=2, help_text="A flat fee for 'PER_SHIPMENT' units, in FCY.", max_digits=10, null=True)),
                ('tiering_json', models.JSONField(blank=True, help_text="For 'PER_KG' units. Stores tier breaks and rates. e.g., [{'break': 0, 'rate': 5.50}, {'break': 100, 'rate': 5.00}]", null=True)),
                ('service_component', models.ForeignKey(help_text="The ServiceComponent this rate is for (e.g., 'Freight', 'Handling').", on_delete=django.db.models.deletion.CASCADE, related_name='partner_rates', to='services.servicecomponent')),
                ('lane', models.ForeignKey(help_text='The lane this rate applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='ratecards.partnerratelane')),
            ],
            options={
                'verbose_name': 'Partner Rate',
                'verbose_name_plural': 'Partner Rates',
                'unique_together': {('lane', 'service_component')},
            },
        ),
        migrations.CreateModel(
            name='RateCardBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_break_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='ratecards.ratecard')),
            ],
            options={
                'ordering': ['weight_break_kg'],
                'unique_together': {('rate_card', 'weight_break_kg')},
            },
        ),
    ]
