# Generated by Django 5.2.5 on 2025-10-14 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratecardfile',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='ratecardfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='ratecardfile',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='RateCardLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_code', models.CharField(help_text='IATA code for the origin airport', max_length=3)),
                ('destination_code', models.CharField(help_text='IATA code for the destination airport', max_length=3)),
                ('ratecard_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='ratecards.ratecardfile')),
            ],
            options={
                'unique_together': {('ratecard_file', 'origin_code', 'destination_code')},
            },
        ),
        migrations.CreateModel(
            name='RateBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_break_kg', models.DecimalField(decimal_places=2, help_text='The minimum weight for this rate break (e.g., 45 for +45kg)', max_digits=10)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='ratecards.ratecardlane')),
            ],
            options={
                'ordering': ['weight_break_kg'],
            },
        ),
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the surcharge (e.g., Fuel Surcharge)', max_length=100)),
                ('code', models.CharField(help_text='Short code for the surcharge (e.g., FSC)', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='ratecards.ratecardlane')),
            ],
        ),
    ]
