# Generated by Django 5.2.5 on 2025-11-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ratecards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerratelane',
            options={'ordering': ['mode', 'origin_airport', 'origin_port'], 'verbose_name': 'Partner Rate Lane', 'verbose_name_plural': 'Partner Rate Lanes'},
        ),
        migrations.AlterUniqueTogether(
            name='partnerratelane',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='partnerratecard',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='partnerratecard',
            name='shipment_type',
        ),
        migrations.AddField(
            model_name='partnerratelane',
            name='destination_port',
            field=models.ForeignKey(blank=True, help_text='Destination port (for SEA mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_destination_lanes_sea', to='core.port'),
        ),
        migrations.AddField(
            model_name='partnerratelane',
            name='mode',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], default='AIR', help_text='The freight mode this lane applies to (e.g., AIR, SEA).', max_length=10),
        ),
        migrations.AddField(
            model_name='partnerratelane',
            name='origin_port',
            field=models.ForeignKey(blank=True, help_text='Origin port (for SEA mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_origin_lanes_sea', to='core.port'),
        ),
        migrations.AddField(
            model_name='partnerratelane',
            name='shipment_type',
            field=models.CharField(choices=[('GENERAL', 'General Cargo'), ('FCL', 'FCL'), ('LCL', 'LCL'), ('BULK', 'Bulk')], default='GENERAL', help_text='The shipment type this lane applies to (e.g., GENERAL, FCL, LCL).', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerratecard',
            name='name',
            field=models.CharField(help_text="A descriptive name, e.g., 'EFM AUD Import Rates 2025'", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='partnerratelane',
            name='destination_airport',
            field=models.ForeignKey(blank=True, help_text='Destination airport (for AIR mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_destination_lanes', to='core.airport'),
        ),
        migrations.AlterField(
            model_name='partnerratelane',
            name='origin_airport',
            field=models.ForeignKey(blank=True, help_text='Origin airport (for AIR mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_origin_lanes', to='core.airport'),
        ),
        migrations.AlterField(
            model_name='partnerrate',
            name='min_charge_fcy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Minimum charge in the card's foreign currency (FCY).", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partnerrate',
            name='rate_per_kg_fcy',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="For 'PER_KG' units. The rate per kilogram in FCY.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partnerrate',
            name='rate_per_shipment_fcy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="For 'SHIPMENT' units. A flat fee per shipment in FCY.", max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='partnerrate',
            name='flat_fee_fcy',
        ),
        migrations.RemoveField(
            model_name='partnerrate',
            name='tiering_json',
        ),
        migrations.AlterUniqueTogether(
            name='partnerratelane',
            unique_together={('rate_card', 'origin_airport', 'destination_airport', 'shipment_type'), ('rate_card', 'origin_port', 'destination_port', 'shipment_type')},
        ),
    ]
