# Generated by Django 5.2.5 on 2025-10-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerratecard',
            name='mode',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], default='AIR', help_text='The freight mode this card applies to (e.g., AIR, SEA).', max_length=10),
        ),
        migrations.AlterField(
            model_name='partnerratecard',
            name='shipment_type',
            field=models.CharField(choices=[('GENERAL', 'General Cargo'), ('FCL', 'FCL'), ('LCL', 'LCL'), ('BULK', 'Bulk')], default='GENERAL', help_text='The shipment type this card applies to (e.g., GENERAL, FCL, LCL).', max_length=20),
        ),
    ]
