# Generated by Django 5.2.5 on 2025-10-15 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0002_rename_created_at_ratecardfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_city_code', models.CharField(max_length=3)),
                ('destination_city_code', models.CharField(max_length=3)),
                ('carrier', models.CharField(default='PX', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PGK', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('origin_city_code', 'destination_city_code', 'carrier', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='RateCardBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_break_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='ratecards.ratecard')),
            ],
            options={
                'ordering': ['weight_break_kg'],
                'unique_together': {('rate_card', 'weight_break_kg')},
            },
        ),
        migrations.DeleteModel(
            name='RateBreak',
        ),
        migrations.DeleteModel(
            name='RatecardFile',
        ),
        migrations.DeleteModel(
            name='RateCardLane',
        ),
        migrations.DeleteModel(
            name='Surcharge',
        ),
    ]
