# Generated by Django 5.2.5 on 2025-11-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ratecards', '0002_alter_partnerratelane_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerratelane',
            name='destination_port',
            field=models.ForeignKey(blank=True, help_text='Destination port (for SEA mode - NOT YET SUPPORTED).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_destination_lanes_sea', to='core.port'),
        ),
        migrations.AlterField(
            model_name='partnerratelane',
            name='mode',
            field=models.CharField(choices=[('AIR', 'Air')], default='AIR', help_text='The freight mode this lane applies to (AIR only, for now).', max_length=10),
        ),
        migrations.AlterField(
            model_name='partnerratelane',
            name='origin_port',
            field=models.ForeignKey(blank=True, help_text='Origin port (for SEA mode - NOT YET SUPPORTED).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_origin_lanes_sea', to='core.port'),
        ),
        migrations.AlterField(
            model_name='partnerratelane',
            name='shipment_type',
            field=models.CharField(choices=[('GENERAL', 'General Cargo')], default='GENERAL', help_text='The shipment type this lane applies to (General Cargo only, for now).', max_length=20),
        ),
    ]
