# Generated by Django 5.2.5 on 2025-10-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0002_alter_partnerratecard_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerrate',
            name='unit',
            field=models.CharField(choices=[('SHIPMENT', 'Per Shipment'), ('KG', 'Per KG'), ('WM', 'Per W/M'), ('CBM', 'Per CBM'), ('TEU', 'Per TEU'), ('FEU', 'Per FEU'), ('PALLET', 'Per Pallet'), ('KM', 'Per KM')], default='PER_KG', help_text='The unit of measure for this rate.', max_length=20),
        ),
    ]
