# Generated by Django 5.2.5 on 2025-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0003_alter_partnerrate_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerratecard',
            name='name',
            field=models.CharField(help_text="A descriptive name, e.g., 'EFM AUD Import Airfreight 2025'", max_length=255, unique=True),
        ),
    ]
