# Generated by Django 5.2.5 on 2025-12-03 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aircrafttype_routelaneconstraint'),
        ('ratecards', '0003_alter_partnerratelane_destination_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerratecard',
            name='route_lane_constraint',
            field=models.ForeignKey(blank=True, help_text='Aircraft/routing constraint for this rate card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_cards', to='core.routelaneconstraint'),
        ),
        migrations.AddField(
            model_name='partnerratecard',
            name='service_level',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('VIA_BNE', 'Via Brisbane'), ('VIA_SYD', 'Via Sydney'), ('STANDARD', 'Standard')], db_index=True, default='STANDARD', help_text='Service level for routing (e.g., DIRECT for narrow-body, VIA_BNE for wide-body)', max_length=20),
        ),
    ]
