# Generated by Django 5.2.5 on 2025-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0004_partnerratecard_route_lane_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrate',
            name='tiering_json',
            field=models.JSONField(blank=True, help_text='JSON defining tiered pricing rules (e.g., weight breaks).', null=True),
        ),
    ]
