# Generated by Django 5.2.5 on 2025-12-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0005_partnerrate_tiering_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrate',
            name='max_charge_fcy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Maximum charge (cap) in the card's foreign currency (FCY).", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='partnerrate',
            name='unit',
            field=models.CharField(choices=[('SHIPMENT', 'Per Shipment'), ('KG', 'Per KG'), ('WM', 'Per W/M'), ('CBM', 'Per CBM'), ('TEU', 'Per TEU'), ('FEU', 'Per FEU'), ('PALLET', 'Per Pallet'), ('KM', 'Per KM'), ('PAGE', 'Per Page')], default='PER_KG', help_text='The unit of measure for this rate.', max_length=20),
        ),
    ]
