# Generated by Django 5.2.5 on 2025-12-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0006_partnerrate_max_charge_fcy_alter_partnerrate_unit'),
        ('services', '0007_a2d_dap_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='A2DDAPRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('AUD', 'Australian Dollar'), ('USD', 'US Dollar')], db_index=True, help_text='Currency for this rate (AUD for AU origin, USD for others)', max_length=3)),
                ('unit_basis', models.CharField(choices=[('AWB', 'Per AWB/Shipment'), ('KG', 'Per Kilogram'), ('PERCENTAGE', 'Percentage of Component')], default='AWB', help_text='How this rate is calculated', max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate amount (flat fee for AWB, per-kg rate, or percentage)', max_digits=10)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum charge (for per-kg rates)', max_digits=10, null=True)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum charge (cap for per-kg rates)', max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in UI')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent_of_component', models.ForeignKey(blank=True, help_text='Component this percentage is based on (for PERCENTAGE unit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a2d_dap_dependent_rates', to='services.servicecomponent')),
                ('service_component', models.ForeignKey(help_text='The service component this rate is for', on_delete=django.db.models.deletion.CASCADE, related_name='a2d_dap_rates', to='services.servicecomponent')),
            ],
            options={
                'verbose_name': 'A2D DAP Rate',
                'verbose_name_plural': 'A2D DAP Rates',
                'ordering': ['currency', 'display_order', 'service_component__code'],
                'unique_together': {('currency', 'service_component')},
            },
        ),
    ]
