# Generated by Django 5.2.5 on 2025-12-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0007_a2d_dap_rate'),
        ('services', '0007_a2d_dap_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a2ddaprate',
            options={'ordering': ['payment_term', 'currency', 'display_order', 'service_component__code'], 'verbose_name': 'A2D DAP Rate', 'verbose_name_plural': 'A2D DAP Rates'},
        ),
        migrations.AlterUniqueTogether(
            name='a2ddaprate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='a2ddaprate',
            name='payment_term',
            field=models.CharField(choices=[('PREPAID', 'Prepaid (Partner Agent - FCY)'), ('COLLECT', 'Collect (Local Customer - PGK)')], db_index=True, default='PREPAID', help_text='PREPAID = FCY passthrough for partner agents, COLLECT = PGK with FX for local customers', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='a2ddaprate',
            unique_together={('payment_term', 'currency', 'service_component')},
        ),
    ]
