# Generated by Django 5.2.5 on 2025-12-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0008_a2d_dap_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerratecard',
            name='rate_type',
            field=models.CharField(choices=[('BUY_RATE', 'Buy Rate (Cost)'), ('SELL_RATE', 'Sell Rate')], db_index=True, default='BUY_RATE', help_text='Whether this is a Buy/Cost rate or a Sell rate', max_length=20),
        ),
        migrations.AlterField(
            model_name='a2ddaprate',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('USD', 'US Dollar'), ('PGK', 'Papua New Guinea Kina')], db_index=True, help_text='Currency for this rate (AUD for AU origin, USD for others)', max_length=3),
        ),
    ]
