# Generated by Django 5.2.5 on 2025-12-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_lane_discriminators'),
        ('ratecards', '0009_add_rate_type_to_ratecard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerratelane',
            options={'ordering': ['mode', 'direction', 'origin_airport', 'origin_port'], 'verbose_name': 'Partner Rate Lane', 'verbose_name_plural': 'Partner Rate Lanes'},
        ),
        migrations.AlterUniqueTogether(
            name='partnerratelane',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partnerratelane',
            name='direction',
            field=models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], db_index=True, default='IMPORT', help_text='Shipment direction: IMPORT (into PNG) or EXPORT (out of PNG).', max_length=10),
        ),
        migrations.AddField(
            model_name='partnerratelane',
            name='payment_term',
            field=models.CharField(choices=[('ANY', 'Any'), ('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], db_index=True, default='ANY', help_text='Payment term constraint: ANY (both), PREPAID, or COLLECT.', max_length=10),
        ),
        migrations.AlterField(
            model_name='partnerratelane',
            name='shipment_type',
            field=models.CharField(choices=[('GENERAL', 'General Cargo')], default='GENERAL', help_text='The cargo type this lane applies to (General Cargo only, for now).', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='partnerratelane',
            unique_together={('rate_card', 'origin_airport', 'destination_airport', 'direction', 'payment_term'), ('rate_card', 'origin_port', 'destination_port', 'direction', 'payment_term')},
        ),
    ]
