# Generated by RateEngine - Backfill lane direction from airport countries
# This migration infers IMPORT/EXPORT direction based on airport countries:
# - Import = non-PNG origin -> PNG destination
# - Export = PNG origin -> non-PNG destination
# Lanes that cannot be inferred are logged for manual admin fix.

from django.db import migrations


PNG_COUNTRY_CODE = 'PG'


def infer_direction_from_airports(apps, schema_editor):
    """
    Backfill `direction` field on PartnerRateLane based on airport countries.
    
    Rules:
    - Origin in PNG, Destination outside PNG -> EXPORT
    - Origin outside PNG, Destination in PNG -> IMPORT
    - Both in PNG (domestic) -> Logs warning (manual fix needed)
    - Both outside PNG -> Logs warning (manual fix needed)
    """
    PartnerRateLane = apps.get_model('ratecards', 'PartnerRateLane')
    
    lanes_updated = 0
    lanes_skipped = []
    
    for lane in PartnerRateLane.objects.all():
        origin_country = None
        dest_country = None
        
        # Get origin country
        if lane.origin_airport:
            if hasattr(lane.origin_airport, 'country') and lane.origin_airport.country:
                origin_country = lane.origin_airport.country.code
            elif hasattr(lane.origin_airport, 'city') and lane.origin_airport.city:
                if hasattr(lane.origin_airport.city, 'country') and lane.origin_airport.city.country:
                    origin_country = lane.origin_airport.city.country.code
        
        # Get destination country
        if lane.destination_airport:
            if hasattr(lane.destination_airport, 'country') and lane.destination_airport.country:
                dest_country = lane.destination_airport.country.code
            elif hasattr(lane.destination_airport.city, 'country') and lane.destination_airport.city.country:
                dest_country = lane.destination_airport.city.country.code
        
        # Infer direction
        inferred_direction = None
        
        if origin_country and dest_country:
            origin_is_png = (origin_country == PNG_COUNTRY_CODE)
            dest_is_png = (dest_country == PNG_COUNTRY_CODE)
            
            if origin_is_png and not dest_is_png:
                # PNG -> non-PNG = EXPORT
                inferred_direction = 'EXPORT'
            elif not origin_is_png and dest_is_png:
                # non-PNG -> PNG = IMPORT
                inferred_direction = 'IMPORT'
            # else: both PNG (domestic) or both non-PNG (unclear) - skip
        
        # Secondary: Try to infer from rate card name patterns
        if not inferred_direction and lane.rate_card:
            card_name = lane.rate_card.name.upper()
            if 'IMPORT' in card_name or 'IMP' in card_name:
                inferred_direction = 'IMPORT'
            elif 'EXPORT' in card_name or 'EXP' in card_name:
                inferred_direction = 'EXPORT'
        
        if inferred_direction:
            lane.direction = inferred_direction
            lane.save(update_fields=['direction'])
            lanes_updated += 1
        else:
            # Could not infer - log for manual fix
            lanes_skipped.append({
                'id': lane.id,
                'rate_card': lane.rate_card.name if lane.rate_card else 'None',
                'origin': str(lane.origin_airport) if lane.origin_airport else 'None',
                'destination': str(lane.destination_airport) if lane.destination_airport else 'None',
                'origin_country': origin_country,
                'dest_country': dest_country,
            })
    
    # Print summary
    print(f"\n{'='*60}")
    print(f"LANE DIRECTION BACKFILL SUMMARY")
    print(f"{'='*60}")
    print(f"Lanes updated: {lanes_updated}")
    print(f"Lanes skipped (need manual fix): {len(lanes_skipped)}")
    
    if lanes_skipped:
        print(f"\n{'='*60}")
        print(f"LANES THAT COULD NOT BE INFERRED (MANUAL FIX REQUIRED)")
        print(f"{'='*60}")
        for lane_info in lanes_skipped:
            print(f"  Lane ID: {lane_info['id']}")
            print(f"    Rate Card: {lane_info['rate_card']}")
            print(f"    Route: {lane_info['origin']} -> {lane_info['destination']}")
            print(f"    Countries: {lane_info['origin_country']} -> {lane_info['dest_country']}")
            print()


def reverse_backfill(apps, schema_editor):
    """Reverse operation: reset all lanes to default IMPORT."""
    PartnerRateLane = apps.get_model('ratecards', 'PartnerRateLane')
    PartnerRateLane.objects.all().update(direction='IMPORT')


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0010_add_lane_discriminators'),
    ]

    operations = [
        migrations.RunPython(
            infer_direction_from_airports,
            reverse_code=reverse_backfill,
        ),
    ]
