# Generated by Django 5.2.5 on 2026-03-05

from django.db import migrations, models
from django.utils import timezone


def archive_a2d_dap_rates(apps, schema_editor):
    A2DDAPRate = apps.get_model('ratecards', 'A2DDAPRate')
    A2DDAPRateArchive = apps.get_model('ratecards', 'A2DDAPRateArchive')

    batch = []
    now = timezone.now()

    qs = A2DDAPRate.objects.select_related('service_component', 'percent_of_component').all().order_by('id')
    for rate in qs.iterator(chunk_size=500):
        service_component = getattr(rate, 'service_component', None)
        percent_of_component = getattr(rate, 'percent_of_component', None)

        snapshot = {
            'source_rate_id': rate.id,
            'payment_term': rate.payment_term,
            'currency': rate.currency,
            'service_component_id': str(getattr(service_component, 'id', '')) if getattr(service_component, 'id', None) is not None else None,
            'service_component_code': getattr(service_component, 'code', None),
            'unit_basis': rate.unit_basis,
            'rate': str(rate.rate),
            'min_charge': str(rate.min_charge) if rate.min_charge is not None else None,
            'max_charge': str(rate.max_charge) if rate.max_charge is not None else None,
            'percent_of_component_id': str(getattr(percent_of_component, 'id', '')) if getattr(percent_of_component, 'id', None) is not None else None,
            'percent_of_component_code': getattr(percent_of_component, 'code', None),
            'display_order': rate.display_order,
            'is_active': rate.is_active,
            'source_created_at': rate.created_at.isoformat() if rate.created_at else None,
            'source_updated_at': rate.updated_at.isoformat() if rate.updated_at else None,
        }

        batch.append(
            A2DDAPRateArchive(
                source_rate_id=rate.id,
                payment_term=rate.payment_term,
                currency=rate.currency,
                service_component_code=getattr(service_component, 'code', '') or '',
                unit_basis=rate.unit_basis,
                rate=rate.rate,
                min_charge=rate.min_charge,
                max_charge=rate.max_charge,
                percent_of_component_code=getattr(percent_of_component, 'code', None),
                display_order=rate.display_order,
                is_active=rate.is_active,
                source_created_at=rate.created_at,
                source_updated_at=rate.updated_at,
                archived_at=now,
                snapshot=snapshot,
            )
        )

        if len(batch) >= 500:
            A2DDAPRateArchive.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []

    if batch:
        A2DDAPRateArchive.objects.bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0011_backfill_lane_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='A2DDAPRateArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_rate_id', models.BigIntegerField(db_index=True, unique=True)),
                ('payment_term', models.CharField(db_index=True, max_length=10)),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('service_component_code', models.CharField(db_index=True, max_length=50)),
                ('unit_basis', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percent_of_component_code', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(db_index=True, default=timezone.now)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'A2D DAP Rate Archive',
                'verbose_name_plural': 'A2D DAP Rate Archive',
                'db_table': 'a2d_dap_rate_archive',
                'ordering': ['-archived_at', 'source_rate_id'],
            },
        ),
        migrations.RunPython(archive_a2d_dap_rates, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='A2DDAPRate',
        ),
    ]
