# Generated by Django 5.2.5 on 2026-03-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0012_archive_and_remove_a2ddaprate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A2DDAPRateArchive',
        ),
    ]
