# Generated by Django on 2026-09-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratecards', '0013_delete_a2ddapratearchive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerRate',
        ),
        migrations.DeleteModel(
            name='PartnerRateLane',
        ),
        migrations.DeleteModel(
            name='PartnerRateCard',
        ),
    ]
