# Generated by Django 5.2.5 on 2025-09-17 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('basis', models.TextField()),
                ('default_tax_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'fee_types',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('country_code', models.CharField(default='PG', max_length=2)),
                ('audience', models.TextField()),
                ('default_sell_currency', models.TextField()),
                ('gst_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disbursement_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursement_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audience', models.TextField(unique=True)),
                ('caf_on_fx', models.BooleanField()),
                ('gst_applies', models.BooleanField()),
                ('gst_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'pricing_policy',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('provider_type', models.TextField()),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='e.g., Australia East Coast to Lae', unique=True)),
                ('origin_country', models.CharField(help_text='ISO 3166-1 alpha-2 code, e.g., AU', max_length=2)),
                ('dest_country', models.CharField(help_text='ISO 3166-1 alpha-2 code, e.g., PG', max_length=2)),
                ('shipment_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], max_length=16)),
                ('requires_manual_rate', models.BooleanField(default=False, help_text='If true, trigger manual rate request for all quotes on this route.')),
            ],
            options={
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('basis', models.TextField()),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iata', models.TextField(unique=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_of_ts', models.DateTimeField()),
                ('base_ccy', models.TextField()),
                ('quote_ccy', models.TextField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_type', models.CharField(default='BUY', help_text="Distinguishes between TT 'BUY' and 'SELL' rates.", max_length=8)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currency_rates',
                'unique_together': {('as_of_ts', 'base_ccy', 'quote_ccy', 'rate_type')},
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.organizations')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='COMPLETE', help_text='e.g., COMPLETE, PENDING_RATE, EXPIRED', max_length=32)),
                ('request_snapshot', models.JSONField()),
                ('buy_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sell_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('incoterm', models.CharField(blank=True, help_text='e.g., DAP, EXW', max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_engine.organizations')),
            ],
            options={
                'verbose_name_plural': 'Quotes',
                'db_table': 'quotes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuoteLines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('is_buy', models.BooleanField()),
                ('is_sell', models.BooleanField()),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=16)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('extended_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('manual_rate_required', models.BooleanField(default=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rate_engine.quotes')),
            ],
            options={
                'db_table': 'quote_lines',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ratecards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('role', models.TextField()),
                ('scope', models.TextField()),
                ('direction', models.TextField()),
                ('audience', models.TextField(blank=True, null=True)),
                ('commodity_code', models.CharField(default='GCR', help_text='e.g., GCR, DGR, LAR, PER', max_length=8)),
                ('rate_strategy', models.CharField(blank=True, default='BREAKS', max_length=32, null=True)),
                ('currency', models.TextField()),
                ('source', models.TextField()),
                ('status', models.TextField()),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.providers')),
            ],
            options={
                'db_table': 'ratecards',
                'unique_together': {('provider', 'name', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='RatecardFees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.TextField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percent_of_code', models.TextField(blank=True, null=True)),
                ('per_kg_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applies_if', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.feetypes')),
                ('ratecard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.ratecards')),
            ],
            options={
                'db_table': 'ratecard_fees',
            },
        ),
        migrations.CreateModel(
            name='RatecardConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dim_factor_kg_per_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_strategy', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('ratecard', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.ratecards')),
            ],
            options={
                'db_table': 'ratecard_config',
            },
        ),
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percent_of_service_code', models.TextField(blank=True, null=True)),
                ('tax_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_code', models.TextField(blank=True, null=True)),
                ('conditions_json', models.JSONField()),
                ('ratecard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.ratecards')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.services')),
            ],
            options={
                'db_table': 'service_items',
            },
        ),
        migrations.CreateModel(
            name='SellCostLinksSimple',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mapping_type', models.TextField()),
                ('mapping_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('buy_fee_code', models.ForeignKey(db_column='buy_fee_code', on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.feetypes', to_field='code')),
                ('sell_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.serviceitems')),
            ],
            options={
                'db_table': 'sell_cost_links_simple',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.organizations')),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='RouteLegs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(help_text='Order of the leg in the journey, e.g., 1, 2, 3...')),
                ('leg_scope', models.CharField(default='INTERNATIONAL', max_length=32)),
                ('service_type', models.CharField(default='LINEHAUL', help_text='e.g., LINEHAUL, CLEARANCE, ONFORWARDING', max_length=32)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='rate_engine.routes')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rate_engine.stations')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rate_engine.stations')),
            ],
            options={
                'db_table': 'route_legs',
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Lanes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('airline', models.TextField(blank=True, null=True)),
                ('is_direct', models.BooleanField()),
                ('ratecard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.ratecards')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lanes_dest_set', to='rate_engine.stations')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.stations')),
                ('via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lanes_via_set', to='rate_engine.stations')),
            ],
            options={
                'db_table': 'lanes',
                'unique_together': {('ratecard', 'origin', 'dest')},
            },
        ),
        migrations.CreateModel(
            name='StorageTiers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_code', models.TextField()),
                ('week_from', models.SmallIntegerField()),
                ('week_to', models.SmallIntegerField()),
                ('rate_per_kg_per_week', models.DecimalField(decimal_places=4, max_digits=12)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ratecard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.ratecards')),
            ],
            options={
                'db_table': 'storage_tiers',
            },
        ),
        migrations.CreateModel(
            name='LaneBreaks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('break_code', models.TextField()),
                ('per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.lanes')),
            ],
            options={
                'db_table': 'lane_breaks',
                'unique_together': {('lane', 'break_code')},
            },
        ),
        migrations.CreateModel(
            name='CartageLadders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_per_kg', models.DecimalField(decimal_places=4, max_digits=12)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ratecard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rate_engine.ratecards')),
            ],
            options={
                'db_table': 'cartage_ladders',
                'unique_together': {('ratecard', 'min_weight_kg', 'max_weight_kg')},
            },
        ),
    ]
