# Generated by Django 5.2.5 on 2025-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratecards",
            name="commodity_code",
            field=models.CharField(
                max_length=8,
                default="GCR",
                help_text="e.g., GCR, DGR, LAR, PER",
            ),
        ),
        migrations.AddField(
            model_name="routes",
            name="requires_manual_rate",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If true, trigger manual rate request for all quotes on this route."
                ),
            ),
        ),
    ]

