# Generated by Django 5.2.5 on 2025-09-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate_engine", "0002_currency_rates_unique_rate_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartageladders",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="contacts",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="currencyrates",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="feetypes",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="lanebreaks",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="lanes",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="organizations",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="pricingpolicy",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="providers",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="ratecardconfig",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="ratecardfees",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="ratecards",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="routelegs",
            options={"managed": True, "ordering": ["route", "sequence"]},
        ),
        migrations.AlterModelOptions(
            name="routes",
            options={"managed": True, "verbose_name_plural": "Routes"},
        ),
        migrations.AlterModelOptions(
            name="sellcostlinkssimple",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="serviceitems",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="services",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="sites",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="stations",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="storagetiers",
            options={"managed": True},
        ),
        migrations.AddField(
            model_name="quotes",
            name="incoterm",
            field=models.CharField(
                blank=True, help_text="e.g., DAP, EXW", max_length=16, null=True
            ),
        ),
    ]
