# Generated by Django 5.2.5 on 2025-09-15 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate_engine", "0002_currency_rates_unique_rate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotes",
            name="incoterm",
            field=models.CharField(
                blank=True, help_text="e.g., DAP, EXW", max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quotelines",
            name="currency",
            field=models.CharField(
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}$", "Must be a 3-letter uppercase ISO currency code."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quotes",
            name="currency",
            field=models.CharField(
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}$", "Must be a 3-letter uppercase ISO currency code."
                    )
                ],
            ),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE currency_rates
                    ALTER COLUMN base_ccy TYPE varchar(3),
                    ALTER COLUMN quote_ccy TYPE varchar(3);
                CREATE INDEX IF NOT EXISTS currency_rates_base_quote_type_asof_idx
                    ON currency_rates (base_ccy, quote_ccy, rate_type, as_of_ts);
                ALTER TABLE ratecard_fees
                    ALTER COLUMN currency TYPE varchar(3);
                ALTER TABLE ratecards
                    ALTER COLUMN currency TYPE varchar(3);
                ALTER TABLE service_items
                    ALTER COLUMN currency TYPE varchar(3);
                ALTER TABLE organizations
                    ALTER COLUMN default_sell_currency TYPE varchar(3);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS currency_rates_base_quote_type_asof_idx;
                ALTER TABLE currency_rates
                    ALTER COLUMN base_ccy TYPE text,
                    ALTER COLUMN quote_ccy TYPE text;
                ALTER TABLE ratecard_fees
                    ALTER COLUMN currency TYPE text;
                ALTER TABLE ratecards
                    ALTER COLUMN currency TYPE text;
                ALTER TABLE service_items
                    ALTER COLUMN currency TYPE text;
                ALTER TABLE organizations
                    ALTER COLUMN default_sell_currency TYPE text;
            """,
        ),
    ]
