# Generated by Django 5.2.5 on 2025-09-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate_engine", "0002_currency_rates_unique_rate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotes",
            name="incoterm",
            field=models.CharField(
                blank=True, help_text="e.g., DAP, EXW", max_length=16, null=True
            ),
        ),
    ]
