# Generated by Django 5.2.5 on 2025-09-11 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_engine', '0002_add_commodity_code_and_requires_manual_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotelines',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'managed': True},
        ),
    ]
