# Generated by Django 5.2.5 on 2025-09-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_engine', '0003_create_admin_tables'),
        ('rate_engine', '0004_seed_stations_initial'),
    ]

    operations = [
    ]
