# Generated by Django 5.2.5 on 2025-09-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_engine', '0005_update_state_to_quotes_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='status',
            field=models.CharField(default='COMPLETE', help_text='e.g., COMPLETE, PENDING_RATE, EXPIRED', max_length=32),
        ),
    ]
