# Generated by Django 5.2.5 on 2025-11-06 22:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['country__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code.', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='ISO 4217 currency code.', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('minor_units', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='FxSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(max_length=50)),
                ('rates', models.JSONField(help_text='A JSON blob of all currency rates at the time of the snapshot.')),
                ('caf_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='Currency Adjustment Factor % applied at the time of snapshot.', max_digits=5)),
                ('fx_buffer_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='Additional FX buffer/hedge % applied at the time of snapshot.', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Policy', max_length=100)),
                ('caf_import_pct', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('caf_export_pct', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('margin_pct', models.DecimalField(decimal_places=4, default=0.15, max_digits=5)),
                ('is_pgk_per_fcy', models.BooleanField(default=True)),
                ('rounding_mode_agent_aud', models.CharField(choices=[('PER_LINE_UP', 'Per Line Up'), ('TOTAL_UP', 'Total Up')], default='PER_LINE_UP', max_length=20)),
                ('include_gst_in_agent_quote', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(help_text='IATA 3-letter airport code.', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city')),
            ],
            options={
                'ordering': ['iata_code'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.CreateModel(
            name='LocalTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_code', models.CharField(help_text="e.g., 'CARTAGE', 'CLEARANCE', 'AGENCY_FEE'", max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('basis', models.CharField(choices=[('FLAT', 'Flat Rate'), ('PER_KG', 'Per Kilogram'), ('FORMULA', 'Complex Formula')], max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('formula_name', models.CharField(blank=True, help_text="Name of the function in code to calculate this, e.g., 'calculate_png_cartage'.", max_length=50, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('unlocode', models.CharField(help_text='UN/LOCODE (e.g., PGPOM, AUBNE).', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city')),
            ],
            options={
                'ordering': ['unlocode'],
            },
        ),
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g., AW, BI, MY, SC, BP', max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('basis', models.CharField(choices=[('FLAT', 'Flat Rate'), ('PER_KG', 'Per Kilogram'), ('FORMULA', 'Complex Formula')], max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('formula', models.TextField(blank=True, help_text='For complex rules like BP, implemented in code.', null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tt_buy', models.DecimalField(blank=True, decimal_places=8, help_text='Telegraphic Transfer Buy Rate', max_digits=18, null=True)),
                ('tt_sell', models.DecimalField(blank=True, decimal_places=8, help_text='Telegraphic Transfer Sell Rate', max_digits=18, null=True)),
                ('source', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField()),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_base_rates', to='core.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_quote_rates', to='core.currency')),
            ],
            options={
                'unique_together': {('base_currency', 'quote_currency', 'source')},
            },
        ),
    ]
