# Generated by Django 5.2.5 on 2025-09-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('basis', models.TextField()),
                ('default_tax_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'fee_types',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('provider_type', models.TextField()),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('basis', models.TextField()),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iata', models.TextField(unique=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_of_ts', models.DateTimeField()),
                ('base_ccy', models.TextField()),
                ('quote_ccy', models.TextField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_type', models.CharField(default='BUY', help_text="Distinguishes between TT 'BUY' and 'SELL' rates.", max_length=8)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currency_rates',
                'unique_together': {('as_of_ts', 'base_ccy', 'quote_ccy', 'rate_type')},
            },
        ),
    ]
