# Generated by Django 5.2.5 on 2025-09-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stations",
            name="max_service_level",
            field=models.CharField(
                choices=[
                    ("DOOR_DOOR", "Door to Door"),
                    ("DOOR_AIRPORT", "Door to Airport"),
                    ("AIRPORT_DOOR", "Airport to Door"),
                    ("AIRPORT_ONLY", "Airport Only"),
                ],
                default="AIRPORT_ONLY",
                help_text="Maximum service level available at this station.",
                max_length=16,
            ),
        ),
    ]
