# Generated by Django 5.2.5 on 2025-10-22 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxsnapshot',
            name='caf_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='Currency Adjustment Factor % applied at the time of snapshot.', max_digits=5),
        ),
        migrations.AddField(
            model_name='fxsnapshot',
            name='fx_buffer_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), help_text='Additional FX buffer/hedge % applied at the time of snapshot.', max_digits=5),
        ),
    ]
