# Generated by Django 5.2.5 on 2025-11-15 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Default currency used in this country.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='core.currency'),
        ),
    ]
