# Generated by Django 5.2.5 on 2025-09-19 11:16

from django.db import migrations


def set_initial_service_levels(apps, schema_editor):
    """
    Set initial max_service_level values for key PNG stations based on business rules.
    - POM and LAE support Door-to-Door.
    - Other PNG ports are limited to Airport services.
    """
    Station = apps.get_model("core", "Stations")
    db_alias = schema_editor.connection.alias

    # Stations that support Door-to-Door services
    door_to_door_stations = ["POM", "LAE"]
    Station.objects.using(db_alias).filter(iata__in=door_to_door_stations).update(
        max_service_level="DOOR_DOOR"
    )

    # Other known PNG stations that are limited to Airport Only
    # This is not exhaustive but covers the main ones from QuotingMatrix.md
    outer_ports = ["HGU", "RAB", "HKN", "MAG", "WWK"]
    Station.objects.using(db_alias).filter(iata__in=outer_ports).update(
        max_service_level="AIRPORT_ONLY"
    )

    # Any other station in PNG defaults to AIRPORT_ONLY, which is already the model's default.
    # So no explicit action is needed for them unless we want to be more specific.

def reverse_service_levels(apps, schema_editor):
    """
    Revert the max_service_level to the default "AIRPORT_ONLY".
    """
    Station = apps.get_model("core", "Stations")
    db_alias = schema_editor.connection.alias
    # This is a simple reversal; it just sets everything back to the default.
    Station.objects.using(db_alias).filter(country="PG").update(
        max_service_level="AIRPORT_ONLY"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_stations_max_service_level"),
    ]

    operations = [
        migrations.RunPython(set_initial_service_levels, reverse_code=reverse_service_levels),
    ]
