# Generated by Django 5.2.5 on 2025-11-16 00:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('AIRPORT', 'Airport'), ('PORT', 'Port'), ('CITY', 'City'), ('ADDRESS', 'Address')], db_index=True, max_length=20)),
                ('name', models.CharField(help_text='Human-readable label for the location.', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Reference code (e.g., IATA, UNLOCODE, or city short code).', max_length=10)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.airport')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.country')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.port')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['kind', 'code'], name='idx_location_kind_code')],
            },
        ),
    ]
