# Generated by Django 5.2.5 on 2025-10-23 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fxsnapshot_caf_percent_fxsnapshot_fx_buffer_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['iata_code']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['country__code', 'name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(help_text='IATA 3-letter airport code.', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('unlocode', models.CharField(help_text='UN/LOCODE (e.g., PGPOM, AUBNE).', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city')),
            ],
            options={
                'ordering': ['unlocode'],
            },
        ),
    ]
