# Generated by Django 5.2.5 on 2025-11-16 00:03

from django.db import migrations


def seed_locations(apps, schema_editor):
    Location = apps.get_model('core', 'Location')
    Airport = apps.get_model('core', 'Airport')
    Port = apps.get_model('core', 'Port')

    for airport in Airport.objects.select_related('city__country__currency'):
        country = airport.city.country if airport.city else None
        Location.objects.get_or_create(
            airport=airport,
            defaults={
                'kind': 'AIRPORT',
                'name': airport.name or airport.iata_code,
                'code': airport.iata_code,
                'country': country,
                'city': airport.city,
            },
        )

    for port in Port.objects.select_related('city__country__currency'):
        country = port.city.country if port.city else None
        Location.objects.get_or_create(
            port=port,
            defaults={
                'kind': 'PORT',
                'name': port.name or port.unlocode,
                'code': port.unlocode,
                'country': country,
                'city': port.city,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location'),
    ]

    operations = [
        migrations.RunPython(seed_locations, migrations.RunPython.noop),
    ]
