# Generated by Django 5.2.5 on 2025-12-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_city_locations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='idx_location_kind_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='kind',
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(db_index=True, help_text='IATA airport code (e.g., BNE, POM, SYD)', max_length=3),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['code'], name='core_locati_code_7933e3_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'code'], name='core_locati_country_476c4b_idx'),
        ),
    ]
