# Generated by Django 5.2.5 on 2025-12-03 01:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_location_idx_location_kind_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Aircraft type code (e.g., B737, B767, A320)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full aircraft name', max_length=100)),
                ('aircraft_class', models.CharField(choices=[('NARROW_BODY', 'Narrow Body'), ('WIDE_BODY', 'Wide Body')], help_text='Aircraft classification', max_length=20)),
                ('max_length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cargo piece length in cm', max_digits=6, null=True)),
                ('max_width_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cargo piece width in cm', max_digits=6, null=True)),
                ('max_height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cargo piece height in cm', max_digits=6, null=True)),
                ('max_piece_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum individual piece weight in kg', max_digits=6, null=True)),
                ('supports_uld', models.BooleanField(default=False, help_text='Whether aircraft supports Unit Load Device (ULD) pallets')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about aircraft capabilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft Type',
                'verbose_name_plural': 'Aircraft Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RouteLaneConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_level', models.CharField(help_text='Service level code (e.g., DIRECT, VIA_BNE)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this lane is currently operational')),
                ('priority', models.IntegerField(default=1, help_text='Lower number = higher priority when selecting lanes (1 = highest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(help_text='Aircraft type operating this lane', on_delete=django.db.models.deletion.PROTECT, related_name='route_lanes', to='core.aircrafttype')),
                ('destination', models.ForeignKey(help_text='Destination location for this lane', on_delete=django.db.models.deletion.CASCADE, related_name='lane_constraints_destination', to='core.location')),
                ('origin', models.ForeignKey(help_text='Origin location for this lane', on_delete=django.db.models.deletion.CASCADE, related_name='lane_constraints_origin', to='core.location')),
                ('via_location', models.ForeignKey(blank=True, help_text='Intermediate routing point (e.g., BNE for SYD→BNE→POM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lane_constraints_via', to='core.location')),
            ],
            options={
                'verbose_name': 'Route Lane Constraint',
                'verbose_name_plural': 'Route Lane Constraints',
                'ordering': ['origin__code', 'destination__code', 'priority'],
                'unique_together': {('origin', 'destination', 'service_level')},
            },
        ),
    ]
