# Generated by Django 5.2.5 on 2025-12-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aircrafttype_routelaneconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='margin_pct',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
        ),
    ]
