# Generated by Django 5.2.5 on 2026-01-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_lane_discriminators'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='kind',
            field=models.CharField(
                choices=[('AIRPORT', 'Airport'), ('PORT', 'Port'), ('CITY', 'City'), ('ADDRESS', 'Address')],
                db_index=True,
                default='AIRPORT',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['kind', 'code'], name='idx_location_kind_code'),
        ),
    ]
