# Generated by Django 5.2.5 on 2026-03-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_location_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalTariff',
        ),
    ]
