# Generated by Django 5.2.5 on 2026-04-16 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_localtariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(db_index=True, help_text='IATA airport code (e.g., BNE, POM, SYD)', max_length=3, validators=[django.core.validators.RegexValidator(message='Location code must be a 3-letter uppercase IATA code.', regex='^[A-Z]{3}$')]),
        ),
    ]
