# Generated by Django 5.2.5 on 2026-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_branch',
            field=models.BooleanField(default=False, help_text='True if this location is an EFM branch/office.'),
        ),
    ]
