# Generated by Django 5.2.14 on 2026-09-21 05:42

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("core", "0011_alter_location_code"),)

    operations = (
        migrations.CreateModel(
            name="GeoLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canonical_name", models.CharField(max_length=255)),
                ("country_code", models.CharField(max_length=2)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("AIRPORT", "Airport"),
                            ("SEAPORT", "Seaport"),
                            ("CITY", "City"),
                            ("INLAND_HUB", "Inland hub"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "geo_location",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "location_type__in",
                                ["AIRPORT", "SEAPORT", "CITY", "INLAND_HUB"],
                            )
                        ),
                        name="geo_location_type_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GeoLocationIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("IATA", "IATA"),
                            ("ICAO", "ICAO"),
                            ("UNLOCODE", "UN/LOCODE"),
                            ("INTERNAL_STATION", "Internal station"),
                        ],
                        max_length=16,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identifiers",
                        to="core.geolocation",
                    ),
                ),
            ],
            options={
                "db_table": "geo_location_identifier",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scheme", "code"),
                        name="geo_identifier_scheme_code_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "scheme__in",
                                ["IATA", "ICAO", "UNLOCODE", "INTERNAL_STATION"],
                            )
                        ),
                        name="geo_identifier_scheme_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("code", ""), _negated=True),
                            (
                                "code",
                                django.db.models.functions.text.Upper(
                                    django.db.models.functions.text.Trim("code")
                                ),
                            ),
                        ),
                        name="geo_identifier_code_normalized",
                    ),
                ],
            },
        ),
    )
