# Generated by Django 5.2.14 on 2026-09-21 22:49

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0012_clean_db_foundation'),
    )

    operations = (
        migrations.CreateModel(
            name='FxMarketRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('effective_date', models.DateField()),
                ('tt_buy_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('tt_sell_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('mid_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'fx_market_rate',
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'effective_date', 'source'), name='fx_market_rate_unique_entry'), models.CheckConstraint(condition=models.Q(('tt_buy_rate__gt', 0)), name='fx_market_tt_buy_positive'), models.CheckConstraint(condition=models.Q(('tt_sell_rate__gt', 0)), name='fx_market_tt_sell_positive'), models.CheckConstraint(condition=models.Q(('mid_rate__gt', 0)), name='fx_market_mid_rate_positive'), models.CheckConstraint(condition=models.Q(('base_currency', django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('base_currency')))), name='fx_market_base_currency_normalized'), models.CheckConstraint(condition=models.Q(('quote_currency', django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('quote_currency')))), name='fx_market_quote_currency_normalized'), models.CheckConstraint(condition=models.Q(('base_currency', models.F('quote_currency')), _negated=True), name='fx_market_currencies_distinct')],
            },
        ),
        migrations.CreateModel(
            name='GeoCorridorPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], max_length=16)),
                ('automation_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_transit_hub', models.BooleanField(default=False)),
                ('default_transit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridor_destinations', to='core.geolocation')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridor_origins', to='core.geolocation')),
                ('via_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridor_hubs', to='core.geolocation')),
            ],
            options={
                'db_table': 'geo_corridor_policy',
                'constraints': [models.UniqueConstraint(condition=models.Q(('via_hub__isnull', True)), fields=('origin', 'destination', 'transport_mode'), name='geo_corridor_direct_uniq'), models.UniqueConstraint(condition=models.Q(('via_hub__isnull', False)), fields=('origin', 'destination', 'transport_mode', 'via_hub'), name='geo_corridor_hub_uniq'), models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='geo_corridor_origin_dest_distinct'), models.CheckConstraint(condition=models.Q(('via_hub__isnull', True), models.Q(models.Q(('via_hub', models.F('origin')), _negated=True), models.Q(('via_hub', models.F('destination')), _negated=True)), _connector='OR'), name='geo_corridor_via_hub_distinct'), models.CheckConstraint(condition=models.Q(('requires_transit_hub', False), ('via_hub__isnull', False), _connector='OR'), name='geo_corridor_hub_required_when_flagged'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='geo_corridor_valid_window'), models.CheckConstraint(condition=models.Q(('transport_mode__in', ['AIR', 'SEA', 'ROAD'])), name='geo_corridor_transport_mode_valid')],
            },
        ),
    )
