# Generated by hand to seed branch locations

from django.db import migrations

def seed_branch_locations(apps, schema_editor):
    Location = apps.get_model('core', 'Location')
    branch_codes = ['POM', 'LAE', 'BNE', 'HIR', 'NAN', 'SUV']
    
    # Update locations to be branches
    Location.objects.filter(code__in=branch_codes).update(is_branch=True)
    
    # Ensure other locations are NOT branches (just in case)
    Location.objects.exclude(code__in=branch_codes).update(is_branch=False)

def unseed_branch_locations(apps, schema_editor):
    Location = apps.get_model('core', 'Location')
    Location.objects.update(is_branch=False)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_location_is_branch'),
    ]

    operations = [
        migrations.RunPython(seed_branch_locations, unseed_branch_locations),
    ]
