# Generated by Django 5.2.14 on 2026-09-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_clean_db_commercial_corridor_fx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routelaneconstraint',
            name='aircraft_type',
        ),
        migrations.AlterUniqueTogether(
            name='routelaneconstraint',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='routelaneconstraint',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='routelaneconstraint',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='routelaneconstraint',
            name='via_location',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='currency',
        ),
        migrations.DeleteModel(
            name='AircraftType',
        ),
        migrations.DeleteModel(
            name='RouteLaneConstraint',
        ),
        migrations.DeleteModel(
            name='Surcharge',
        ),
    ]
