# Generated by Django 5.2.14 on 2026-09-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_aircrafttype_routelaneconstraint_surcharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FxRate',
        ),
    ]
