# Generated by Django 5.2.5 on 2025-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcogs',
            name='percent_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage rate (e.g., 20.00 for 20%)', max_digits=5, null=True),
        ),
    ]
