# Generated by Django 5.2.5 on 2025-12-17 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0002_importcogs_percent_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('DOMESTIC_AIR', 'Domestic Air'), ('EXPORT_AIR', 'Export Air'), ('IMPORT_AIR', 'Import Air')], db_index=True, max_length=20)),
                ('rate_type', models.CharField(choices=[('FLAT', 'Fixed Per Shipment'), ('PER_KG', 'Per Kilogram'), ('PERCENT', 'Percentage')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='PGK', max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.ForeignKey(help_text='The ProductCode this surcharge represents', on_delete=django.db.models.deletion.PROTECT, related_name='surcharges', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Surcharge',
                'verbose_name_plural': 'Surcharges',
                'db_table': 'surcharges',
                'ordering': ['service_type', 'product_code'],
                'unique_together': {('product_code', 'service_type', 'valid_from')},
            },
        ),
    ]
