# Generated by Django 5.2.5 on 2025-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0003_surcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='surcharge',
            name='rate_side',
            field=models.CharField(choices=[('COGS', 'Cost of Goods Sold'), ('SELL', 'Sell Rate')], db_index=True, default='COGS', max_length=4),
        ),
    ]
