# Generated by Django 5.2.5 on 2025-12-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0004_surcharge_rate_side'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surcharge',
            unique_together={('product_code', 'service_type', 'rate_side', 'valid_from')},
        ),
    ]
