# Generated by Django 5.2.5 on 2025-12-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0005_alter_surcharge_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domesticcogs',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='domesticcogs',
            name='carrier',
            field=models.ForeignKey(blank=True, help_text='For freight linehaul (e.g. PX)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domestic_cogs_rates', to='pricing_v4.carrier'),
        ),
        migrations.AlterField(
            model_name='domesticcogs',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='For local services (e.g. Cartage)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domestic_cogs_rates', to='pricing_v4.agent'),
        ),
        migrations.AddConstraint(
            model_name='domesticcogs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', True), ('carrier__isnull', False)), models.Q(('agent__isnull', False), ('carrier__isnull', True)), _connector='OR'), name='domestic_cogs_one_counterparty'),
        ),
    ]
