# Generated by Django 5.2.5 on 2025-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0006_alter_domesticcogs_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticcogs',
            name='weight_breaks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domesticsellrate',
            name='weight_breaks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='destination_filter',
            field=models.CharField(blank=True, db_index=True, help_text='IATA code to restrict destination (NULL = all destinations)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='origin_filter',
            field=models.CharField(blank=True, db_index=True, help_text='IATA code to restrict origin (NULL = all origins)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='service_type',
            field=models.CharField(choices=[('DOMESTIC_AIR', 'Domestic Air'), ('EXPORT_AIR', 'Export Air'), ('IMPORT_AIR', 'Import Air'), ('EXPORT_ORIGIN', 'Export Origin Services'), ('EXPORT_DEST', 'Export Destination Services'), ('IMPORT_ORIGIN', 'Import Origin Services'), ('IMPORT_DEST', 'Import Destination Services'), ('ALL', 'All Service Types')], db_index=True, max_length=20),
        ),
    ]
