# Generated by Django 5.2.5 on 2025-12-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0008_add_rate_lookup_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='domesticcogs',
            name='domestic_cogs_zone_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='domesticsellrate',
            name='domestic_sell_zone_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='exportcogs',
            name='export_cogs_lane_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='exportsellrate',
            name='export_sell_lane_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='importcogs',
            name='import_cogs_lane_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='importsellrate',
            name='import_sell_lane_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='surcharge',
            name='surcharge_type_side_product_idx',
        ),
    ]
