# Generated by Django 5.2.5 on 2026-01-07 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('pricing_v4', '0009_remove_domesticcogs_domestic_cogs_zone_product_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='gst_treatment',
            field=models.CharField(choices=[('STANDARD', 'Standard (10% GST)'), ('ZERO_RATED', 'Zero-Rated (Export)'), ('EXEMPT', 'Exempt (Disbursement)')], db_index=True, default='STANDARD', help_text='STANDARD=10%, ZERO_RATED=0% (tracked), EXEMPT=0% (not tracked)', max_length=15),
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount as percentage (e.g., 5.00 for 5% off)', max_digits=5)),
                ('valid_until', models.DateField(help_text='Discount expires after this date (inclusive)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer company receiving the discount', limit_choices_to={'company_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='parties.company')),
                ('product_code', models.ForeignKey(help_text='ProductCode this discount applies to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Customer Discount',
                'verbose_name_plural': 'Customer Discounts',
                'db_table': 'customer_discounts',
                'ordering': ['customer', 'product_code'],
                'unique_together': {('customer', 'product_code')},
            },
        ),
    ]
