# Generated by Django 5.2.5 on 2026-01-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0010_add_gst_treatment_and_customer_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdiscount',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='currency',
            field=models.CharField(default='PGK', help_text='Currency for FLAT_AMOUNT/FIXED_CHARGE types', max_length=3),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage Discount (e.g., 5% off)'), ('FLAT_AMOUNT', 'Flat Amount Reduction (e.g., K50 off)'), ('RATE_REDUCTION', 'Rate Reduction (e.g., K0.50/kg instead of standard)'), ('FIXED_CHARGE', 'Fixed Charge (e.g., K200 flat regardless of weight)'), ('MARGIN_OVERRIDE', 'Margin Override (e.g., 15% margin instead of 20%)')], default='PERCENTAGE', help_text='Type of discount to apply', max_length=20),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='discount_value',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Discount value (meaning depends on discount_type)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (e.g., "Negotiated Q1 2026 contract")'),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Discount starts from this date (null = immediately effective)', null=True),
        ),
    ]
