# Generated by Django 5.2.5 on 2026-01-17 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0011_enhance_customer_discount_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importsellrate',
            unique_together={('product_code', 'origin_airport', 'destination_airport', 'currency', 'valid_from')},
        ),
        migrations.CreateModel(
            name='ComponentMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('DOMESTIC_AIR', 'Domestic Air'), ('EXPORT_AIR', 'Export Air'), ('IMPORT_AIR', 'Import Air'), ('EXPORT_ORIGIN', 'Export Origin Services'), ('EXPORT_DEST', 'Export Destination Services'), ('IMPORT_ORIGIN', 'Import Origin Services'), ('IMPORT_DEST', 'Import Destination Services')], db_index=True, help_text='Apply to all products in this service group', max_length=20, null=True)),
                ('margin_type', models.CharField(choices=[('PERCENT', 'Percentage Markup'), ('FIXED', 'Fixed Amount Markup')], default='PERCENT', max_length=10)),
                ('margin_value', models.DecimalField(decimal_places=4, help_text='Percentage (e.g. 20.0 for 20%) or Fixed Amount', max_digits=10)),
                ('min_margin_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum margin amount in currency (e.g. maintain at least K10 profit)', max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.ForeignKey(blank=True, help_text='Specific product margin (overrides service type margin)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_margins', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Component Margin',
                'verbose_name_plural': 'Component Margins',
                'db_table': 'component_margins',
                'ordering': ['service_type', 'product_code'],
            },
        ),
    ]
