# Generated by Django 5.2.5 on 2026-01-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0012_add_currency_to_import_sell_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='max_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum charge cap for RATE_REDUCTION (e.g., 500.00 = K500 max)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='min_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum charge for RATE_REDUCTION (e.g., 50.00 = K50 min)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Discount expires after this date (inclusive, null = no expiry)', null=True),
        ),
    ]
