# Generated by Django 5.2.5 on 2026-01-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0013_add_minmax_charges_to_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exportsellrate',
            unique_together={('product_code', 'origin_airport', 'destination_airport', 'currency', 'valid_from')},
        ),
    ]
