# Generated by Django 5.2.5 on 2026-02-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0014_add_currency_to_export_sell_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCOGSRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, help_text='IATA airport code (origin for EXPORT, destination for IMPORT)', max_length=3)),
                ('direction', models.CharField(choices=[('EXPORT', 'Export (Origin Costs)'), ('IMPORT', 'Import (Destination Costs)')], db_index=True, help_text='EXPORT = origin costs, IMPORT = destination costs', max_length=6)),
                ('currency', models.CharField(max_length=3)),
                ('rate_type', models.CharField(choices=[('FIXED', 'Fixed Per Shipment'), ('PER_KG', 'Per Kilogram'), ('PERCENT', 'Percentage of Component')], default='FIXED', max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Rate amount (flat fee, per-kg rate, or percentage)', max_digits=10)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum charge (for per-kg rates)', max_digits=10, null=True)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum charge (cap for per-kg rates)', max_digits=10, null=True)),
                ('weight_breaks', models.JSONField(blank=True, help_text='For tiered rates: [{"min_kg": 0, "rate": "5.00"}, ...]', null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='For agent-provided services (typical for local charges)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_cogs_rates', to='pricing_v4.agent')),
                ('carrier', models.ForeignKey(blank=True, help_text='For carrier-provided services', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_cogs_rates', to='pricing_v4.carrier')),
                ('percent_of_product_code', models.ForeignKey(blank=True, help_text='For PERCENT type: the ProductCode this is a percentage of', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_cogs_dependent_rates', to='pricing_v4.productcode')),
                ('product_code', models.ForeignKey(help_text='The ProductCode this rate applies to', on_delete=django.db.models.deletion.PROTECT, related_name='local_cogs_rates', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Local COGS Rate',
                'verbose_name_plural': 'Local COGS Rates',
                'db_table': 'local_cogs_rates',
                'ordering': ['location', 'direction', 'product_code'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', True), ('carrier__isnull', False)), models.Q(('agent__isnull', False), ('carrier__isnull', True)), _connector='OR'), name='local_cogs_one_counterparty')],
            },
        ),
        migrations.CreateModel(
            name='LocalSellRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, help_text='IATA airport code (origin for EXPORT, destination for IMPORT)', max_length=3)),
                ('direction', models.CharField(choices=[('EXPORT', 'Export (Origin Charges)'), ('IMPORT', 'Import (Destination Charges)')], db_index=True, help_text='EXPORT = origin charges, IMPORT = destination charges', max_length=6)),
                ('payment_term', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect'), ('ANY', 'Any Term')], db_index=True, default='ANY', help_text='PREPAID, COLLECT, or ANY (applies to both)', max_length=7)),
                ('currency', models.CharField(max_length=3)),
                ('rate_type', models.CharField(choices=[('FIXED', 'Fixed Per Shipment'), ('PER_KG', 'Per Kilogram'), ('PERCENT', 'Percentage of Component')], default='FIXED', max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Rate amount (flat fee, per-kg rate, or percentage)', max_digits=10)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum charge (for per-kg rates)', max_digits=10, null=True)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum charge (cap for per-kg rates)', max_digits=10, null=True)),
                ('weight_breaks', models.JSONField(blank=True, help_text='For tiered cartage rates: [{"min_kg": 0, "rate": "5.00"}, ...]', null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent_of_product_code', models.ForeignKey(blank=True, help_text='For PERCENT type: the ProductCode this is a percentage of', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_sell_dependent_rates', to='pricing_v4.productcode')),
                ('product_code', models.ForeignKey(help_text='The ProductCode this rate applies to', on_delete=django.db.models.deletion.PROTECT, related_name='local_sell_rates', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Local Sell Rate',
                'verbose_name_plural': 'Local Sell Rates',
                'db_table': 'local_sell_rates',
                'ordering': ['location', 'direction', 'product_code'],
                'unique_together': {('product_code', 'location', 'direction', 'payment_term', 'currency', 'valid_from')},
            },
        ),
    ]
