# Generated by Django 5.2.5 on 2026-03-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0016_additive_to_local_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOMESTIC', 'Domestic')], db_index=True, max_length=10)),
                ('service_scope', models.CharField(choices=[('A2A', 'Airport to Airport'), ('A2D', 'Airport to Door'), ('D2A', 'Door to Airport'), ('D2D', 'Door to Door')], db_index=True, max_length=3)),
                ('commodity_code', models.CharField(choices=[('GCR', 'General Cargo'), ('SCR', 'Special Cargo'), ('DG', 'Dangerous Goods'), ('AVI', 'Live Animals'), ('PER', 'Perishables'), ('HVC', 'High Value Cargo'), ('HUM', 'Human Remains'), ('OOG', 'Oversized/Heavy Cargo'), ('VUL', 'Vulnerable Cargo'), ('TTS', 'Time/Temperature Sensitive'), ('OTHER', 'Other Special Cargo')], db_index=True, default='GCR', max_length=10)),
                ('leg', models.CharField(choices=[('ORIGIN', 'Origin'), ('MAIN', 'Main Freight'), ('DESTINATION', 'Destination')], db_index=True, max_length=11)),
                ('trigger_mode', models.CharField(choices=[('AUTO', 'Auto Include'), ('OPTIONAL', 'Optional'), ('REQUIRES_SPOT', 'Requires SPOT'), ('REQUIRES_MANUAL', 'Requires Manual Entry')], default='AUTO', max_length=20)),
                ('origin_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('destination_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('payment_term', models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], db_index=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commodity_charge_rules', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Commodity Charge Rule',
                'verbose_name_plural': 'Commodity Charge Rules',
                'db_table': 'commodity_charge_rules',
                'ordering': ['shipment_type', 'service_scope', 'commodity_code', 'product_code__id'],
                'indexes': [models.Index(fields=['shipment_type', 'service_scope', 'commodity_code', 'is_active'], name='commodity_rule_lookup_idx'), models.Index(fields=['origin_code', 'destination_code', 'payment_term'], name='commodity_rule_lane_idx')],
            },
        ),
    ]
