# Generated by Django 5.2.5 on 2026-03-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0017_commoditychargerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOMESTIC', 'Domestic')], db_index=True, max_length=10)),
                ('service_scope', models.CharField(blank=True, choices=[('A2A', 'Airport to Airport'), ('A2D', 'Airport to Door'), ('D2A', 'Door to Airport'), ('D2D', 'Door to Door')], db_index=True, help_text='Optional scope filter. Leave blank to apply to all scopes.', max_length=3, null=True)),
                ('commodity_code', models.CharField(choices=[('GCR', 'General Cargo'), ('SCR', 'Special Cargo'), ('DG', 'Dangerous Goods'), ('AVI', 'Live Animals'), ('PER', 'Perishables'), ('HVC', 'High Value Cargo'), ('HUM', 'Human Remains'), ('OOG', 'Oversized/Heavy Cargo'), ('VUL', 'Vulnerable Cargo'), ('TTS', 'Time/Temperature Sensitive'), ('OTHER', 'Other Special Cargo')], db_index=True, default='GCR', max_length=10)),
                ('requires_manager_approval', models.BooleanField(default=True)),
                ('margin_below_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum margin threshold below which approval is required.', max_digits=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commodity Approval Rule',
                'verbose_name_plural': 'Commodity Approval Rules',
                'db_table': 'commodity_approval_rules',
                'ordering': ['shipment_type', 'commodity_code', 'service_scope'],
                'indexes': [models.Index(fields=['shipment_type', 'commodity_code', 'is_active'], name='commodity_approval_lookup_idx'), models.Index(fields=['service_scope', 'effective_from'], name='commodity_approval_scope_idx')],
            },
        ),
    ]
