# Generated by Django 5.2.5 on 2026-03-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0018_commodityapprovalrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommodityApprovalRule',
        ),
    ]
