# Generated by Django 5.2.5 on 2026-04-20 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0019_delete_commodityapprovalrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importcogs',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this import COGS row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importcogs',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this import COGS row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
