# Generated by Django 5.2.5 on 2026-04-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0020_importcogs_created_by_importcogs_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('object_pk', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('RETIRE', 'Retire'), ('DELETE', 'Delete'), ('REVISE', 'Revise')], max_length=16)),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rate_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate Change Log',
                'verbose_name_plural': 'Rate Change Logs',
                'db_table': 'pricing_v4_rate_change_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['table_name', 'object_pk', '-created_at'], name='pricing_v4_rate_log_idx')],
            },
        ),
    ]
