# Generated by Django 5.2.5 on 2026-04-21 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0021_ratechangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticcogs',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this domestic COGS row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domesticcogs',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='domesticcogs',
            name='supersedes_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_rates', to='pricing_v4.domesticcogs'),
        ),
        migrations.AddField(
            model_name='domesticcogs',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this domestic COGS row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domesticsellrate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this domestic sell row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domesticsellrate',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='domesticsellrate',
            name='supersedes_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_rates', to='pricing_v4.domesticsellrate'),
        ),
        migrations.AddField(
            model_name='domesticsellrate',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this domestic sell row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportcogs',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this export COGS row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportcogs',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='exportcogs',
            name='supersedes_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_rates', to='pricing_v4.exportcogs'),
        ),
        migrations.AddField(
            model_name='exportcogs',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this export COGS row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportsellrate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this export sell row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportsellrate',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='exportsellrate',
            name='supersedes_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_rates', to='pricing_v4.exportsellrate'),
        ),
        migrations.AddField(
            model_name='exportsellrate',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this export sell row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importcogs',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='importcogs',
            name='supersedes_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_rates', to='pricing_v4.importcogs'),
        ),
        migrations.AddField(
            model_name='importsellrate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this import sell row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importsellrate',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='importsellrate',
            name='supersedes_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_rates', to='pricing_v4.importsellrate'),
        ),
        migrations.AddField(
            model_name='importsellrate',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this import sell row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localcogsrate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this local COGS row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localcogsrate',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='localcogsrate',
            name='supersedes_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_rates', to='pricing_v4.localcogsrate'),
        ),
        migrations.AddField(
            model_name='localcogsrate',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this local COGS row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localsellrate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this local sell row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localsellrate',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='localsellrate',
            name='supersedes_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_rates', to='pricing_v4.localsellrate'),
        ),
        migrations.AddField(
            model_name='localsellrate',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this local sell row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratechangelog',
            name='lineage_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
