# Generated by Django 5.2.5 on 2026-04-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0022_domesticcogs_created_by_domesticcogs_lineage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(help_text='Human-entered/raw charge label to normalize.', max_length=255)),
                ('normalized_alias_text', models.CharField(db_index=True, help_text='Deterministically normalized alias text for case-insensitive matching.', max_length=255)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact Match'), ('CONTAINS', 'Contains'), ('STARTS_WITH', 'Starts With'), ('ENDS_WITH', 'Ends With')], db_index=True, default='EXACT', max_length=11)),
                ('mode_scope', models.CharField(choices=[('ANY', 'Any Shipment Type'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOMESTIC', 'Domestic')], db_index=True, default='ANY', help_text='Shipment type scope. ANY applies across export/import/domestic.', max_length=10)),
                ('direction_scope', models.CharField(choices=[('ANY', 'Any Leg'), ('ORIGIN', 'Origin'), ('MAIN', 'Main Freight'), ('DESTINATION', 'Destination')], db_index=True, default='ANY', help_text='Leg scope. ANY applies across origin/main/destination.', max_length=11)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='Lower values win when multiple aliases match the same input.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_aliases', to='pricing_v4.productcode')),
            ],
            options={
                'verbose_name': 'Charge Alias',
                'verbose_name_plural': 'Charge Aliases',
                'db_table': 'charge_aliases',
                'ordering': ['priority', 'normalized_alias_text', 'id'],
                'indexes': [models.Index(fields=['normalized_alias_text', 'match_type', 'is_active', 'mode_scope', 'direction_scope'], name='charge_alias_lookup_idx'), models.Index(fields=['product_code', 'is_active', 'priority'], name='charge_alias_prod_idx')],
            },
        ),
    ]
