# Generated by Django 5.2.5 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing_v4", "0024_import_origin_permit_and_customs_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcode",
            name="category",
            field=models.CharField(
                choices=[
                    ("FREIGHT", "Freight"),
                    ("HANDLING", "Handling & Terminal"),
                    ("CLEARANCE", "Customs Clearance"),
                    ("DOCUMENTATION", "Documentation"),
                    ("REGULATORY", "Regulatory / Permit"),
                    ("CARTAGE", "Pickup & Delivery"),
                    ("AGENCY", "Agency Fees"),
                    ("SCREENING", "Security & Screening"),
                    ("SURCHARGE", "Surcharges"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
