# Generated by Django 5.2.5 on 2026-05-16 05:18

from django.db import migrations, models


LANE_TABLES = (
    'ExportCOGS',
    'ExportSellRate',
    'ImportSellRate',
    'DomesticCOGS',
    'DomesticSellRate',
)
LOCAL_TABLES = (
    'LocalCOGSRate',
    'LocalSellRate',
)


def backfill_scope(apps, schema_editor):
    from pricing_v4.services.import_cogs_scope import classify_import_cogs_scope
    from pricing_v4.services.pricing_rate_scope import classify_pricing_rate_scope

    ImportCOGS = apps.get_model('pricing_v4', 'ImportCOGS')
    for row in ImportCOGS.objects.select_related('product_code').only('id', 'scope', 'product_code'):
        row.scope = classify_import_cogs_scope(row).value
        row.save(update_fields=['scope'])

    for model_name in LANE_TABLES:
        model_cls = apps.get_model('pricing_v4', model_name)
        for row in model_cls.objects.select_related('product_code').only('id', 'scope', 'product_code'):
            row.scope = classify_pricing_rate_scope(row).value
            row.save(update_fields=['scope'])

    for model_name in LOCAL_TABLES:
        model_cls = apps.get_model('pricing_v4', model_name)
        model_cls.objects.update(scope='LOCAL')


def clear_scope(apps, schema_editor):
    for model_name in ('ImportCOGS', *LANE_TABLES, *LOCAL_TABLES):
        model_cls = apps.get_model('pricing_v4', model_name)
        model_cls.objects.update(scope=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0027_explicit_origin_customs_and_export_permit_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticcogs',
            name='scope',
            field=models.CharField(blank=True, choices=[('LANE', 'Lane'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('LOCAL', 'Local'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Transition scope for future rate normalization. Nullable during Phase 2.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='domesticsellrate',
            name='scope',
            field=models.CharField(blank=True, choices=[('LANE', 'Lane'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('LOCAL', 'Local'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Transition scope for future rate normalization. Nullable during Phase 2.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='exportcogs',
            name='scope',
            field=models.CharField(blank=True, choices=[('LANE', 'Lane'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('LOCAL', 'Local'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Transition scope for future rate normalization. Nullable during Phase 2.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='exportsellrate',
            name='scope',
            field=models.CharField(blank=True, choices=[('LANE', 'Lane'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('LOCAL', 'Local'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Transition scope for future rate normalization. Nullable during Phase 2.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='importcogs',
            name='scope',
            field=models.CharField(blank=True, choices=[('LANE', 'Lane'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('LOCAL', 'Local'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Transition scope for future rate normalization. Nullable during Phase 2.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='importsellrate',
            name='scope',
            field=models.CharField(blank=True, choices=[('LANE', 'Lane'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('LOCAL', 'Local'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Transition scope for future rate normalization. Nullable during Phase 2.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='localcogsrate',
            name='scope',
            field=models.CharField(blank=True, choices=[('LANE', 'Lane'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('LOCAL', 'Local'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Transition scope for future rate normalization. Local tables should resolve to LOCAL.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='localsellrate',
            name='scope',
            field=models.CharField(blank=True, choices=[('LANE', 'Lane'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('LOCAL', 'Local'), ('UNKNOWN', 'Unknown')], db_index=True, help_text='Transition scope for future rate normalization. Local tables should resolve to LOCAL.', max_length=11, null=True),
        ),
        migrations.RunPython(backfill_scope, clear_scope),
    ]
