# Generated by Django 5.2.5 on 2026-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0028_rate_scope_phase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importcogs',
            name='destination_airport',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='importcogs',
            name='origin_airport',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
