# Generated by Django 5.2.5 on 2026-06-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0030_normalize_import_cogs_origin_phase_3b'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('mode_scope', models.CharField(choices=[('ANY', 'Any Shipment Type'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOMESTIC', 'Domestic')], db_index=True, default='ANY', max_length=10)),
                ('direction_scope', models.CharField(choices=[('ANY', 'Any Leg'), ('ORIGIN', 'Origin'), ('MAIN', 'Main Freight'), ('DESTINATION', 'Destination')], db_index=True, default='ANY', max_length=15)),
                ('is_system', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canonical Charge Type',
                'verbose_name_plural': 'Canonical Charge Types',
                'db_table': 'canonical_charge_types',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='chargealias',
            name='canonical_charge_type',
            field=models.ForeignKey(blank=True, help_text='Associated CanonicalChargeType semantic layer mapping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_aliases', to='pricing_v4.canonicalchargetype'),
        ),
    ]
