# Generated by Django 5.2.5 on 2026-06-15 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0032_seed_canonical_charge_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCodeCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(help_text='Original raw label from ingestion source', max_length=100)),
                ('suggested_name', models.CharField(help_text='Suggested human-friendly description/name', max_length=200)),
                ('suggested_bucket', models.CharField(help_text='Suggested category bucket (e.g. FREIGHT, Terminal, Customs)', max_length=50)),
                ('suggested_basis', models.CharField(help_text='Suggested charge basis (e.g. per Shipment, per KG)', max_length=50)),
                ('suggested_reason', models.TextField(blank=True, help_text='Reason/context for suggesting this product code')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp of approval', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='Timestamp of rejection', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User (Admin) who approved/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_code_creation_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who requested the creation', on_delete=django.db.models.deletion.PROTECT, related_name='product_code_creation_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Code Creation Request',
                'verbose_name_plural': 'Product Code Creation Requests',
                'db_table': 'product_code_creation_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='pc_req_status_idx'), models.Index(fields=['created_at'], name='pc_req_created_at_idx')],
            },
        ),
    ]
