# Generated by Django 5.2.5 on 2026-06-15 02:14

from django.conf import settings
from django.db import migrations, models


def backfill_normalized_fields(apps, schema_editor):
    ProductCodeCreationRequest = apps.get_model('pricing_v4', 'ProductCodeCreationRequest')
    for req in ProductCodeCreationRequest.objects.all():
        # normalize: strip, lowercase, collapse internal whitespace to single space
        req.normalized_source_label = " ".join(str(req.source_label).split()).lower()
        req.normalized_suggested_name = " ".join(str(req.suggested_name).split()).lower()
        req.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0033_productcodecreationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productcodecreationrequest',
            name='pc_req_status_idx',
        ),
        migrations.AddField(
            model_name='productcodecreationrequest',
            name='normalized_source_label',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcodecreationrequest',
            name='normalized_suggested_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.RunPython(
            backfill_normalized_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='productcodecreationrequest',
            index=models.Index(fields=['status', 'normalized_source_label', 'normalized_suggested_name'], name='pc_req_dedupe_idx'),
        ),
    ]
