# Generated by Django 5.2.5 on 2026-06-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0034_add_product_code_request_normalized_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcodecreationrequest',
            name='approved_product_code',
            field=models.ForeignKey(blank=True, help_text='ProductCode linked to this request upon approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_requests', to='pricing_v4.productcode'),
        ),
    ]
