# Generated by Django 5.2.14 on 2026-07-21 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0036_productcodecreationrequest_source_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='productcode',
            name='replacement_product_code',
            field=models.ForeignKey(blank=True, help_text='Optional active replacement ProductCode when this code is retired.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_product_codes', to='pricing_v4.productcode'),
        ),
        migrations.AddField(
            model_name='productcode',
            name='retired_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductCodeContextRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code_domain', models.CharField(choices=[('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOMESTIC', 'Domestic')], db_index=True, max_length=10)),
                ('leg_role', models.CharField(choices=[('INTERNATIONAL_IMPORT', 'International Import'), ('INTERNATIONAL_EXPORT', 'International Export'), ('DOMESTIC_ON_FORWARDING', 'Domestic On-forwarding'), ('DOMESTIC_PRE_CARRIAGE', 'Domestic Pre-carriage'), ('FINAL_PICKUP', 'Final Pickup'), ('FINAL_DELIVERY', 'Final Delivery')], db_index=True, max_length=32)),
                ('commercial_position', models.CharField(choices=[('ORIGIN', 'Origin'), ('FREIGHT', 'Freight'), ('DESTINATION', 'Destination')], db_index=True, max_length=20)),
                ('transport_mode', models.CharField(choices=[('INTERNATIONAL_AIR', 'International Air'), ('DOMESTIC_AIR', 'Domestic Air'), ('LOCAL_ROAD', 'Local Road')], db_index=True, max_length=32)),
                ('operational_location', models.CharField(blank=True, db_index=True, max_length=20)),
                ('calculation_basis', models.CharField(blank=True, db_index=True, max_length=50)),
                ('service_scope', models.CharField(blank=True, db_index=True, max_length=20)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('review_status', models.CharField(choices=[('APPROVED', 'Approved'), ('CANDIDATE', 'Candidate'), ('REJECTED', 'Rejected')], db_index=True, default='CANDIDATE', max_length=20)),
                ('source', models.CharField(choices=[('ADMIN', 'Admin Managed'), ('MIGRATION', 'Reviewed Migration'), ('DIAGNOSTIC', 'Diagnostic Only')], db_index=True, default='ADMIN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_code_context_rules', to='pricing_v4.canonicalchargetype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_rules', to='pricing_v4.productcode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductCode Context Rule',
                'verbose_name_plural': 'ProductCode Context Rules',
                'db_table': 'product_code_context_rules',
                'ordering': ['priority', 'canonical_charge_type__code', 'id'],
                'indexes': [models.Index(fields=['canonical_charge_type', 'product_code_domain', 'leg_role', 'commercial_position', 'transport_mode', 'is_active', 'review_status'], name='pc_context_rule_lookup_idx'), models.Index(fields=['product_code', 'is_active', 'review_status'], name='pc_context_rule_prod_idx')],
                'constraints': [models.UniqueConstraint(fields=('canonical_charge_type', 'product_code', 'product_code_domain', 'leg_role', 'commercial_position', 'transport_mode', 'operational_location', 'calculation_basis', 'service_scope'), name='uniq_product_context_rule_dims')],
            },
        ),
    ]
