# Generated by Django 5.2.14 on 2026-09-21 22:49

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = (
        ('parties', '0013_clean_db_foundation'),
        ('pricing_v4', '0037_phase16d_productcode_context_rules'),
    )

    operations = (
        migrations.CreateModel(
            name='CommercialProductCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FREIGHT', 'Freight'), ('ORIGIN', 'Origin'), ('DESTINATION', 'Destination'), ('CLEARANCE', 'Clearance'), ('SERVICE', 'Service')], max_length=32)),
                ('sub_category', models.CharField(blank=True, max_length=64)),
                ('gst_treatment', models.CharField(choices=[('FREIGHT_EXPORT', 'Freight Export'), ('FREIGHT_IMPORT', 'Freight Import'), ('DOMESTIC_STANDARD', 'Domestic Standard'), ('EXEMPT', 'Exempt'), ('ZERO_RATED', 'Zero Rated')], max_length=32)),
                ('charge_basis_default', models.CharField(choices=[('FLAT', 'Flat'), ('PER_KG', 'Per kg'), ('PER_CBM', 'Per cbm'), ('PER_UNIT', 'Per unit'), ('TIERED_WEIGHT', 'Tiered weight'), ('PERCENTAGE', 'Percentage')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'commercial_product_code',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), ('code', django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('code')))), name='comm_product_code_normalized'), models.CheckConstraint(condition=models.Q(('category__in', ['FREIGHT', 'ORIGIN', 'DESTINATION', 'CLEARANCE', 'SERVICE'])), name='comm_product_code_category_valid'), models.CheckConstraint(condition=models.Q(('gst_treatment__in', ['FREIGHT_EXPORT', 'FREIGHT_IMPORT', 'DOMESTIC_STANDARD', 'EXEMPT', 'ZERO_RATED'])), name='comm_product_code_gst_valid'), models.CheckConstraint(condition=models.Q(('charge_basis_default__in', ['FLAT', 'PER_KG', 'PER_CBM', 'PER_UNIT', 'TIERED_WEIGHT', 'PERCENTAGE'])), name='comm_product_code_basis_valid')],
            },
        ),
        migrations.CreateModel(
            name='CommercialTermsPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_code', models.CharField(max_length=64, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('target_gross_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('import_caf_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('export_caf_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gst_standard_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'policy_commercial_terms',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('policy_code', ''), _negated=True), ('policy_code', django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('policy_code')))), name='comm_policy_code_normalized'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='comm_policy_valid_window'), models.CheckConstraint(condition=models.Q(('target_gross_margin_percent__isnull', True), models.Q(('target_gross_margin_percent__gte', 0), ('target_gross_margin_percent__lt', 100)), _connector='OR'), name='comm_policy_margin_valid_range'), models.CheckConstraint(condition=models.Q(('import_caf_percent__isnull', True), models.Q(('import_caf_percent__gte', 0), ('import_caf_percent__lte', 100)), _connector='OR'), name='comm_policy_import_caf_range'), models.CheckConstraint(condition=models.Q(('export_caf_percent__isnull', True), models.Q(('export_caf_percent__gte', 0), ('export_caf_percent__lte', 100)), _connector='OR'), name='comm_policy_export_caf_range'), models.CheckConstraint(condition=models.Q(('gst_standard_percent__gte', 0), ('gst_standard_percent__lte', 100)), name='comm_policy_gst_standard_range')],
            },
        ),
        migrations.CreateModel(
            name='CommercialChargeAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.CharField(max_length=255)),
                ('transport_mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], max_length=16)),
                ('source_currency', models.CharField(blank=True, max_length=3)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('carrier_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_charge_aliases', to='parties.partymaster')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='pricing_v4.commercialproductcode')),
            ],
            options={
                'db_table': 'commercial_charge_alias',
                'constraints': [models.UniqueConstraint(condition=models.Q(('carrier_party__isnull', True)), fields=('raw_text', 'transport_mode'), name='charge_alias_global_uniq'), models.UniqueConstraint(condition=models.Q(('carrier_party__isnull', False)), fields=('raw_text', 'transport_mode', 'carrier_party'), name='charge_alias_carrier_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('raw_text', ''), _negated=True), ('raw_text', django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('raw_text')))), name='charge_alias_raw_text_normalized'), models.CheckConstraint(condition=models.Q(('transport_mode__in', ['AIR', 'SEA', 'ROAD'])), name='charge_alias_transport_mode_valid'), models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), name='charge_alias_confidence_range'), models.CheckConstraint(condition=models.Q(('source_currency', ''), ('source_currency__regex', '^[A-Z]{3}$'), _connector='OR'), name='charge_alias_source_currency_format')],
            },
        ),
    )
