# Generated by Django 5.2.14 on 2026-09-22 01:32

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def add_pg_exclusion_constraint(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
        schema_editor.execute(
            """
            ALTER TABLE rate_tier
            ADD CONSTRAINT rate_tier_overlap_exclude
            EXCLUDE USING gist (
                rate_line_id WITH =,
                numrange(min_quantity, max_quantity, '[)') WITH &&
            );
            """
        )


def remove_pg_exclusion_constraint(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE rate_tier DROP CONSTRAINT IF EXISTS rate_tier_overlap_exclude;"
        )


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0013_clean_db_commercial_corridor_fx'),
        ('parties', '0013_clean_db_foundation'),
        ('pricing_v4', '0038_clean_db_commercial_master'),
    )

    operations = (
        migrations.CreateModel(
            name='RateSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rate_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('transport_mode', models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('ROAD', 'Road')], max_length=8)),
                ('currency_code', models.CharField(max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('carrier', models.ForeignKey(blank=True, help_text='Optional carrier scope for BUY tariffs', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier_rate_sheets', to='parties.partymaster')),
                ('party', models.ForeignKey(blank=True, help_text='Optional customer scope for SELL tariffs', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_rate_sheets', to='parties.partymaster')),
            ],
            options={
                'db_table': 'rate_sheet',
            },
        ),
        migrations.CreateModel(
            name='RateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_basis', models.CharField(choices=[('FLAT', 'Flat'), ('PER_KG', 'Per kg'), ('PER_CBM', 'Per cbm'), ('PER_UNIT', 'Per unit'), ('TIERED_WEIGHT', 'Tiered weight'), ('PERCENTAGE', 'Percentage')], max_length=32)),
                ('unit_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Scalar unit rate for FLAT, PER_KG, PER_CBM, PER_UNIT', max_digits=18, null=True)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=4, help_text='Optional minimum charge floor', max_digits=18, null=True)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=4, help_text='Optional maximum charge ceiling', max_digits=18, null=True)),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage rate (e.g. 10.00) for PERCENTAGE basis', max_digits=5, null=True)),
                ('percentage_basis_product_code', models.ForeignKey(blank=True, help_text='Reference product code that the percentage applies to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='percentage_dependent_rate_lines', to='pricing_v4.commercialproductcode')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_lines', to='pricing_v4.commercialproductcode')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing_v4.ratesheet')),
            ],
            options={
                'db_table': 'rate_line',
            },
        ),
        migrations.CreateModel(
            name='RateTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_quantity', models.DecimalField(decimal_places=4, help_text='Tier quantity lower bound (inclusive)', max_digits=12)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Tier quantity upper bound (exclusive); NULL represents open-ended/infinity', max_digits=12, null=True)),
                ('unit_rate', models.DecimalField(decimal_places=4, help_text='Unit rate applicable to this tier quantity bracket', max_digits=18)),
                ('rate_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pricing_v4.rateline')),
            ],
            options={
                'db_table': 'rate_tier',
            },
        ),
        migrations.CreateModel(
            name='RateApplicability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_level', models.CharField(blank=True, choices=[('EXPRESS', 'Express'), ('STANDARD', 'Standard'), ('DEFERRED', 'Deferred')], max_length=32)),
                ('commodity_category', models.CharField(blank=True, max_length=64)),
                ('direction', models.CharField(blank=True, choices=[('IMPORT', 'Import'), ('EXPORT', 'Export'), ('DOMESTIC', 'Domestic')], max_length=32)),
                ('equipment_type', models.CharField(blank=True, max_length=64)),
                ('destination', models.ForeignKey(blank=True, help_text='Optional destination location filter', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.geolocation')),
                ('origin', models.ForeignKey(blank=True, help_text='Optional origin location filter', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.geolocation')),
                ('rate_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicability', to='pricing_v4.rateline')),
            ],
            options={
                'db_table': 'rate_applicability',
                'constraints': [models.CheckConstraint(condition=models.Q(('direction__in', ['', 'IMPORT', 'EXPORT', 'DOMESTIC'])), name='rate_app_direction_valid'), models.CheckConstraint(condition=models.Q(('service_level__in', ['', 'EXPRESS', 'STANDARD', 'DEFERRED'])), name='rate_app_service_level_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='ratesheet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), ('name', django.db.models.functions.text.Trim('name'))), name='rate_sheet_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='ratesheet',
            constraint=models.CheckConstraint(condition=models.Q(('currency_code__regex', '^[A-Z]{3}$')), name='rate_sheet_currency_format'),
        ),
        migrations.AddConstraint(
            model_name='ratesheet',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='rate_sheet_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='ratesheet',
            constraint=models.CheckConstraint(condition=models.Q(('rate_type__in', ['BUY', 'SELL'])), name='rate_sheet_rate_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='ratesheet',
            constraint=models.CheckConstraint(condition=models.Q(('transport_mode__in', ['AIR', 'SEA', 'ROAD'])), name='rate_sheet_transport_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='ratesheet',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='rate_sheet_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='rateline',
            constraint=models.CheckConstraint(condition=models.Q(('rate_basis__in', ['FLAT', 'PER_KG', 'PER_CBM', 'PER_UNIT', 'TIERED_WEIGHT', 'PERCENTAGE'])), name='rate_line_basis_valid'),
        ),
        migrations.AddConstraint(
            model_name='rateline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_rate__isnull', True), ('unit_rate__gte', 0), _connector='OR'), name='rate_line_unit_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rateline',
            constraint=models.CheckConstraint(condition=models.Q(('min_charge__isnull', True), ('min_charge__gte', 0), _connector='OR'), name='rate_line_min_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rateline',
            constraint=models.CheckConstraint(condition=models.Q(('max_charge__isnull', True), ('max_charge__gte', 0), _connector='OR'), name='rate_line_max_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rateline',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_rate__isnull', True), ('percentage_rate__gte', 0), _connector='OR'), name='rate_line_percentage_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rateline',
            constraint=models.CheckConstraint(condition=models.Q(('min_charge__isnull', True), ('max_charge__isnull', True), ('min_charge__lte', models.F('max_charge')), _connector='OR'), name='rate_line_min_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='rateline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rate_basis', 'PERCENTAGE'), ('percentage_rate__isnull', False), ('percentage_basis_product_code__isnull', False), ('unit_rate__isnull', True)), models.Q(('rate_basis', 'TIERED_WEIGHT'), ('unit_rate__isnull', True), ('percentage_rate__isnull', True), ('percentage_basis_product_code__isnull', True)), models.Q(('rate_basis__in', ['FLAT', 'PER_KG', 'PER_CBM', 'PER_UNIT']), ('unit_rate__isnull', False), ('percentage_rate__isnull', True), ('percentage_basis_product_code__isnull', True)), _connector='OR'), name='rate_line_basis_integrity'),
        ),
        migrations.AddConstraint(
            model_name='ratetier',
            constraint=models.CheckConstraint(condition=models.Q(('min_quantity__gte', 0)), name='rate_tier_min_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ratetier',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gt', models.F('min_quantity')), _connector='OR'), name='rate_tier_max_quantity_gt_min'),
        ),
        migrations.AddConstraint(
            model_name='ratetier',
            constraint=models.CheckConstraint(condition=models.Q(('unit_rate__gte', 0)), name='rate_tier_unit_rate_non_negative'),
        ),
        migrations.RunPython(
            add_pg_exclusion_constraint,
            reverse_code=remove_pg_exclusion_constraint,
        ),
    )
