# Generated by Django 5.2.14 on 2026-09-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v4', '0039_clean_db_rate_matrix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentMargin',
        ),
    ]
